package com.projectgoth.fusion.gateway.packet;

import com.projectgoth.fusion.common.RMIExceptionHelper;
import com.projectgoth.fusion.common.SystemProperty;
import com.projectgoth.fusion.common.SystemPropertyEntities;
import com.projectgoth.fusion.data.ContactData;
import com.projectgoth.fusion.ejb.EJBHomeCache;
import com.projectgoth.fusion.ejb.FusionEJBException;
import com.projectgoth.fusion.fdl.packets.FusionPktDataAcceptContactRequest;
import com.projectgoth.fusion.gateway.ConnectionI;
import com.projectgoth.fusion.interfaces.Contact;
import com.projectgoth.fusion.interfaces.ContactHome;
import com.projectgoth.fusion.packet.FusionPacket;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.rmi.RemoteException;
import javax.ejb.CreateException;

public class FusionPktAcceptContactRequest extends FusionPktDataAcceptContactRequest {
   public FusionPktAcceptContactRequest() {
   }

   public FusionPktAcceptContactRequest(ByteBuffer byteBuffer) throws IOException {
      super(byteBuffer);
   }

   public FusionPktAcceptContactRequest(FusionPacket packet) {
      super(packet);
   }

   protected FusionPacket[] processRequest(ConnectionI connection) {
      try {
         String contactUsername = this.getContactUsername();
         if (contactUsername == null) {
            return (new FusionPktError(this.transactionId, FusionPktError.Code.UNDEFINED, "Contact username not set")).toArray();
         } else {
            Boolean shareMobilePhone = this.getShareMobilePhone();
            Contact contactEJB = (Contact)EJBHomeCache.getObject("ejb/Contact", ContactHome.class);
            ContactData contactData = new ContactData();
            contactData.username = connection.getUsername();
            contactData.fusionUsername = contactUsername;
            contactData.contactGroupId = this.getGroupId();
            contactData.displayOnPhone = true;
            if (shareMobilePhone != null) {
               contactData.shareMobilePhone = shareMobilePhone;
            }

            if (SystemProperty.getBool((SystemPropertyEntities.SystemPropertyEntryInterface)SystemPropertyEntities.Contacts.FOLLOW_ON_ADD_CONTACT_ENABLED)) {
               boolean followOnMiniblog = SystemProperty.getBool((SystemPropertyEntities.SystemPropertyEntryInterface)SystemPropertyEntities.Contacts.MIGBO_INTEGRATION_ENABLED);
               contactData = contactEJB.addFusionUserAsContact(connection.getUserID(), contactData, followOnMiniblog);
            } else {
               contactData = contactEJB.acceptContactRequest(connection.getUserID(), contactData, false);
            }

            return (Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue() ? (new FusionPktContact(this.transactionId, contactData, connection)).toArray() : (new FusionPktContactOld(this.transactionId, contactData, connection)).toArray();
         }
      } catch (CreateException var7) {
         return (new FusionPktError(this.transactionId, FusionPktError.Code.UNDEFINED, "Failed to create ContactEJB")).toArray();
      } catch (RemoteException var8) {
         return (new FusionPktError(this.transactionId, FusionPktError.Code.UNDEFINED, "Failed to accept user - " + RMIExceptionHelper.getRootMessage(var8))).toArray();
      } catch (FusionEJBException var9) {
         return (new FusionPktError(this.transactionId, FusionPktError.Code.UNDEFINED, "Failed to accept user - " + var9.getMessage())).toArray();
      }
   }
}
