package com.projectgoth.fusion.gateway.packet;

import com.projectgoth.fusion.common.SystemPropertyEntities;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktChat;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktChatListVersion;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktChatListVersionOld;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktEndMessages;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktGetChats;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktGetMessageStatusEvents;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktGetMessages;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktHaveLatestChatList;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktLatestMessagesDigest;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktSetChatName;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktSetChatNameOld;
import com.projectgoth.fusion.gateway.packet.sticker.FusionPktEndStickerPack;
import com.projectgoth.fusion.gateway.packet.sticker.FusionPktEndStickerPackOld;
import com.projectgoth.fusion.gateway.packet.sticker.FusionPktGetStickerPack;
import com.projectgoth.fusion.gateway.packet.sticker.FusionPktGetStickerPackList;
import com.projectgoth.fusion.gateway.packet.sticker.FusionPktGetStickerPackListOld;
import com.projectgoth.fusion.gateway.packet.sticker.FusionPktGetStickerPackOld;
import com.projectgoth.fusion.gateway.packet.sticker.FusionPktStickerPack;
import com.projectgoth.fusion.gateway.packet.sticker.FusionPktStickerPackList;
import com.projectgoth.fusion.gateway.packet.sticker.FusionPktStickerPackListOld;
import com.projectgoth.fusion.gateway.packet.sticker.FusionPktStickerPackOld;
import com.projectgoth.fusion.packet.FusionPacket;
import java.nio.ByteBuffer;

public class FusionPacketFactory {
   public static FusionPacket getSpecificPacket(FusionPacket packet) {
      switch(packet.getType()) {
      case 0:
         return new FusionPktError(packet);
      case 1:
         return new FusionPktOk(packet);
      case 2:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktPing(packet);
         }

         return new FusionPktPingOld(packet);
      case 3:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktPong(packet);
         }

         return new FusionPktPingReplyOld(packet);
      case 5:
         return new FusionPktAlert(packet);
      case 6:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktHelpText(packet);
         }

         return new FusionPktHelpTextOld(packet);
      case 7:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetHelpText(packet);
         }

         return new FusionPktGetHelpTextOld(packet);
      case 8:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktServerQuestion(packet);
         }

         return new FusionPktServerQuestionOld(packet);
      case 9:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktServerQuestionReply(packet);
         }

         return new FusionPktServerQuestionReplyOld(packet);
      case 10:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktReport(packet);
         }

         return new FusionPktReportOld(packet);
      case 11:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktMidletProperty(packet);
         }

         return new FusionPktMidletPropertyOld(packet);
      case 12:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetMidletProperty(packet);
         }

         return new FusionPktGetMidletPropertyOld(packet);
      case 13:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktHttpPoll(packet);
         }

         return new FusionPktHTTPPollOld(packet);
      case 14:
         return new FusionPktNotification(packet);
      case 16:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCaptcha(packet);
         }

         return new FusionPktCaptchaOld(packet);
      case 17:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCaptchaResponse(packet);
         }

         return new FusionPktCaptchaResponseOld(packet);
      case 18:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetServerQuestion(packet);
         }

         return new FusionPktGetServerQuestionOld(packet);
      case 100:
         return new FusionPktNewRegistration(packet);
      case 101:
         return new FusionPktRegistration(packet);
      case 102:
         return new FusionPktRegistrationChallenge(packet);
      case 103:
         return new FusionPktRegistrationResponse(packet);
      case 104:
         return new FusionPktRegistrationError(packet);
      case 200:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLogin(packet);
         }

         return new FusionPktLoginOld(packet);
      case 201:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLoginChallenge(packet);
         }

         return new FusionPktLoginChallengeOld(packet);
      case 202:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLoginResponse(packet);
         }

         return new FusionPktLoginResponseOld(packet);
      case 203:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLoginOk(packet);
         }

         return new FusionPktLoginOkOld(packet);
      case 204:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktActivateAccount(packet);
         }

         return new FusionPktActivateAccountOld(packet);
      case 205:
         return new FusionPktResendVerificationCode(packet);
      case 206:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktImLogin(packet);
         }

         return new FusionPktIMLoginOld(packet);
      case 207:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktImSessionStatus(packet);
         }

         return new FusionPktIMSessionStatusOld(packet);
      case 209:
         return new FusionPktLoginResponse(packet);
      case 210:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSlimLoginOk(packet);
         }

         return new FusionPktSlimLoginOkOld(packet);
      case 211:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCreateSession(packet);
         }

         return new FusionPktCreateSessionOld(packet);
      case 212:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSlimLoginChallenge(packet);
         }

         return new FusionPktSlimLoginChallengeOld(packet);
      case 300:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLogout(packet);
         }

         return new FusionPktLogoutOld(packet);
      case 301:
         return new FusionPktSessionTerminated(packet);
      case 302:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktImLogout(packet);
         }

         return new FusionPktIMLogoutOld(packet);
      case 400:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetContacts(packet);
         }

         return new FusionPktGetContactsOld(packet);
      case 401:
         return new FusionPktGroup(packet);
      case 402:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktContact(packet);
         }

         return new FusionPktContactOld(packet);
      case 403:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetContactsComplete(packet);
         }

         return new FusionPktGetContactsCompleteOld(packet);
      case 404:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktPresence(packet);
         }

         return new FusionPktPresenceOld(packet);
      case 405:
         return new FusionPktAddContact(packet);
      case 406:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktRemoveContact(packet);
         }

         return new FusionPktRemoveContactOld(packet);
      case 407:
         return new FusionPktUpdateContact(packet);
      case 408:
         return new FusionPktAddGroup(packet);
      case 409:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktRemoveGroup(packet);
         }

         return new FusionPktRemoveGroupOld(packet);
      case 410:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUpdateGroup(packet);
         }

         return new FusionPktUpdateGroupOld(packet);
      case 411:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktMoveContact(packet);
         }

         return new FusionPktMoveContactOld(packet);
      case 412:
         return new FusionPktContactRequest(packet);
      case 413:
         return new FusionPktAcceptContactRequest(packet);
      case 414:
         return new FusionPktRejectContactRequest(packet);
      case 415:
         return new FusionPktGetPermissionList(packet);
      case 416:
         return new FusionPktPermissionList(packet);
      case 417:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetPermission(packet);
         }

         return new FusionPktSetPermissionOld(packet);
      case 418:
         return new FusionPktVoiceCapability(packet);
      case 419:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktHaveLatestContactList(packet);
         }

         return new FusionPktHaveLatestContactListOld(packet);
      case 420:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktContactListVersion(packet);
         }

         return new FusionPktContactListVersionOld(packet);
      case 421:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktStatusMessage(packet);
         }

         return new FusionPktStatusMessageOld(packet);
      case 422:
         return new FusionPktUserEvent(packet);
      case 423:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktDisplayPicture(packet);
         }

         return new FusionPktDisplayPictureOld(packet);
      case 500:
         return new FusionPktMessage(packet);
      case 501:
         return new FusionPktWAPPush(packet);
      case 502:
         return new FusionPktFileReceived(packet);
      case 503:
         return new FusionPktMailInfo(packet);
      case 504:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUploadFile(packet);
         }

         return new FusionPktUploadFileOld(packet);
      case 505:
         return new FusionPktMessageStatusEvent(packet);
      case 507:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLeavePrivateChat(packet);
         }

         return new FusionPktLeavePrivateChatOld(packet);
      case 550:
         return new FusionPktGetMessages(packet);
      case 551:
         return new FusionPktGetChats(packet);
      case 552:
         return new FusionPktHaveLatestChatList(packet);
      case 560:
         return new FusionPktChat(packet);
      case 561:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktChatListVersion(packet);
         }

         return new FusionPktChatListVersionOld(packet);
      case 562:
         return new FusionPktEndMessages(packet);
      case 563:
         return new FusionPktLatestMessagesDigest(packet);
      case 564:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetChatName(packet);
         }

         return new FusionPktSetChatNameOld(packet);
      case 565:
         return new FusionPktGetMessageStatusEvents(packet);
      case 600:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetPresence(packet);
         }

         return new FusionPktSetPresenceOld(packet);
      case 601:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetStatusMessage(packet);
         }

         return new FusionPktSetStatusMessageOld(packet);
      case 602:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetDisplayPicture(packet);
         }

         return new FusionPktSetDisplayPictureOld(packet);
      case 603:
         return new FusionPktAvatar(packet);
      case 604:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktDeviceMode(packet);
         }

         return new FusionPktDeviceModeOld(packet);
      case 700:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetChatrooms(packet);
         }

         return new FusionPktGetChatRoomsOld(packet);
      case 701:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktChatroom(packet);
         }

         return new FusionPktChatRoomOld(packet);
      case 702:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetChatroomsComplete(packet);
         }

         return new FusionPktGetChatRoomsCompleteOld(packet);
      case 703:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktJoinChatroom(packet);
         }

         return new FusionPktJoinChatRoomOld(packet);
      case 704:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLeaveChatroom(packet);
         }

         return new FusionPktLeaveChatRoomOld(packet);
      case 705:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCreateChatroom(packet);
         }

         return new FusionPktCreateChatRoomOld(packet);
      case 706:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktKickChatroomParticipant(packet);
         }

         return new FusionPktKickChatRoomParticipantOld(packet);
      case 707:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetChatroomParticipants(packet);
         }

         return new FusionPktGetChatRoomParticipantsOld(packet);
      case 708:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktChatroomParticipants(packet);
         }

         return new FusionPktChatRoomParticipantsOld(packet);
      case 709:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktMuteChatroomParticipant(packet);
         }

         return new FusionPktMuteChatRoomParticipantOld(packet);
      case 710:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUnmuteChatroomParticipant(packet);
         }

         return new FusionPktUnmuteChatRoomParticipantOld(packet);
      case 711:
         return new FusionPktAddFavoriteChatroom(packet);
      case 712:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktRemoveFavoriteChatroom(packet);
         }

         return new FusionPktRemoveFavouriteChatRoomOld(packet);
      case 713:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetChatroomCategories(packet);
         }

         return new FusionPktGetChatRoomCategoriesOld(packet);
      case 714:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktChatroomCategory(packet);
         }

         return new FusionPktChatRoomCategoryOld(packet);
      case 715:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetChatroomCategoriesComplete(packet);
         }

         return new FusionPktGetChatRoomCategoriesCompleteOld(packet);
      case 716:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetCategorizedChatrooms(packet);
         }

         return new FusionPktGetCategorizedChatRoomsOld(packet);
      case 717:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetCategorizedChatroomsComplete(packet);
         }

         return new FusionPktGetCategorizedChatRoomsCompleteOld(packet);
      case 718:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktChatroomNotification(packet);
         }

         return new FusionPktChatRoomNotificationOld(packet);
      case 750:
         return new FusionPktGroupChat(packet);
      case 751:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCreateGroupChat(packet);
         }

         return new FusionPktCreateGroupChatOld(packet);
      case 752:
         return new FusionPktGroupChatInvite(packet);
      case 753:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLeaveGroupChat(packet);
         }

         return new FusionPktLeaveGroupChatOld(packet);
      case 754:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetGroupChatParticipants(packet);
         }

         return new FusionPktGetGroupChatParticipantsOld(packet);
      case 755:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGroupChatParticipants(packet);
         }

         return new FusionPktGroupChatParticipantsOld(packet);
      case 800:
         return new FusionPktPhoneCall(packet);
      case 801:
         return new FusionPktWebCall(packet);
      case 802:
         return new FusionPktWebCallNotification(packet);
      case 803:
         return new FusionPktWebCallResponse(packet);
      case 804:
         return new FusionPktDial(packet);
      case 805:
         return new FusionPktCompareCallRate(packet);
      case 806:
         return new FusionPktAnonymousCallNotification(packet);
      case 807:
         return new FusionPktAnonymousCallResponse(packet);
      case 900:
         return new FusionPktInviteFriend(packet);
      case 901:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetAccountBalance(packet);
         }

         return new FusionPktGetAccountBalanceOld(packet);
      case 902:
         return new FusionPktAccountBalance(packet);
      case 903:
         return new FusionPktRecharge(packet);
      case 904:
         return new FusionPktForgotPassword(packet);
      case 905:
         return new FusionPktGetUserProfile(packet);
      case 906:
         return new FusionPktUserProfile(packet);
      case 907:
         return new FusionPktUpdateUserProfile(packet);
      case 908:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktChangePassword(packet);
         }

         return new FusionPktChangePasswordOld(packet);
      case 909:
         return new FusionPktTransferCredit(packet);
      case 910:
         return new FusionPktGetURL(packet);
      case 911:
         return new FusionPktDynamicMenu(packet);
      case 912:
         return new FusionPktWallpaper(packet);
      case 913:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.se378HotkeyPacketFullUrlDataEnabled.getValue()) {
            return new FusionPktGetEmoticon(packet);
         }

         return new FusionPktGetEmoticonPreSE378(packet);
      case 914:
         return new FusionPktEmoticon(packet);
      case 915:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktClearEmoticonCache(packet);
         }

         return new FusionPktClearEmoticonCacheOld(packet);
      case 916:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktEmoticonHotkeys(packet);
         }

         return new FusionPktEmoticonHotKeysOld(packet);
      case 918:
         return new FusionPktMidletTab(packet);
      case 920:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktMidletAction(packet);
         }

         return new FusionPktMidletActionOld(packet);
      case 921:
         return new FusionPktChangeUserEventSetting(packet);
      case 922:
         return new FusionPktOpenURL(packet);
      case 923:
         return new FusionPktOpenURLResponse(packet);
      case 924:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktTextColor(packet);
         }

         return new FusionPktTextColourOld(packet);
      case 925:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLanguage(packet);
         }

         return new FusionPktLanguageOld(packet);
      case 926:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetImIcons(packet);
         }

         return new FusionPktGetIMIconsOld(packet);
      case 927:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktImIcons(packet);
         }

         return new FusionPktIMIconsOld(packet);
      case 928:
         return new FusionPktGetEmoticonsComplete(packet);
      case 929:
         return new FusionPktGetDynamicMenuIcon(packet);
      case 930:
         return new FusionPktDynamicMenuIcon(packet);
      case 931:
         return new FusionPktGetPreloginMarketingMsg(packet);
      case 935:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetGift(packet);
         }

         return new FusionPktGetGiftOld(packet);
      case 936:
         return new FusionPktGiftHotkeys(packet);
      case 938:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetStickerPackList(packet);
         }

         return new FusionPktGetStickerPackListOld(packet);
      case 939:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktStickerPackList(packet);
         }

         return new FusionPktStickerPackListOld(packet);
      case 940:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetStickerPack(packet);
         }

         return new FusionPktGetStickerPackOld(packet);
      case 941:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktStickerPack(packet);
         }

         return new FusionPktStickerPackOld(packet);
      case 942:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktEndStickerPack(packet);
         }

         return new FusionPktEndStickerPackOld(packet);
      case 959:
         return new FusionPktGetUploadDataTicket(packet);
      case 960:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUploadAddressBookContacts(packet);
         }

         return new FusionPktUploadAddressBookContactsOld(packet);
      default:
         return packet;
      }
   }

   public static FusionRequest getSpecificRequest(FusionPacket packet) {
      switch(packet.getType()) {
      case 2:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktPing(packet);
         }

         return new FusionPktPingOld(packet);
      case 7:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetHelpText(packet);
         }

         return new FusionPktGetHelpTextOld(packet);
      case 9:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktServerQuestionReply(packet);
         }

         return new FusionPktServerQuestionReplyOld(packet);
      case 10:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktReport(packet);
         }

         return new FusionPktReportOld(packet);
      case 11:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktMidletProperty(packet);
         }

         return new FusionPktMidletPropertyOld(packet);
      case 13:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktHttpPoll(packet);
         }

         return new FusionPktHTTPPollOld(packet);
      case 17:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCaptchaResponse(packet);
         }

         return new FusionPktCaptchaResponseOld(packet);
      case 18:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetServerQuestion(packet);
         }

         return new FusionPktGetServerQuestionOld(packet);
      case 100:
         return new FusionPktNewRegistration(packet);
      case 101:
         return new FusionPktRegistration(packet);
      case 103:
         return new FusionPktRegistrationResponse(packet);
      case 200:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLogin(packet);
         }

         return new FusionPktLoginOld(packet);
      case 202:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLoginResponse(packet);
         }

         return new FusionPktLoginResponseOld(packet);
      case 204:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktActivateAccount(packet);
         }

         return new FusionPktActivateAccountOld(packet);
      case 205:
         return new FusionPktResendVerificationCode(packet);
      case 206:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktImLogin(packet);
         }

         return new FusionPktIMLoginOld(packet);
      case 209:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSlimLogin(packet);
         }

         return new FusionPktSlimLoginOld(packet);
      case 211:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCreateSession(packet);
         }

         return new FusionPktCreateSessionOld(packet);
      case 300:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLogout(packet);
         }

         return new FusionPktLogoutOld(packet);
      case 302:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktImLogout(packet);
         }

         return new FusionPktIMLogoutOld(packet);
      case 400:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetContacts(packet);
         }

         return new FusionPktGetContactsOld(packet);
      case 405:
         return new FusionPktAddContact(packet);
      case 406:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktRemoveContact(packet);
         }

         return new FusionPktRemoveContactOld(packet);
      case 407:
         return new FusionPktUpdateContact(packet);
      case 408:
         return new FusionPktAddGroup(packet);
      case 409:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktRemoveGroup(packet);
         }

         return new FusionPktRemoveGroupOld(packet);
      case 410:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUpdateGroup(packet);
         }

         return new FusionPktUpdateGroupOld(packet);
      case 411:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktMoveContact(packet);
         }

         return new FusionPktMoveContactOld(packet);
      case 413:
         return new FusionPktAcceptContactRequest(packet);
      case 414:
         return new FusionPktRejectContactRequest(packet);
      case 415:
         return new FusionPktGetPermissionList(packet);
      case 417:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetPermission(packet);
         }

         return new FusionPktSetPermissionOld(packet);
      case 419:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktHaveLatestContactList(packet);
         }

         return new FusionPktHaveLatestContactListOld(packet);
      case 425:
         return new FusionPktGetContactRequests(packet);
      case 500:
         return new FusionPktMessage(packet);
      case 501:
         return new FusionPktWAPPush(packet);
      case 504:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUploadFile(packet);
         }

         return new FusionPktUploadFileOld(packet);
      case 505:
         return new FusionPktMessageStatusEvent(packet);
      case 507:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLeavePrivateChat(packet);
         }

         return new FusionPktLeavePrivateChatOld(packet);
      case 550:
         return new FusionPktGetMessages(packet);
      case 551:
         return new FusionPktGetChats(packet);
      case 564:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetChatName(packet);
         }

         return new FusionPktSetChatNameOld(packet);
      case 565:
         return new FusionPktGetMessageStatusEvents(packet);
      case 600:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetPresence(packet);
         }

         return new FusionPktSetPresenceOld(packet);
      case 601:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetStatusMessage(packet);
         }

         return new FusionPktSetStatusMessageOld(packet);
      case 602:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetDisplayPicture(packet);
         }

         return new FusionPktSetDisplayPictureOld(packet);
      case 604:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktDeviceMode(packet);
         }

         return new FusionPktDeviceModeOld(packet);
      case 700:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetChatrooms(packet);
         }

         return new FusionPktGetChatRoomsOld(packet);
      case 703:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktJoinChatroom(packet);
         }

         return new FusionPktJoinChatRoomOld(packet);
      case 704:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLeaveChatroom(packet);
         }

         return new FusionPktLeaveChatRoomOld(packet);
      case 705:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCreateChatroom(packet);
         }

         return new FusionPktCreateChatRoomOld(packet);
      case 706:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktKickChatroomParticipant(packet);
         }

         return new FusionPktKickChatRoomParticipantOld(packet);
      case 707:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetChatroomParticipants(packet);
         }

         return new FusionPktGetChatRoomParticipantsOld(packet);
      case 709:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktMuteChatroomParticipant(packet);
         }

         return new FusionPktMuteChatRoomParticipantOld(packet);
      case 710:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUnmuteChatroomParticipant(packet);
         }

         return new FusionPktUnmuteChatRoomParticipantOld(packet);
      case 711:
         return new FusionPktAddFavoriteChatroom(packet);
      case 712:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktRemoveFavoriteChatroom(packet);
         }

         return new FusionPktRemoveFavouriteChatRoomOld(packet);
      case 713:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetChatroomCategories(packet);
         }

         return new FusionPktGetChatRoomCategoriesOld(packet);
      case 716:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetCategorizedChatrooms(packet);
         }

         return new FusionPktGetCategorizedChatRoomsOld(packet);
      case 751:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCreateGroupChat(packet);
         }

         return new FusionPktCreateGroupChatOld(packet);
      case 752:
         return new FusionPktGroupChatInvite(packet);
      case 753:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLeaveGroupChat(packet);
         }

         return new FusionPktLeaveGroupChatOld(packet);
      case 754:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetGroupChatParticipants(packet);
         }

         return new FusionPktGetGroupChatParticipantsOld(packet);
      case 800:
         return new FusionPktPhoneCall(packet);
      case 801:
         return new FusionPktWebCall(packet);
      case 803:
         return new FusionPktWebCallResponse(packet);
      case 805:
         return new FusionPktCompareCallRate(packet);
      case 807:
         return new FusionPktAnonymousCallResponse(packet);
      case 900:
         return new FusionPktInviteFriend(packet);
      case 901:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetAccountBalance(packet);
         }

         return new FusionPktGetAccountBalanceOld(packet);
      case 903:
         return new FusionPktRecharge(packet);
      case 904:
         return new FusionPktForgotPassword(packet);
      case 905:
         return new FusionPktGetUserProfile(packet);
      case 907:
         return new FusionPktUpdateUserProfile(packet);
      case 908:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktChangePassword(packet);
         }

         return new FusionPktChangePasswordOld(packet);
      case 909:
         return new FusionPktTransferCredit(packet);
      case 910:
         return new FusionPktGetURL(packet);
      case 913:
         return new FusionPktGetEmoticon(packet);
      case 921:
         return new FusionPktChangeUserEventSetting(packet);
      case 922:
         return new FusionPktOpenURL(packet);
      case 925:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLanguage(packet);
         }

         return new FusionPktLanguageOld(packet);
      case 926:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetImIcons(packet);
         }

         return new FusionPktGetIMIconsOld(packet);
      case 929:
         return new FusionPktGetDynamicMenuIcon(packet);
      case 931:
         return new FusionPktGetPreloginMarketingMsg(packet);
      case 935:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetGift(packet);
         }

         return new FusionPktGetGiftOld(packet);
      case 937:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetEmoticonHotkeys(packet);
         }

         return new FusionPktGetEmoticonHotkeysOld(packet);
      case 938:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetStickerPackList(packet);
         }

         return new FusionPktGetStickerPackListOld(packet);
      case 940:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetStickerPack(packet);
         }

         return new FusionPktGetStickerPackOld(packet);
      case 959:
         return new FusionPktGetUploadDataTicket(packet);
      case 960:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUploadAddressBookContacts(packet);
         }

         return new FusionPktUploadAddressBookContactsOld(packet);
      default:
         return null;
      }
   }

   public static FusionRequest readSpecificRequest(ByteBuffer readBuffer) throws Exception {
      short type = FusionPacket.getPacketType(readBuffer);
      Object request;
      switch(type) {
      case 2:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktPing(readBuffer);
         }

         request = new FusionPktPingOld();
         break;
      case 7:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetHelpText(readBuffer);
         }

         request = new FusionPktGetHelpTextOld();
         break;
      case 9:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktServerQuestionReply(readBuffer);
         }

         request = new FusionPktServerQuestionReplyOld();
         break;
      case 10:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktReport(readBuffer);
         }

         request = new FusionPktReportOld();
         break;
      case 11:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktMidletProperty(readBuffer);
         }

         request = new FusionPktMidletPropertyOld();
         break;
      case 13:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktHttpPoll(readBuffer);
         }

         request = new FusionPktHTTPPollOld();
         break;
      case 17:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCaptchaResponse(readBuffer);
         }

         request = new FusionPktCaptchaResponseOld();
         break;
      case 18:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetServerQuestion(readBuffer);
         }

         request = new FusionPktGetServerQuestionOld();
         break;
      case 100:
         request = new FusionPktNewRegistration();
         break;
      case 101:
         request = new FusionPktRegistration();
         break;
      case 103:
         request = new FusionPktRegistrationResponse();
         break;
      case 200:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLogin(readBuffer);
         }

         request = new FusionPktLoginOld();
         break;
      case 202:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLoginResponse(readBuffer);
         }

         request = new FusionPktLoginResponseOld();
         break;
      case 204:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktActivateAccount(readBuffer);
         }

         request = new FusionPktActivateAccountOld();
         break;
      case 205:
         request = new FusionPktResendVerificationCode();
         break;
      case 206:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktImLogin(readBuffer);
         }

         request = new FusionPktIMLoginOld();
         break;
      case 209:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSlimLogin(readBuffer);
         }

         request = new FusionPktSlimLoginOld();
         break;
      case 211:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCreateSession(readBuffer);
         }

         request = new FusionPktCreateSessionOld();
         break;
      case 300:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLogout(readBuffer);
         }

         request = new FusionPktLogoutOld();
         break;
      case 302:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktImLogout(readBuffer);
         }

         request = new FusionPktIMLogoutOld();
         break;
      case 400:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetContacts(readBuffer);
         }

         request = new FusionPktGetContactsOld();
         break;
      case 405:
         request = new FusionPktAddContact();
         break;
      case 406:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktRemoveContact(readBuffer);
         }

         request = new FusionPktRemoveContactOld();
         break;
      case 407:
         request = new FusionPktUpdateContact();
         break;
      case 408:
         return new FusionPktAddGroup(readBuffer);
      case 409:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktRemoveGroup(readBuffer);
         }

         request = new FusionPktRemoveGroupOld();
         break;
      case 410:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUpdateGroup(readBuffer);
         }

         request = new FusionPktUpdateGroupOld();
         break;
      case 411:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktMoveContact(readBuffer);
         }

         request = new FusionPktMoveContactOld();
         break;
      case 413:
         return new FusionPktAcceptContactRequest(readBuffer);
      case 414:
         request = new FusionPktRejectContactRequest();
         break;
      case 415:
         request = new FusionPktGetPermissionList();
         break;
      case 417:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetPermission(readBuffer);
         }

         request = new FusionPktSetPermissionOld();
         break;
      case 419:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktHaveLatestContactList(readBuffer);
         }

         request = new FusionPktHaveLatestContactListOld();
         break;
      case 425:
         request = new FusionPktGetContactRequests();
         break;
      case 500:
         request = new FusionPktMessage();
         break;
      case 501:
         request = new FusionPktWAPPush();
         break;
      case 504:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUploadFile(readBuffer);
         }

         request = new FusionPktUploadFileOld();
         break;
      case 505:
         request = new FusionPktMessageStatusEvent();
         break;
      case 507:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLeavePrivateChat(readBuffer);
         }

         request = new FusionPktLeavePrivateChatOld();
         break;
      case 550:
         request = new FusionPktGetMessages();
         break;
      case 551:
         request = new FusionPktGetChats();
         break;
      case 564:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetChatName(readBuffer);
         }

         request = new FusionPktSetChatNameOld();
         break;
      case 565:
         request = new FusionPktGetMessageStatusEvents();
         break;
      case 600:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetPresence(readBuffer);
         }

         request = new FusionPktSetPresenceOld();
         break;
      case 601:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetStatusMessage(readBuffer);
         }

         request = new FusionPktSetStatusMessageOld();
         break;
      case 602:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktSetDisplayPicture(readBuffer);
         }

         request = new FusionPktSetDisplayPictureOld();
         break;
      case 604:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktDeviceMode(readBuffer);
         }

         request = new FusionPktDeviceModeOld();
         break;
      case 700:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetChatrooms(readBuffer);
         }

         request = new FusionPktGetChatRoomsOld();
         break;
      case 703:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktJoinChatroom(readBuffer);
         }

         request = new FusionPktJoinChatRoomOld();
         break;
      case 704:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLeaveChatroom(readBuffer);
         }

         request = new FusionPktLeaveChatRoomOld();
         break;
      case 705:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCreateChatroom(readBuffer);
         }

         request = new FusionPktCreateChatRoomOld();
         break;
      case 706:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktKickChatroomParticipant(readBuffer);
         }

         request = new FusionPktKickChatRoomParticipantOld();
         break;
      case 707:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetChatroomParticipants(readBuffer);
         }

         request = new FusionPktGetChatRoomParticipantsOld();
         break;
      case 709:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktMuteChatroomParticipant(readBuffer);
         }

         request = new FusionPktMuteChatRoomParticipantOld();
         break;
      case 710:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUnmuteChatroomParticipant(readBuffer);
         }

         request = new FusionPktUnmuteChatRoomParticipantOld();
         break;
      case 711:
         return new FusionPktAddFavoriteChatroom(readBuffer);
      case 712:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktRemoveFavoriteChatroom(readBuffer);
         }

         request = new FusionPktRemoveFavouriteChatRoomOld();
         break;
      case 713:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetChatroomCategories(readBuffer);
         }

         request = new FusionPktGetChatRoomCategoriesOld();
         break;
      case 716:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetCategorizedChatrooms(readBuffer);
         }

         request = new FusionPktGetCategorizedChatRoomsOld();
         break;
      case 751:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktCreateGroupChat(readBuffer);
         }

         request = new FusionPktCreateGroupChatOld();
         break;
      case 752:
         request = new FusionPktGroupChatInvite();
         break;
      case 753:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLeaveGroupChat(readBuffer);
         }

         request = new FusionPktLeaveGroupChatOld();
         break;
      case 754:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetGroupChatParticipants(readBuffer);
         }

         request = new FusionPktGetGroupChatParticipantsOld();
         break;
      case 800:
         request = new FusionPktPhoneCall();
         break;
      case 801:
         request = new FusionPktWebCall();
         break;
      case 803:
         request = new FusionPktWebCallResponse();
         break;
      case 805:
         request = new FusionPktCompareCallRate();
         break;
      case 807:
         request = new FusionPktAnonymousCallResponse();
         break;
      case 900:
         request = new FusionPktInviteFriend();
         break;
      case 901:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetAccountBalance(readBuffer);
         }

         request = new FusionPktGetAccountBalanceOld();
         break;
      case 903:
         request = new FusionPktRecharge();
         break;
      case 904:
         request = new FusionPktForgotPassword();
         break;
      case 905:
         request = new FusionPktGetUserProfile();
         break;
      case 907:
         request = new FusionPktUpdateUserProfile();
         break;
      case 908:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktChangePassword(readBuffer);
         }

         request = new FusionPktChangePasswordOld();
         break;
      case 909:
         request = new FusionPktTransferCredit();
         break;
      case 910:
         request = new FusionPktGetURL();
         break;
      case 913:
         request = new FusionPktGetEmoticon();
         break;
      case 921:
         request = new FusionPktChangeUserEventSetting();
         break;
      case 922:
         request = new FusionPktOpenURL();
         break;
      case 925:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktLanguage(readBuffer);
         }

         request = new FusionPktLanguageOld();
         break;
      case 926:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetImIcons(readBuffer);
         }

         request = new FusionPktGetIMIconsOld();
         break;
      case 929:
         request = new FusionPktGetDynamicMenuIcon();
         break;
      case 931:
         request = new FusionPktGetPreloginMarketingMsg();
         break;
      case 935:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetGift(readBuffer);
         }

         request = new FusionPktGetGiftOld();
         break;
      case 937:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetEmoticonHotkeys(readBuffer);
         }

         request = new FusionPktGetEmoticonHotkeysOld();
         break;
      case 938:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetStickerPackList(readBuffer);
         }

         request = new FusionPktGetStickerPackListOld();
         break;
      case 940:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktGetStickerPack(readBuffer);
         }

         request = new FusionPktGetStickerPackOld();
         break;
      case 959:
         request = new FusionPktGetUploadDataTicket();
         break;
      case 960:
         if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week3UseAutogeneratedPacketsEnabled.getValue()) {
            return new FusionPktUploadAddressBookContacts(readBuffer);
         }

         request = new FusionPktUploadAddressBookContactsOld();
         break;
      default:
         return null;
      }

      ((FusionRequest)request).read(readBuffer);
      return (FusionRequest)request;
   }
}
