/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  org.apache.log4j.Logger
 */
package com.projectgoth.fusion.chatsync;

import com.projectgoth.fusion.chatsync.ChatDefinition;
import com.projectgoth.fusion.chatsync.ChatSyncStats;
import com.projectgoth.fusion.chatsync.ChatSyncStore;
import com.projectgoth.fusion.chatsync.UserMissingChats;
import com.projectgoth.fusion.common.ConfigUtils;
import com.projectgoth.fusion.common.LogFilter;
import com.projectgoth.fusion.common.SystemProperty;
import com.projectgoth.fusion.common.SystemPropertyEntities;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktChat;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktChatListVersion;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktChatListVersionOld;
import com.projectgoth.fusion.slice.ConnectionPrx;
import com.projectgoth.fusion.slice.FusionException;
import com.projectgoth.fusion.slice.SessionPrx;
import org.apache.log4j.Logger;

public class UserMissingChatsPusher
extends UserMissingChats {
    private static final LogFilter log = new LogFilter(Logger.getLogger((String)ConfigUtils.getLoggerName(UserMissingChatsPusher.class)), SystemPropertyEntities.ChatSyncSettings.LOG_EXCLUSION_FILTER);
    private final ConnectionPrx connection;
    private final short transactionId;
    private final String parentUsername;
    private long queueingStartTime;

    public UserMissingChatsPusher(int userID, ConnectionPrx connection, int chatListVersion, Integer limit, Byte chatType, short transactionId, String parentUsername) {
        super(userID, chatListVersion, limit, chatType, connection);
        this.connection = connection;
        this.transactionId = transactionId;
        this.parentUsername = parentUsername;
        this.queueingStartTime = System.currentTimeMillis();
    }

    /*
     * WARNING - Removed try catching itself - possible behaviour change.
     */
    public void retrieve(ChatSyncStore[] stores) throws FusionException {
        if (SystemProperty.getBool(SystemPropertyEntities.ChatSyncSettings.WALLCLOCK_TIME_STATS_ENABLED)) {
            ChatSyncStats.getInstance().addGetChatsAsyncQueueingWallclockTime(System.currentTimeMillis() - this.queueingStartTime);
        }
        long startWallclock = System.currentTimeMillis();
        try {
            super.retrieve(stores);
            if (this.missingChatDefs.size() != 0) {
                this.pushMissingChats();
            }
            Object var5_3 = null;
        }
        catch (Throwable throwable) {
            Object var5_4 = null;
            if (SystemProperty.getBool(SystemPropertyEntities.ChatSyncSettings.WALLCLOCK_TIME_STATS_ENABLED)) {
                ChatSyncStats.getInstance().addGetChatsAsyncWallclockTime(System.currentTimeMillis() - startWallclock);
            }
            throw throwable;
        }
        if (SystemProperty.getBool(SystemPropertyEntities.ChatSyncSettings.WALLCLOCK_TIME_STATS_ENABLED)) {
            ChatSyncStats.getInstance().addGetChatsAsyncWallclockTime(System.currentTimeMillis() - startWallclock);
        }
    }

    private void pushMissingChats() throws FusionException {
        SessionPrx session = this.connection.getSessionObject();
        if (log.isDebugEnabled()) {
            log.debug("pushMissingChats to session=" + session.getSessionID() + " with desired chatType=" + this.chatType);
        }
        if (log.isDebugEnabled()) {
            log.debug("pushMissingChats: no of chats to push=" + this.missingChatDefs.size());
        }
        if (this.missingChatDefs.size() > 0) {
            long chatListTimestamp = System.currentTimeMillis();
            for (ChatDefinition chatDef : this.missingChatDefs) {
                try {
                    if (log.isDebugEnabled()) {
                        log.debug("pushMissingChats: pushing chat id=" + chatDef.getChatID());
                    }
                    FusionPktChat chat = chatDef.toFusionPktChat(this.transactionId, this.currentChatList.getVersion(), chatListTimestamp, this.parentUsername);
                    if (log.isDebugEnabled()) {
                        log.debug("pushMissingChats: converted ChatDefinition to pkt=" + chat);
                    }
                    this.connection.putSerializedPacket(chat.toSerializedBytes());
                }
                catch (Exception e) {
                    log.error("Failed to send chat " + chatDef + " to userID=" + this.userID);
                }
            }
        }
        if (SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue().booleanValue()) {
            FusionPktChatListVersion finished = new FusionPktChatListVersion(this.transactionId);
            finished.setVersion(this.currentChatList.getVersion());
            this.connection.putSerializedPacket(finished.toSerializedBytes());
        } else {
            FusionPktChatListVersionOld finished = new FusionPktChatListVersionOld(this.transactionId);
            finished.setVersion(this.currentChatList.getVersion());
            this.connection.putSerializedPacket(finished.toSerializedBytes());
        }
        session.setChatListVersion(this.currentChatList.getVersion());
        this.setCurrentChatListOnUser(session);
    }

    private void setCurrentChatListOnUser(SessionPrx session) {
        try {
            session.setCurrentChatListGroupChatSubset(this.currentChatList.toIceObject());
        }
        catch (Exception e) {
            log.error("Call to setCurrentChatListGroupChatSubset failed for user=" + this.parentUsername + " e=" + e, e);
        }
    }

    public boolean canRetryReads() throws FusionException {
        return SystemProperty.getBool(SystemPropertyEntities.ChatSyncSettings.RETRY_GET_CHATS_ENABLED);
    }
}

