package com.projectgoth.fusion.jobscheduling;

public enum JobGroup {
   GROUP_NOTIFICATION,
   SUBSCRIPTION_MANAGEMENT,
   REPUTATION_SERVICE,
   REFERRAL_MANAGEMENT,
   LEADERBOARD_COMPUTATION,
   MERCHANT_TRAIL,
   VAS_COMPUTATION,
   MERCHANT_TAG_EXPIRY,
   LEADERBOARD_DAILY_COMPUTATION,
   LEADERBOARD_WEEKLY_COMPUTATION,
   AVATAR_CANDIDATE_POOLING,
   TOPMERCHANT_TAGGING,
   PAINT_WARS_WEEKLY_RAFFLES,
   MIGBO_RSSFEED_GENERATION,
   MIGBO_EMAIL_DAILY_DIGEST,
   MOL_ASYNCHRONOUS_UPDATE,
   MIMOPAY_ASYNCHRONOUS_UPDATE,
   PAYPAL_ASYNCHRONOUS_UPDATE,
   MIGBO_EMAIL_DAILY_DIGEST_TO_USERS_BEING_FOLLOWED,
   RECOMMENDATION_GENERATION;
}
