/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  javax.ejb.CreateException
 */
package com.projectgoth.fusion.gateway.packet;

import com.projectgoth.fusion.common.RMIExceptionHelper;
import com.projectgoth.fusion.common.SystemProperty;
import com.projectgoth.fusion.common.SystemPropertyEntities;
import com.projectgoth.fusion.data.ContactData;
import com.projectgoth.fusion.ejb.EJBHomeCache;
import com.projectgoth.fusion.ejb.FusionEJBException;
import com.projectgoth.fusion.fdl.packets.FusionPktDataAcceptContactRequest;
import com.projectgoth.fusion.gateway.ConnectionI;
import com.projectgoth.fusion.gateway.packet.FusionPktContact;
import com.projectgoth.fusion.gateway.packet.FusionPktContactOld;
import com.projectgoth.fusion.gateway.packet.FusionPktError;
import com.projectgoth.fusion.interfaces.Contact;
import com.projectgoth.fusion.interfaces.ContactHome;
import com.projectgoth.fusion.packet.FusionPacket;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.rmi.RemoteException;
import javax.ejb.CreateException;

public class FusionPktAcceptContactRequest
extends FusionPktDataAcceptContactRequest {
    public FusionPktAcceptContactRequest() {
    }

    public FusionPktAcceptContactRequest(ByteBuffer byteBuffer) throws IOException {
        super(byteBuffer);
    }

    public FusionPktAcceptContactRequest(FusionPacket packet) {
        super(packet);
    }

    protected FusionPacket[] processRequest(ConnectionI connection) {
        try {
            String contactUsername = this.getContactUsername();
            if (contactUsername == null) {
                return new FusionPktError(this.transactionId, FusionPktError.Code.UNDEFINED, "Contact username not set").toArray();
            }
            Boolean shareMobilePhone = this.getShareMobilePhone();
            Contact contactEJB = (Contact)EJBHomeCache.getObject("ejb/Contact", ContactHome.class);
            ContactData contactData = new ContactData();
            contactData.username = connection.getUsername();
            contactData.fusionUsername = contactUsername;
            contactData.contactGroupId = this.getGroupId();
            contactData.displayOnPhone = true;
            if (shareMobilePhone != null) {
                contactData.shareMobilePhone = shareMobilePhone;
            }
            if (SystemProperty.getBool(SystemPropertyEntities.Contacts.FOLLOW_ON_ADD_CONTACT_ENABLED)) {
                boolean followOnMiniblog = SystemProperty.getBool(SystemPropertyEntities.Contacts.MIGBO_INTEGRATION_ENABLED);
                contactData = contactEJB.addFusionUserAsContact(connection.getUserID(), contactData, followOnMiniblog);
            } else {
                contactData = contactEJB.acceptContactRequest(connection.getUserID(), contactData, false);
            }
            if (SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue().booleanValue()) {
                return new FusionPktContact(this.transactionId, contactData, connection).toArray();
            }
            return new FusionPktContactOld(this.transactionId, contactData, connection).toArray();
        }
        catch (CreateException e) {
            return new FusionPktError(this.transactionId, FusionPktError.Code.UNDEFINED, "Failed to create ContactEJB").toArray();
        }
        catch (RemoteException e) {
            return new FusionPktError(this.transactionId, FusionPktError.Code.UNDEFINED, "Failed to accept user - " + RMIExceptionHelper.getRootMessage(e)).toArray();
        }
        catch (FusionEJBException e) {
            return new FusionPktError(this.transactionId, FusionPktError.Code.UNDEFINED, "Failed to accept user - " + e.getMessage()).toArray();
        }
    }
}

