package com.projectgoth.fusion.fdl.enums;

import java.util.HashMap;

public enum PacketType {
   ERROR((short)0),
   OK((short)1),
   PING((short)2),
   PONG((short)3),
   ALERT((short)5),
   HELP_TEXT((short)6),
   GET_HELP_TEXT((short)7),
   SERVER_QUESTION((short)8),
   SERVER_QUESTION_REPLY((short)9),
   REPORT((short)10),
   MIDLET_PROPERTY((short)11),
   GET_MIDLET_PROPERTY((short)12),
   HTTP_POLL((short)13),
   NOTIFICATION((short)14),
   RESERVED((short)15),
   CAPTCHA((short)16),
   CAPTCHA_RESPONSE((short)17),
   GET_SERVER_QUESTION((short)18),
   NEW_REGISTRATION((short)100),
   REGISTRATION((short)101),
   REGISTRATION_CHALLENGE((short)102),
   REGISTRATION_RESPONSE((short)103),
   REGISTRATION_ERROR((short)104),
   LOGIN((short)200),
   LOGIN_CHALLENGE((short)201),
   LOGIN_RESPONSE((short)202),
   LOGIN_OK((short)203),
   ACTIVATE_ACCOUNT((short)204),
   RESEND_VERIFICATION_CODE((short)205),
   IM_LOGIN((short)206),
   IM_SESSION_STATUS((short)207),
   IM_AVAILABLE((short)208),
   SLIM_LOGIN((short)209),
   SLIM_LOGIN_OK((short)210),
   CREATE_SESSION((short)211),
   SLIM_LOGIN_CHALLENGE((short)212),
   LOGOUT((short)300),
   SESSION_TERMINATED((short)301),
   IM_LOGOUT((short)302),
   GET_CONTACTS((short)400),
   GROUP((short)401),
   CONTACT((short)402),
   GET_CONTACTS_COMPLETE((short)403),
   PRESENCE((short)404),
   ADD_CONTACT((short)405),
   REMOVE_CONTACT((short)406),
   UPDATE_CONTACT((short)407),
   ADD_GROUP((short)408),
   REMOVE_GROUP((short)409),
   UPDATE_GROUP((short)410),
   MOVE_CONTACT((short)411),
   CONTACT_REQUEST((short)412),
   ACCEPT_CONTACT_REQUEST((short)413),
   REJECT_CONTACT_REQUEST((short)414),
   GET_PERMISSION_LIST((short)415),
   PERMISSION_LIST((short)416),
   SET_PERMISSION((short)417),
   VOICE_CAPABILITY((short)418),
   HAVE_LATEST_CONTACT_LIST((short)419),
   CONTACT_LIST_VERSION((short)420),
   STATUS_MESSAGE((short)421),
   USER_EVENT((short)422),
   DISPLAY_PICTURE((short)423),
   GET_USER_INIT_DETAILS((short)424),
   GET_CONTACT_REQUESTS((short)425),
   MESSAGE((short)500),
   WAP_PUSH((short)501),
   FILE_RECEIVED((short)502),
   MAIL_INFO((short)503),
   UPLOAD_FILE((short)504),
   MESSAGE_STATUS_EVENT((short)505),
   MESSAGE_STATUS_EVENTS((short)506),
   LEAVE_PRIVATE_CHAT((short)507),
   GET_MESSAGES((short)550),
   GET_CHATS((short)551),
   HAVE_LATEST_CHAT_LIST((short)552),
   CHAT((short)560),
   CHAT_LIST_VERSION((short)561),
   END_MESSAGES((short)562),
   LATEST_MESSAGES_DIGEST((short)563),
   SET_CHAT_NAME((short)564),
   GET_MESSAGE_STATUS_EVENTS((short)565),
   SET_PRESENCE((short)600),
   SET_STATUS_MESSAGE((short)601),
   SET_DISPLAY_PICTURE((short)602),
   AVATAR((short)603),
   DEVICE_MODE((short)604),
   GET_CHATROOMS((short)700),
   CHATROOM((short)701),
   GET_CHATROOMS_COMPLETE((short)702),
   JOIN_CHATROOM((short)703),
   LEAVE_CHATROOM((short)704),
   CREATE_CHATROOM((short)705),
   KICK_CHATROOM_PARTICIPANT((short)706),
   GET_CHATROOM_PARTICIPANTS((short)707),
   CHATROOM_PARTICIPANTS((short)708),
   MUTE_CHATROOM_PARTICIPANT((short)709),
   UNMUTE_CHATROOM_PARTICIPANT((short)710),
   ADD_FAVORITE_CHATROOM((short)711),
   REMOVE_FAVORITE_CHATROOM((short)712),
   GET_CHATROOM_CATEGORIES((short)713),
   CHATROOM_CATEGORY((short)714),
   GET_CHATROOM_CATEGORIES_COMPLETE((short)715),
   GET_CATEGORIZED_CHATROOMS((short)716),
   GET_CATEGORIZED_CHATROOMS_COMPLETE((short)717),
   CHATROOM_NOTIFICATION((short)718),
   CHATROOM_THEME((short)719),
   CHATROOM_USER_STATUS((short)720),
   GROUP_CHAT((short)750),
   CREATE_GROUP_CHAT((short)751),
   GROUP_CHAT_INVITE((short)752),
   LEAVE_GROUP_CHAT((short)753),
   GET_GROUP_CHAT_PARTICIPANTS((short)754),
   GROUP_CHAT_PARTICIPANTS((short)755),
   GROUP_CHAT_USER_STATUS((short)756),
   PHONE_CALL((short)800),
   WEBCALL((short)801),
   WEBCALL_NOTIFICATION((short)802),
   WEBCALL_RESPONSE((short)803),
   DIAL((short)804),
   COMPARE_CALL_RATE((short)805),
   ANONYMOUS_CALL_NOTIFICATION((short)806),
   ANONYMOUS_CALL_RESPONSE((short)807),
   INVITE_FRIEND((short)900),
   GET_ACCOUNT_BALANCE((short)901),
   ACCOUNT_BALANCE((short)902),
   RECHARGE((short)903),
   FORGOT_PASSWORD((short)904),
   GET_USER_PROFILE((short)905),
   USER_PROFILE((short)906),
   UPDATE_USER_PROFILE((short)907),
   CHANGE_PASSWORD((short)908),
   TRANSFER_CREDIT((short)909),
   GET_URL((short)910),
   DYNAMIC_MENU((short)911),
   WALLPAPER((short)912),
   GET_EMOTICON((short)913),
   EMOTICON((short)914),
   CLEAR_EMOTICON_CACHE((short)915),
   EMOTICON_HOTKEYS((short)916),
   MIDLET_TAB((short)918),
   MIDLET_ACTION((short)920),
   CHANGE_USER_EVENT_SETTING((short)921),
   OPEN_URL((short)922),
   OPEN_URL_RESPONSE((short)923),
   TEXT_COLOR((short)924),
   LANGUAGE((short)925),
   GET_IM_ICONS((short)926),
   IM_ICONS((short)927),
   GET_EMOTICONS_COMPLETE((short)928),
   GET_DYNAMIC_MENU_ICON((short)929),
   DYNAMIC_MENU_ICON((short)930),
   GET_PRELOGIN_MARKETING_MSG((short)931),
   PRELOGIN_MARKETING_MSG((short)932),
   APPLICATION_MENU((short)933),
   APPLICATION_MENU_COMPLETE((short)934),
   GET_GIFT((short)935),
   GIFT_HOTKEYS((short)936),
   GET_EMOTICON_HOTKEYS((short)937),
   GET_STICKER_PACK_LIST((short)938),
   STICKER_PACK_LIST((short)939),
   GET_STICKER_PACK((short)940),
   STICKER_PACK((short)941),
   END_STICKER_PACK((short)942),
   GET_UPLOAD_DATA_TICKET((short)959),
   UPLOAD_ADDRESS_BOOK_CONTACTS((short)960);

   private short value;
   private static final HashMap<Short, PacketType> LOOKUP = new HashMap();

   private PacketType(short value) {
      this.value = value;
   }

   public short value() {
      return this.value;
   }

   public static PacketType fromValue(int value) {
      return (PacketType)LOOKUP.get((short)value);
   }

   public static PacketType fromValue(Short value) {
      return (PacketType)LOOKUP.get(value);
   }

   static {
      PacketType[] arr$ = values();
      int len$ = arr$.length;

      for(int i$ = 0; i$ < len$; ++i$) {
         PacketType packetType = arr$[i$];
         LOOKUP.put(packetType.value, packetType);
      }

   }
}
