CREATE DATABASE migwars;

GRANT SELECT, INSERT, UPDATE, DELETE ON migwars.* TO migwars@'%' IDENTIFIED BY 'migwars';

CREATE TABLE IF NOT EXISTS player
( 
	ID INT NOT NULL AUTO_INCREMENT,
	UserID INT UNSIGNED NOT NULL,
	Username VARCHAR(128) NOT NULL,
	Class TINYINT UNSIGNED NOT NULL,
	Experience INT NOT NULL DEFAULT '0',
	Level SMALLINT UNSIGNED NOT NULL DEFAULT '1',
	Attack SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	Defense SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	Energy SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	MaxEnergy SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	NextEnergyUpdate DATETIME NULL,
	Health SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	MaxHealth SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	NextHealthUpdate DATETIME NULL,
	Stamina SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	MaxStamina SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	NextStaminaUpdate DATETIME NULL,
	SkillPoints SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	Balance INT NOT NULL DEFAULT '0',
	BankBalance INT NOT NULL DEFAULT '0',
	NextBalanceUpdate DATETIME NULL,
	GangSize INT NOT NULL DEFAULT '0',
	FightsWon INT NOT NULL DEFAULT '0',
	FightsLost INT NOT NULL DEFAULT '0',
	TutorialStep TINYINT UNSIGNED NOT NULL DEFAULT '0',
	TutorialCompleted TINYINT UNSIGNED NOT NULL DEFAULT '0',
	LocationID TINYINT UNSIGNED NOT NULL DEFAULT '0',
	JournalLastViewed DATETIME NULL,
	LastPlayedDate DATE NULL,
	Status TINYINT UNSIGNED NOT NULL DEFAULT '1',
	PRIMARY KEY (ID),
	UNIQUE INDEX (UserID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS location
( 
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(100) NOT NULL,
	MinLevel SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	Image VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS mission
( 
	ID INT NOT NULL AUTO_INCREMENT,
	LocationID INT NOT NULL,
	Name VARCHAR(100) NOT NULL,
	EnergyCost SMALLINT UNSIGNED NOT NULL,
	MinLevel SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	MinGangSize INT NOT NULL DEFAULT '0',
	NumToMaster SMALLINT UNSIGNED NOT NULL,
	ExperienceReward INT NOT NULL,
	MinCashReward INT NOT NULL DEFAULT '0',
	MaxCashReward INT NOT NULL DEFAULT '0',
	MasteredExperienceReward INT NOT NULL,
	MasteredCashReward INT NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_mission_locationid FOREIGN KEY (LocationID) REFERENCES location (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS missioncompleted
(
	PlayerID INT NOT NULL,
	MissionID INT NOT NULL,
	NumCompleted INT NOT NULL,
	PRIMARY KEY (PlayerID, MissionID),
	CONSTRAINT FK_missioncompleted_playerid FOREIGN KEY (PlayerID) REFERENCES player (ID),
	CONSTRAINT FK_missioncompleted_missionid FOREIGN KEY (MissionID) REFERENCES mission (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS item
(
	ID INT NOT NULL AUTO_INCREMENT,
	Type TINYINT UNSIGNED NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Description VARCHAR(200) NOT NULL,
	Image VARCHAR(100) NOT NULL,
	Attack SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	Defense SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	CanBePurchased TINYINT UNSIGNED NOT NULL DEFAULT '0',
	Cost INT NULL,
	MigCreditCost DOUBLE(12,2) NULL,
	MigCreditCurrency VARCHAR(6) NULL,
	CostMultiplier INT NOT NULL DEFAULT '0',
	SellPrice INT NULL,
	Upkeep INT NOT NULL DEFAULT '0',
	Income INT NOT NULL DEFAULT '0',
	MinLevel SMALLINT UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS missionrequireditem
(
	MissionID INT NOT NULL,
	ItemID INT NOT NULL,
	NumRequired SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (MissionID, ItemID),
	CONSTRAINT FK_missionrequireditem_missionid FOREIGN KEY (MissionID) REFERENCES mission (ID),
	CONSTRAINT FK_missionrequireditem_itemid FOREIGN KEY (ItemID) REFERENCES item (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS missionitemloot
(
	MissionID INT NOT NULL,
	ItemID INT NOT NULL,
	LootPercentageChance TINYINT UNSIGNED NOT NULL,
	MasteredRequired TINYINT UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (MissionID, ItemID),
	CONSTRAINT FK_missionitemloot_missionid FOREIGN KEY (MissionID) REFERENCES mission (ID),
	CONSTRAINT FK_missionitemloot_itemid FOREIGN KEY (ItemID) REFERENCES item (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS itemowned
(
	PlayerID INT NOT NULL,
	ItemID INT NOT NULL,
	NumOwned INT NOT NULL,
	PRIMARY KEY (PlayerID, ItemID),
	CONSTRAINT FK_itemowned_playerid FOREIGN KEY (PlayerID) REFERENCES player (ID),
	CONSTRAINT FK_itemowned_itemid FOREIGN KEY (ItemID) REFERENCES item (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS gang
(
	PlayerID INT NOT NULL,
	MemberPlayerID INT NOT NULL,
	DateCreated DATETIME NOT NULL,
	PRIMARY KEY (PlayerID, MemberPlayerID),
	CONSTRAINT FK_gang_playerid FOREIGN KEY (PlayerID) REFERENCES player (ID),
	CONSTRAINT FK_gang_memberplayerid FOREIGN KEY (MemberPlayerID) REFERENCES player (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS ganginvitation
(
	PlayerID INT NOT NULL,
	InvitedPlayerID INT NOT NULL,
	DateCreated DATETIME NOT NULL,
	PRIMARY KEY (PlayerID, InvitedPlayerID),
	CONSTRAINT FK_ganginvitation_playerid FOREIGN KEY (PlayerID) REFERENCES player (ID),
	CONSTRAINT FK_ganginvitation_invitedplayerid FOREIGN KEY (InvitedPlayerID) REFERENCES player (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS hitlist
(
	ID INT NOT NULL AUTO_INCREMENT,
	PlayerID INT NOT NULL,
	HitPlayerID INT NOT NULL,
	MigCreditCost DOUBLE(12,2) NULL,
	MigCreditFundedCost DOUBLE(12,2) NULL,
	MigCreditHitAmount DOUBLE(12,2) NULL,
	MigCreditHitFundedAmount DOUBLE(12,2) NULL,
	MigCreditLotteryAmount DOUBLE(12,2) NULL,
	MigCreditLotteryFundedAmount DOUBLE(12,2) NULL,
	MigCreditCurrency VARCHAR(6) NULL,
	MigCreditExchangeRate DOUBLE(15,4) NULL,
	DateCreated DATETIME NOT NULL,
	Completed TINYINT UNSIGNED NOT NULL DEFAULT '0',
	CompletedDate DATETIME NULL,
	CompletedByPlayerID INT NULL,
	LotteryID INT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_hitlist_playerid FOREIGN KEY (PlayerID) REFERENCES player (ID),
	CONSTRAINT FK_hitlist_hitplayerid FOREIGN KEY (HitPlayerID) REFERENCES player (ID),
	CONSTRAINT FK_hitlist_completedbyplayerid FOREIGN KEY (CompletedByPlayerID) REFERENCES player (ID),
	CONSTRAINT FK_hitlist_lotteryid FOREIGN KEY (LotteryID) REFERENCES lottery (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS lottery
(
	ID INT NOT NULL AUTO_INCREMENT,
	WinnerPlayerID INT NULL,
	MigCreditAmount DOUBLE(12,2) NULL,
	MigCreditFundedAmount DOUBLE(12,2) NULL,
	MigCreditCurrency VARCHAR(6) NULL,
	MigCreditExchangeRate DOUBLE(15,4) NULL,
	DateCreated DATETIME NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_lottery_winnerplayerid FOREIGN KEY (WinnerPlayerID) REFERENCES player (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS fight
(
	ID INT NOT NULL AUTO_INCREMENT,
	AttackerPlayerID INT NOT NULL,
	DefenderPlayerID INT NOT NULL,
	WinnerPlayerID INT NOT NULL,
	LoserPlayerID INT NOT NULL,
	AttackerHealthLost SMALLINT UNSIGNED NOT NULL,
	DefenderHealthLost SMALLINT UNSIGNED NOT NULL,
	ExperienceGained INT NOT NULL,
	MoneyTaken INT NOT NULL,
	LoserDied TINYINT UNSIGNED NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_fight_attackerplayerid FOREIGN KEY (AttackerPlayerID) REFERENCES player (ID),
	CONSTRAINT FK_fight_defenderplayerid FOREIGN KEY (DefenderPlayerID) REFERENCES player (ID),
	CONSTRAINT FK_fight_winnerplayerid FOREIGN KEY (WinnerPlayerID) REFERENCES player (ID),
	CONSTRAINT FK_fight_loserplayerid FOREIGN KEY (LoserPlayerID) REFERENCES player (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS mercenary
(
	MigCreditCost DOUBLE(12,2) NULL,
	MigCreditCurrency VARCHAR(6) NULL
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS mercenaryhired
(
	PlayerID INT NOT NULL,
	NumHired INT NOT NULL,
	PRIMARY KEY (PlayerID),
	CONSTRAINT FK_mercenaryhired_playerid FOREIGN KEY (PlayerID) REFERENCES player (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;

CREATE TABLE IF NOT EXISTS journal
(
	ID INT NOT NULL AUTO_INCREMENT,
	PlayerID INT NOT NULL,
	OtherPlayerID INT NULL,
	DateCreated DATETIME NOT NULL,
	Type TINYINT UNSIGNED NOT NULL,
	Amount INT NULL,
	Description VARCHAR(500) NULL,
	PRIMARY KEY (ID),
	INDEX (PlayerID, DateCreated),
	CONSTRAINT FK_journal_playerid FOREIGN KEY (PlayerID) REFERENCES player (ID),
	CONSTRAINT FK_journal_otherplayerid FOREIGN KEY (OtherPlayerID) REFERENCES player (ID)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;
