-- Insert the pack mapping
insert into `fusion`.`emoticonpack` (Type, Name, Price, ForSale, Status) values (2, 'Paint Wars Pack', 0.0, 0, 1);


-- Insert the emoticons
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-cleanemoticon', 12, 12, '/usr/fusion/emoticons/paintwars/Clean_Emo_12.gif', '/usr/fusion/emoticons/paintwars/Clean_Emo_12.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-cleanemoticon', 16, 16, '/usr/fusion/emoticons/paintwars/Clean_Emo_16.gif', '/usr/fusion/emoticons/paintwars/Clean_Emo_16.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-cleanemoticon', 24, 24, '/usr/fusion/emoticons/paintwars/Clean_Emo_24.gif', '/usr/fusion/emoticons/paintwars/Clean_Emo_24.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-cleanemoticon', 32, 32, '/usr/fusion/emoticons/paintwars/Clean_Emo_32.gif', '/usr/fusion/emoticons/paintwars/Clean_Emo_32.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-cleanemoticon', 48, 48, '/usr/fusion/emoticons/paintwars/Clean_Emo_48.gif', '/usr/fusion/emoticons/paintwars/Clean_Emo_48.png');

insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-doubletrouble', 12, 12, '/usr/fusion/emoticons/paintwars/Double_Trouble_12.gif', '/usr/fusion/emoticons/paintwars/Double_Trouble_12.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-doubletrouble', 16, 16, '/usr/fusion/emoticons/paintwars/Double_Trouble_16.gif', '/usr/fusion/emoticons/paintwars/Double_Trouble_16.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-doubletrouble', 24, 24, '/usr/fusion/emoticons/paintwars/Double_Trouble_24.gif', '/usr/fusion/emoticons/paintwars/Double_Trouble_24.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-doubletrouble', 32, 32, '/usr/fusion/emoticons/paintwars/Double_Trouble_32.gif', '/usr/fusion/emoticons/paintwars/Double_Trouble_32.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-doubletrouble', 48, 48, '/usr/fusion/emoticons/paintwars/Double_Trouble_48.gif', '/usr/fusion/emoticons/paintwars/Double_Trouble_48.png');

insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-paintemoticon', 12, 12, '/usr/fusion/emoticons/paintwars/Paint_Emo_12.gif', '/usr/fusion/emoticons/paintwars/Paint_Emo_12.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-paintemoticon', 16, 16, '/usr/fusion/emoticons/paintwars/Paint_Emo_16.gif', '/usr/fusion/emoticons/paintwars/Paint_Emo_16.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-paintemoticon', 24, 24, '/usr/fusion/emoticons/paintwars/Paint_Emo_24.gif', '/usr/fusion/emoticons/paintwars/Paint_Emo_24.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-paintemoticon', 32, 32, '/usr/fusion/emoticons/paintwars/Paint_Emo_32.gif', '/usr/fusion/emoticons/paintwars/Paint_Emo_32.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-paintemoticon', 48, 48, '/usr/fusion/emoticons/paintwars/Paint_Emo_48.gif', '/usr/fusion/emoticons/paintwars/Paint_Emo_48.png');

insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-paintproof', 12, 12, '/usr/fusion/emoticons/paintwars/Paint_Proof_12.gif', '/usr/fusion/emoticons/paintwars/Paint_Proof_12.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-paintproof', 16, 16, '/usr/fusion/emoticons/paintwars/Paint_Proof_16.gif', '/usr/fusion/emoticons/paintwars/Paint_Proof_16.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-paintproof', 24, 24, '/usr/fusion/emoticons/paintwars/Paint_Proof_24.gif', '/usr/fusion/emoticons/paintwars/Paint_Proof_24.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-paintproof', 32, 32, '/usr/fusion/emoticons/paintwars/Paint_Proof_32.gif', '/usr/fusion/emoticons/paintwars/Paint_Proof_32.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-paintproof', 48, 48, '/usr/fusion/emoticons/paintwars/Paint_Proof_48.gif', '/usr/fusion/emoticons/paintwars/Paint_Proof_48.png');

insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-stealth', 12, 12, '/usr/fusion/emoticons/paintwars/Stealth_12.gif', '/usr/fusion/emoticons/paintwars/Stealth_12.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-stealth', 16, 16, '/usr/fusion/emoticons/paintwars/Stealth_16.gif', '/usr/fusion/emoticons/paintwars/Stealth_16.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-stealth', 24, 24, '/usr/fusion/emoticons/paintwars/Stealth_24.gif', '/usr/fusion/emoticons/paintwars/Stealth_24.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-stealth', 32, 32, '/usr/fusion/emoticons/paintwars/Stealth_32.gif', '/usr/fusion/emoticons/paintwars/Stealth_32.png');
insert into `fusion`.`emoticon` (EmoticonPackID, Type, Alias, Width, Height, Location, LocationPNG) values ((select id from `fusion`.`emoticonpack` where name='Paint Wars Pack'), 1, 'paintwars-stealth', 48, 48, '/usr/fusion/emoticons/paintwars/Stealth_48.gif', '/usr/fusion/emoticons/paintwars/Stealth_48.png');


-- Insert the hot key mapping
insert into `fusion`.`emoticonhotkey` (emoticonid, type, hotkey) select id, 1,'(paintwars-cleanemoticon)' from `fusion`.`emoticon` where alias='paintwars-cleanemoticon';
insert into `fusion`.`emoticonhotkey` (emoticonid, type, hotkey) select id, 1,'(paintwars-doubletrouble)' from `fusion`.`emoticon` where alias='paintwars-doubletrouble';
insert into `fusion`.`emoticonhotkey` (emoticonid, type, hotkey) select id, 1,'(paintwars-paintemoticon)' from `fusion`.`emoticon` where alias='paintwars-paintemoticon';
insert into `fusion`.`emoticonhotkey` (emoticonid, type, hotkey) select id, 1,'(paintwars-paintproof)' from `fusion`.`emoticon` where alias='paintwars-paintproof';
insert into `fusion`.`emoticonhotkey` (emoticonid, type, hotkey) select id, 1,'(paintwars-stealth)' from `fusion`.`emoticon` where alias='paintwars-stealth';

