# pool list
poolNames=

# DEFAULT SETTINGS (optional but good)
common.weights=1
common.initConn=1
common.minConn=1
common.maxConn=10
common.maxIdle=1000
common.maintSleep=30
common.nagle=false
common.socketTO=3000
common.socketConnectTO=0

# POOL SERVERS
contactList.servers=127.0.0.1:11211
broadcastList.servers=127.0.0.1:11211
profiles.servers=127.0.0.1:11211
userDisplayPictureAndStatus.servers=127.0.0.1:11211
captcha.servers=127.0.0.1:11211
common.servers=127.0.0.1:11211
rateLimit.servers=127.0.0.1:11211
bclPersisted.servers=127.0.0.1:11211
surgeMail.servers=127.0.0.1:11211
recentChatRooms.servers=127.0.0.1:11211
chatRoomSearch.servers=127.0.0.1:11211
authenticationService.servers=127.0.0.1:11211

# AUTH SERVICE CACHE EXTRA SETTINGS
authenticationService.weights=1
authenticationService.initConn=1
authenticationService.minConn=1
authenticationService.maxConn=10
authenticationService.maxIdle=1000
authenticationService.maintSleep=30
authenticationService.nagle=false
authenticationService.socketTO=3000
authenticationService.socketConnectTO=0
