<?php
require_once "PHPUnit/Extensions/Database/TestCase.php";
fast_require('AvatarDAO', get_dao_directory() . '/avatar_dao.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-16 at 16:38:48.
 */
class AvatarDAOTest extends PHPUnit_Extensions_Database_TestCase
{
    /**
     * @var AvatarDAO
     */
    protected $object;

	/**
     * @return PHPUnit_Extensions_Database_DB_IDatabaseConnection
     */
    public function getConnection()
    {
		$pdo = new PDO($GLOBALS['L_DB_DSN'], $GLOBALS['L_DB_USER'], $GLOBALS['L_DB_PWD']);
		$pdo->exec("set foreign_key_checks = 0;");
		return $this->createDefaultDBConnection($pdo, $GLOBALS['L_DB_NAME']);
    }

	/**
     * @return PHPUnit_Extensions_Database_DataSet_IDataSet
     */
    public function getDataSet()
    {
		global $test_base_dir;
		return $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/frame252.xml');
		$ds1 = $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/system.xml');
		$ds2 = $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/avatarbody.xml');
		$ds3 = $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/bonusprogram.xml');
		$ds4 = $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/currency.xml');
		$ds5 = $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/country.xml');
		$ds6 = $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/reputationscoretolevel.xml');
		$ds7 = $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/frame252.xml');
		$compositeDs = new PHPUnit_Extensions_Database_DataSet_CompositeDataSet(array($ds1, $ds2, $ds3, $ds4, $ds5, $ds6, $ds7));
        return $compositeDs;
    }

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		parent::setUp();
		Memcached::get_instance()->flush();
        $this->object = new AvatarDAO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
		$this->getConnection()->getConnection()->exec("set foreign_key_checks = 1;");;
		parent::tearDown();
    }

	/**
     * @covers AvatarDAO::get_avatar_bodies
	 * @group FRAME-252
     */
    public function testGet_avatar_bodies()
    {
        $result = $this->object->get_avatar_bodies();
		$this->assertNotEmpty($result, "Array not empty");
		$this->assertEquals(8, count($result["bodies"]), "All bodies");

        $result = $this->object->get_avatar_bodies("f");
		$this->assertEquals(4, count($result["bodies"]), "Female bodies");

		$result = $this->object->get_avatar_bodies("m");
		$this->assertEquals(4, count($result["bodies"]), "Male bodies");
    }

	/**
     * @covers AvatarDAO::rate_avatar
     * @group FRAME-252
     */
    public function testRate_avatar()
    {
		$session_username = "lesterchan"; // 2160
		$avataruser_id = 2160; // joker1
		$rating1 = 5;
        $result = $this->object->rate_avatar($session_username, $avataruser_id, $rating1);
		$this->assertNotEmpty($result);
		$this->assertEquals(1, $result['numratings'], "1 numrating after 1st vote");

		$session_username = "joker2"; // 7386
		$rating2 = 4;
        $result = $this->object->rate_avatar($session_username, $avataruser_id, $rating2);
		$this->assertNotEmpty($result);
		$this->assertEquals(2, $result['numratings'], "2 numrating after 2nd vote");
		$this->assertEquals((($rating1 + $rating2) / 2), $result['average'], "Average is right");
		$this->assertEquals(($rating1 + $rating2), $result['total'], "Total is right");
    }

    /**
     * @covers AvatarDAO::get_avatar_wall
     */
    public function testGet_avatar_wall()
    {
		try
		{
			$this->object->get_avatar_wall('cherrymoo', 'lesterchan', 0);
			$this->fail("Shouldn't be viewable");
		}
		catch (PHPUnit_Framework_AssertionFailedError $ex)
		{
			throw $ex;
		}
		catch (Exception $ex)
		{
			$this->assertTrue(true);
		}

		$result = $this->object->get_avatar_wall('cherrymoo', 'joker2', 0);
		$this->assertNotEmpty($result);
		$this->assertArrayHasKey('posts', $result);
		$this->assertArrayHasKey('total_count', $result);
		$this->assertEmpty($result['posts']);

		$result = $this->object->get_avatar_wall('joker2', 'cherrymoo', 0);
		$this->assertNotEmpty($result);
		$this->assertArrayHasKey('posts', $result);
		$this->assertArrayHasKey('total_count', $result);
		$this->assertNotEmpty($result['posts']);

		$num_posts = count($result['posts']);
		$row = $result['posts'][0];
		$older_than_id = $row->id;

		$result = $this->object->get_avatar_wall('joker2', 'cherrymoo', 0, 10, $older_than_id);
		$this->assertNotEmpty($result);
		$this->assertArrayHasKey('posts', $result);
		$this->assertArrayHasKey('total_count', $result);
		$this->assertNotEmpty($result['posts']);
		$this->assertEquals($num_posts - 1, count($result['posts']));
    }

    /**
     * @covers AvatarDAO::get_avatar_wall_post_likes
     */
    public function testGet_avatar_wall_post_likes()
    {
		$avatar_wall_post_id = 1;
        $result = $this->object->get_avatar_wall_post_likes($avatar_wall_post_id);
		$this->assertNotEmpty($result);
		$this->assertEquals(0, $result['numlikes']);

		$avatar_wall_post_id = 2;
        $result = $this->object->get_avatar_wall_post_likes($avatar_wall_post_id);
		$this->assertNotEmpty($result);
		$this->assertEquals(1, $result['numlikes']);
    }

    /**
     * @covers AvatarDAO::like_avatar_wall_post
     */
    public function testLike_avatar_wall_post()
    {
		$session_username = "cherrymoo"; // 2160
		$username = 'joker2';
		$avatar_wall_post_id = 1;

        $result = $this->object->get_avatar_wall_post_likes($avatar_wall_post_id);
		$this->assertNotEmpty($result);
		$this->assertEquals(0, $result['numlikes']);
		$this->assertEquals(0, $result['numdislikes']);

		$result = $this->object->like_avatar_wall_post($session_username, $username, $avatar_wall_post_id);
		$this->assertNotEmpty($result);
		$this->assertEquals(1, $result['numlikes']);
		$this->assertEquals(0, $result['numdislikes']);
    }

//    /**
//     * @covers AvatarDAO::get_categories
//     * @todo   Implement testGet_categories().
//     */
//    public function testGet_categories()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_all_categories
//     * @todo   Implement testGet_all_categories().
//     */
//    public function testGet_all_categories()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_active_avatar_sets
//     * @todo   Implement testGet_active_avatar_sets().
//     */
//    public function testGet_active_avatar_sets()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_set_items
//     * @todo   Implement testGet_set_items().
//     */
//    public function testGet_set_items()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::user_has_avatar
//     * @todo   Implement testUser_has_avatar().
//     */
//    public function testUser_has_avatar()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::user_has_avatar_from_username
//     * @todo   Implement testUser_has_avatar_from_username().
//     */
//    public function testUser_has_avatar_from_username()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::use_body
//     * @todo   Implement testUse_body().
//     */
//    public function testUse_body()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_user_avatar_body
//     * @todo   Implement testGet_user_avatar_body().
//     */
//    public function testGet_user_avatar_body()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_user_avatar_body_uuid_by_user_id
//     * @todo   Implement testGet_user_avatar_body_uuid_by_user_id().
//     */
//    public function testGet_user_avatar_body_uuid_by_user_id()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_user_avatar_body_uuid
//     * @todo   Implement testGet_user_avatar_body_uuid().
//     */
//    public function testGet_user_avatar_body_uuid()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::set_user_avatar_body_uuid
//     * @todo   Implement testSet_user_avatar_body_uuid().
//     */
//    public function testSet_user_avatar_body_uuid()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_user_avatar_items
//     * @todo   Implement testGet_user_avatar_items().
//     */
//    public function testGet_user_avatar_items()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::add_avatar_set_to_user
//     * @todo   Implement testAdd_avatar_set_to_user().
//     */
//    public function testAdd_avatar_set_to_user()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::add_avatar_item_to_user
//     * @todo   Implement testAdd_avatar_item_to_user().
//     */
//    public function testAdd_avatar_item_to_user()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::equip_set_for_user
//     * @todo   Implement testEquip_set_for_user().
//     */
//    public function testEquip_set_for_user()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::equip_item_for_user
//     * @todo   Implement testEquip_item_for_user().
//     */
//    public function testEquip_item_for_user()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::unequip_item_for_user
//     * @todo   Implement testUnequip_item_for_user().
//     */
//    public function testUnequip_item_for_user()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::can_equip_item
//     * @todo   Implement testCan_equip_item().
//     */
//    public function testCan_equip_item()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_category
//     * @todo   Implement testGet_category().
//     */
//    public function testGet_category()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_avatar_item
//     * @todo   Implement testGet_avatar_item().
//     */
//    public function testGet_avatar_item()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_avatar_items
//     * @todo   Implement testGet_avatar_items().
//     */
//    public function testGet_avatar_items()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::set_is_owned
//     * @todo   Implement testSet_is_owned().
//     */
//    public function testSet_is_owned()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::item_is_owned
//     * @todo   Implement testItem_is_owned().
//     */
//    public function testItem_is_owned()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::item_requires_ownership
//     * @todo   Implement testItem_requires_ownership().
//     */
//    public function testItem_requires_ownership()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::set_requires_ownership
//     * @todo   Implement testSet_requires_ownership().
//     */
//    public function testSet_requires_ownership()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::item_is_wearable
//     * @todo   Implement testItem_is_wearable().
//     */
//    public function testItem_is_wearable()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_avatar_ratings
//     * @todo   Implement testGet_avatar_ratings().
//     */
//    public function testGet_avatar_ratings()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::get_avatar_comment_count
//     * @todo   Implement testGet_avatar_comment_count().
//     */
//    public function testGet_avatar_comment_count()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers AvatarDAO::get_avatar_wall_post
//     * @todo   Implement testGet_avatar_wall_post().
//     */
//    public function testGet_avatar_wall_post()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::create_avatar_post
//     * @todo   Implement testCreate_avatar_post().
//     */
//    public function testCreate_avatar_post()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::remove_avatar_post
//     * @todo   Implement testRemove_avatar_post().
//     */
//    public function testRemove_avatar_post()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers AvatarDAO::dislike_avatar_wall_post
//     * @todo   Implement testDislike_avatar_wall_post().
//     */
//    public function testDislike_avatar_wall_post()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers AvatarDAO::get_user_current_avatar_items
//     * @todo   Implement testGet_user_current_avatar_items().
//     */
//    public function testGet_user_current_avatar_items()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::set_total_comments_count_in_cache
//     * @todo   Implement testSet_total_comments_count_in_cache().
//     */
//    public function testSet_total_comments_count_in_cache()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::update_avatar_comment_cache
//     * @todo   Implement testUpdate_avatar_comment_cache().
//     */
//    public function testUpdate_avatar_comment_cache()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::insert_comment_to_cache
//     * @todo   Implement testInsert_comment_to_cache().
//     */
//    public function testInsert_comment_to_cache()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::delete_comment_from_cache
//     * @todo   Implement testDelete_comment_from_cache().
//     */
//    public function testDelete_comment_from_cache()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers AvatarDAO::fetch_comments_from_cache
//     * @todo   Implement testFetch_comments_from_cache().
//     */
//    public function testFetch_comments_from_cache()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
}
