<?php
fast_require('IceDAO', get_dao_directory() . '/ice_dao.php');
fast_require('FusionREST', get_library_directory() . '/fusion/fusion_rest.php');
fast_require('Encrypt', get_library_directory() . '/encoder/Encrypt.php');
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-14 at 09:47:46.
 */
class IceDAOTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var IceDAO
     */
    protected $object;
	public $logged_in;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new IceDAO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers IceDAO::loadProfile
     */
    public function testLoadProfile()
    {
		$result = IceDAO::loadProfile();
		$this->assertInstanceOf('Ice_Communicator', $result);
    }

    /**
     * @covers IceDAO::get_object_prx
     */
    public function testGet_object_prx()
    {
		$config = new IceDomain('registry');
		$result = IceDAO::get_object_prx($config);
		$this->assertInstanceOf('Ice_ObjectPrx', $result);
    }

	private function login_and_create_ice_session($username=null, $password=null, $view = 'mig33_wap')
	{
		if ( isset($this->logged_in[$username]) ) return;
		$request = array(
			  'username'	=> $username
			, 'password'	=> $password
			, 'view'        => $view
		);
		$result = FusionRest::get_instance()->post(FusionRest::KEYSPACE_SESSION_LOGIN, $request);
		if (empty($result['sessionId']))
		{
			$this->fail("SessionId not found.");
		}
		else
		{
			$esid_json = Encrypt::get_instance()->decode($result['sessionId']);
			$esid = json_decode($esid_json);
			$_COOKIE[SessionUtilities::SESSION_COOKIE_KEY] = $esid->sid;
			$this->create_user_session($esid->sid);
			$this->logged_in[$username] = $esid->sid;
		}
	}

	private function create_user_session($sid=null)
	{
		if (is_null($sid)) return false;
		$post_curlopt = array
		(
			  CURLOPT_URL            => $GLOBALS['server_root'] . '/xml/'
			, CURLOPT_POST           => 1
			, CURLOPT_POSTFIELDS     => '{"T":211,"I":2,"F":{"2":5,"3":"'.$sid.'"}}'
			, CURLOPT_SSL_VERIFYHOST => 0
			, CURLOPT_SSL_VERIFYPEER => false
			, CURLOPT_RETURNTRANSFER => 1
			, CURLOPT_VERBOSE        => 0
			, CURLOPT_HEADER         => true
			, CURLINFO_HEADER_OUT    => true
			, CURLOPT_FOLLOWLOCATION => true
			, CURLOPT_MAXREDIRS      => 5
			, CURLOPT_USERAGENT      => 'mig33 Core API v2'
			, CURLOPT_HTTPHEADER     => array(
				  'Cache-Control: must-revalidate, post-check=0, pre-check=0'
				, 'Expires: 0'
				, 'Pragma: no-cache'
				, 'Expect:'
				, 'Content-Type: application/json'
				, 'X-Mig33-JSON-Version: 2' // Important to have this header for it to work.
			)
		);

		// Init CURL
		$ch = curl_init();

		// Set CURL Options
		curl_setopt_array($ch, $post_curlopt);

		// CURL It
		$raw_response = curl_exec($ch);
		$curl_errno   = curl_errno($ch);
		$curl_errmsg  = curl_error($ch) ;
		$curl_info    = curl_getinfo($ch);

		// Close CURL
		curl_close($ch);

		if ($curl_errno > 0) return false;
		return true;
	}

    /**
     * @covers IceDAO::check_session
     */
    public function testCheck_session()
    {
		$this->markTestSkipped('Pending fix');
		try
		{
			$result = $this->object->check_session();
			$this->fail("Should not be allowing.");
		}
		catch (IceDAOException $ex)
		{
			$this->assertTrue(true);
		}
		$this->login_and_create_ice_session('cherrymoo', '11password');
		try
		{
			$result = $this->object->check_session();
			$this->assertTrue(true);
		}
		catch (IceDAOException $ex)
		{
			$this->fail("ICE Session created.");
		}
    }

    /**
     * @covers IceDAO::get_username
     */
    public function testGet_username()
    {
		$this->markTestSkipped('Pending fix');
		$this->login_and_create_ice_session('cherrymoo', '11password');
        $result = $this->object->get_username(0);
		$this->assertEquals('cherrymoo', $result);
    }

    /**
     * @covers IceDAO::get_userdata
     */
    public function testGet_userdata()
    {
		$this->markTestSkipped('Pending fix');
		$this->login_and_create_ice_session('cherrymoo', '11password');
        $result = $this->object->get_userdata();
		$this->assertInstanceOf('com_projectgoth_fusion_slice_UserDataIce', $result);
		$this->assertEquals('cherrymoo', $result->username);
    }

    /**
     * @covers IceDAO::disconnect_flooder
     * @todo   Implement testDisconnect_flooder().
     */
    public function testDisconnect_flooder()
    {
		$this->markTestSkipped('Unable to test without flushing the memcache.');
        $this->login_and_create_ice_session('joker2', '11password');
		$this->object->disconnect_flooder('Just testing...');
		try
		{
			$this->object->check_session();
			$this->fail("Should not logged in.");
		}
		catch (IceDAOException $ex)
		{
			$this->assertTrue(true);
		}
    }

    /**
     * @covers IceDAO::get_stats
     */
    public function testGet_stats()
    {
		$this->login_and_create_ice_session('cherrymoo', '11password');
		$result = $this->object->get_stats();
		$this->assertInstanceOf('com_projectgoth_fusion_slice_RegistryStats', $result);
    }

    /**
     * @covers IceDAO::get_other_im_credentials
     */
    public function testGet_other_im_credentials()
    {
		$this->markTestSkipped('Pending fix');
		$this->login_and_create_ice_session('cherrymoo', '11password');
        $result = $this->object->get_other_im_credentials();
		$this->assertNotEmpty($result);
		$this->assertInstanceOf('com_projectgoth_fusion_slice_Credential', $result[0]);
		$this->assertEquals(14, $result[0]->passwordType);
    }

    /**
     * @covers IceDAO::get_im_credentials
     */
    public function testGet_im_credentials()
    {
		$this->markTestSkipped('Pending fix');
		$this->login_and_create_ice_session('cherrymoo', '11password');
		$result = $this->object->get_other_im_credentials();
		$this->assertNotEmpty($result);
		$this->assertInstanceOf('com_projectgoth_fusion_slice_Credential', $result[0]);
		$this->assertEquals(14, $result[0]->passwordType);
    }

    /**
     * @covers IceDAO::get_other_im_contacts
     */
    public function testGet_other_im_contacts()
    {
		$this->markTestSkipped('Pending fix');
		$this->login_and_create_ice_session('cherrymoo', '11password');
		$this->login_and_create_ice_session('joker2', '11password');
		$username = 'joker2';
		$result = $this->object->get_other_im_contacts($username);
        $this->assertTrue(is_array($result));
    }

    /**
     * @covers IceDAO::get_overall_presence
     */
    public function testGet_overall_presence()
    {
		$this->markTestSkipped('Pending fix');

		$this->login_and_create_ice_session('cherrymoo', '11password');
        $result = $this->object->get_overall_presence('joker2', 'cherrymoo');
		$this->assertEquals(1, $result);
		$result = $this->object->get_overall_presence('cherrymoo', 'joker2');
		$this->assertEquals(1, $result);
    }

    /**
     * @covers IceDAO::get_current_chatrooms
     */
    public function testGet_current_chatrooms()
    {
		$this->login_and_create_ice_session('cherrymoo', '11password');
        $result = $this->object->get_current_chatrooms('cherrymoo');
		$this->assertTrue(is_array($result));
    }

    /**
     * @covers IceDAO::get_chatroom_users
     */
    public function testGet_chatroom_users()
    {
		$this->login_and_create_ice_session('cherrymoo', '11password');
		$result = $this->object->get_chatroom_users('legoland', 'cherrymoo');
		$this->assertTrue(is_array($result));
    }

    /**
     * @covers IceDAO::get_groupchat_users
     */
    public function testGet_groupchat_users()
    {
		$this->login_and_create_ice_session('cherrymoo', '11password');
		$groupchatid = '260';
		$username = 'cherrymoo';
        $result = $this->object->get_groupchat_users($groupchatid, $username);
		$this->assertTrue(is_array($result));
    }

    /**
     * @covers IceDAO::email_notification
     */
    public function testEmail_notification()
    {
		$this->markTestSkipped('Pending fix');

		$this->login_and_create_ice_session('cherrymoo', '11password');
		try
		{
			$this->object->email_notification(10);
		}
		catch (Exception $ex)
		{
			$this->fail("Unable to set email notification: " . $ex->getMessage());
		}
    }

    /**
     * @covers IceDAO::edit_profile_metric
     */
    public function testEdit_profile_metric()
    {
		$this->markTestSkipped('Pending fix');

		$this->login_and_create_ice_session('cherrymoo', '11password');
		try
		{
			$this->object->edit_profile_metric();
		}
		catch (Exception $ex)
		{
			$this->fail("Unable to edit profile metric: " . $ex->getMessage());
		}
    }

    /**
     * @covers IceDAO::update_theme_metric
     */
    public function testUpdate_theme_metric()
    {
		$this->markTestSkipped('Pending fix');

		$this->login_and_create_ice_session('cherrymoo', '11password');
		try
		{
			$this->object->update_theme_metric();
		}
		catch (Exception $ex)
		{
			$this->fail("Unable to update theme metric: " . $ex->getMessage());
		}
    }

    /**
     * @covers IceDAO::get_publishing_privacy_setting
     */
    public function testGet_publishing_privacy_setting()
    {
		$this->login_and_create_ice_session('cherrymoo', '11password');
		$username = 'cherrymoo';
		$result = $this->object->get_publishing_privacy_setting($username);
		$this->assertInstanceOf('com_projectgoth_fusion_slice_EventPrivacySettingIce', $result);
    }

    /**
     * @covers IceDAO::get_receiving_privacy_setting
     */
    public function testGet_receiving_privacy_setting()
    {
		$this->login_and_create_ice_session('cherrymoo', '11password');
		$username = 'cherrymoo';
		$result = $this->object->get_receiving_privacy_setting($username);
		$this->assertInstanceOf('com_projectgoth_fusion_slice_EventPrivacySettingIce', $result);
    }

    /**
     * @covers IceDAO::set_publishing_privacy_setting
     */
    public function testSet_publishing_privacy_setting()
    {
		$this->login_and_create_ice_session('cherrymoo', '11password');
		$username = 'cherrymoo';
		$org_settings = $this->object->get_publishing_privacy_setting($username);
		$cur_status = $org_settings->statusUpdates;

		$org_settings->statusUpdates = !$cur_status;
		$this->object->set_publishing_privacy_setting($username, $org_settings);

		$new_settings = $this->object->get_publishing_privacy_setting($username);
		$this->assertEquals(!$cur_status, $new_settings->statusUpdates);

		$new_settings->statusUpdates = $cur_status;
		$this->object->set_publishing_privacy_setting($username, $new_settings);
    }

    /**
     * @covers IceDAO::set_receiving_privacy_setting
     */
    public function testSet_receiving_privacy_setting()
    {
		$this->login_and_create_ice_session('cherrymoo', '11password');
		$username = 'cherrymoo';
		$settings = $this->object->get_receiving_privacy_setting($username);

		$cur_status_updates = $settings->statusUpdates;
		$settings->statusUpdates = !$cur_status_updates;
		$this->object->set_receiving_privacy_setting($username, $settings);

		$new_settings = $this->object->get_receiving_privacy_setting($username);
		$this->assertEquals(!$cur_status_updates, $new_settings->statusUpdates);

		$settings->statusUpdates = $cur_status_updates;
		$this->object->set_receiving_privacy_setting($username, $settings);
    }

    /**
     * @covers IceDAO::get_online_contacts_count
     */
    public function testGet_online_contacts_count()
    {
		$this->markTestSkipped('Pending fix');

		$this->login_and_create_ice_session('cherrymoo', '11password');
		$result = $this->object->get_online_contacts_count();
		$this->assertTrue(is_int($result));
    }

    /**
     * @covers IceDAO::get_mobile_device
     */
    public function testGet_mobile_device()
    {
		$this->markTestSkipped('Pending fix');

		$this->login_and_create_ice_session('cherrymoo', '11password');
		$result = $this->object->get_mobile_device();
		$this->assertNotEmpty($result);
    }
}
