<?php
require_once "PHPUnit/Extensions/Database/TestCase.php";
fast_require('MerchantDAO', get_dao_directory() . '/merchant_dao.php');
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-16 at 16:46:28.
 */
class MerchantDAOTest extends PHPUnit_Extensions_Database_TestCase
{
    /**
     * @var MerchantDAO
     */
    protected $object;

	/**
     * @return PHPUnit_Extensions_Database_DB_IDatabaseConnection
     */
    public function getConnection()
    {
		$pdo = new PDO($GLOBALS['L_DB_DSN'], $GLOBALS['L_DB_USER'], $GLOBALS['L_DB_PWD']);
		$pdo->exec("set foreign_key_checks = 0;");
		return $this->createDefaultDBConnection($pdo, $GLOBALS['L_DB_NAME']);
    }

	/**
     * @return PHPUnit_Extensions_Database_DataSet_IDataSet
     */
    public function getDataSet()
    {
		global $test_base_dir;
		return $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/frame252.xml');
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		parent::setUp();
		Memcached::get_instance()->flush();
        $this->object = new MerchantDAO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
		$this->getConnection()->getConnection()->exec("set foreign_key_checks = 1;");;
		parent::tearDown();
    }

	public function testPlaceHolder()
	{
		$this->assertTrue(true);
	}

//    /**
//     * @covers MerchantDAO::get_login_count
//     * @todo   Implement testGet_login_count().
//     */
//    public function testGet_login_count()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::increment_merchant_login
//     * @todo   Implement testIncrement_merchant_login().
//     */
//    public function testIncrement_merchant_login()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::insert_merchant_mentor
//     * @todo   Implement testInsert_merchant_mentor().
//     */
//    public function testInsert_merchant_mentor()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::insert_merchant_referrer
//     * @todo   Implement testInsert_merchant_referrer().
//     */
//    public function testInsert_merchant_referrer()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_account_transactions
//     * @todo   Implement testGet_account_transactions().
//     */
//    public function testGet_account_transactions()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_account_transactions_summary
//     * @todo   Implement testGet_account_transactions_summary().
//     */
//    public function testGet_account_transactions_summary()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_month_year_transactions
//     * @todo   Implement testGet_month_year_transactions().
//     */
//    public function testGet_month_year_transactions()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::search_customer
//     * @todo   Implement testSearch_customer().
//     */
//    public function testSearch_customer()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_customer_transaction_summary
//     * @todo   Implement testGet_customer_transaction_summary().
//     */
//    public function testGet_customer_transaction_summary()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_customer_transactions
//     * @todo   Implement testGet_customer_transactions().
//     */
//    public function testGet_customer_transactions()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::registerMerchant
//     * @todo   Implement testRegisterMerchant().
//     */
//    public function testRegisterMerchant()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_sub_merchants
//     * @todo   Implement testGet_sub_merchants().
//     */
//    public function testGet_sub_merchants()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_merchant
//     * @todo   Implement testGet_merchant().
//     */
//    public function testGet_merchant()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_mentor
//     * @todo   Implement testGet_mentor().
//     */
//    public function testGet_mentor()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_merchant_latest_transfer
//     * @todo   Implement testGet_merchant_latest_transfer().
//     */
//    public function testGet_merchant_latest_transfer()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_authentication_token
//     * @todo   Implement testGet_authentication_token().
//     */
//    public function testGet_authentication_token()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::store_authentication_token
//     * @todo   Implement testStore_authentication_token().
//     */
//    public function testStore_authentication_token()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::set_authentication_active_by_token
//     * @todo   Implement testSet_authentication_active_by_token().
//     */
//    public function testSet_authentication_active_by_token()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::set_authentication_active
//     * @todo   Implement testSet_authentication_active().
//     */
//    public function testSet_authentication_active()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::check_authentication_token_exists
//     * @todo   Implement testCheck_authentication_token_exists().
//     */
//    public function testCheck_authentication_token_exists()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::authentication_token_exists
//     * @todo   Implement testAuthentication_token_exists().
//     */
//    public function testAuthentication_token_exists()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::remove_authentication_tokens
//     * @todo   Implement testRemove_authentication_tokens().
//     */
//    public function testRemove_authentication_tokens()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::remove_unauthenticated_tokens
//     * @todo   Implement testRemove_unauthenticated_tokens().
//     */
//    public function testRemove_unauthenticated_tokens()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::remove_authenticated_tokens
//     * @todo   Implement testRemove_authenticated_tokens().
//     */
//    public function testRemove_authenticated_tokens()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::verify_secret
//     * @todo   Implement testVerify_secret().
//     */
//    public function testVerify_secret()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_secret_question
//     * @todo   Implement testGet_secret_question().
//     */
//    public function testGet_secret_question()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_merchants_in_country
//     * @todo   Implement testGet_merchants_in_country().
//     */
//    public function testGet_merchants_in_country()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_user_friends
//     * @todo   Implement testGet_user_friends().
//     */
//    public function testGet_user_friends()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_user_merchant
//     * @todo   Implement testGet_user_merchant().
//     */
//    public function testGet_user_merchant()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_user_mentor
//     * @todo   Implement testGet_user_mentor().
//     */
//    public function testGet_user_mentor()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_merchant_in_location_name
//     * @todo   Implement testGet_merchant_in_location_name().
//     */
//    public function testGet_merchant_in_location_name()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_merchant_performance
//     * @todo   Implement testGet_merchant_performance().
//     */
//    public function testGet_merchant_performance()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_dashboard_old_customers
//     * @todo   Implement testGet_dashboard_old_customers().
//     */
//    public function testGet_dashboard_old_customers()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_top_merchant_achievements_country
//     * @todo   Implement testGet_top_merchant_achievements_country().
//     */
//    public function testGet_top_merchant_achievements_country()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_top_merchant_achievements_all
//     * @todo   Implement testGet_top_merchant_achievements_all().
//     */
//    public function testGet_top_merchant_achievements_all()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_merchant_popular_groups_in_country
//     * @todo   Implement testGet_merchant_popular_groups_in_country().
//     */
//    public function testGet_merchant_popular_groups_in_country()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_merchant_popular_chatrooms_in_country
//     * @todo   Implement testGet_merchant_popular_chatrooms_in_country().
//     */
//    public function testGet_merchant_popular_chatrooms_in_country()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::fix_merchanttag_accountentry
//     * @todo   Implement testFix_merchanttag_accountentry().
//     */
//    public function testFix_merchanttag_accountentry()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_top_active_tags
//     * @todo   Implement testGet_top_active_tags().
//     */
//    public function testGet_top_active_tags()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_top_inactive_tags
//     * @todo   Implement testGet_top_inactive_tags().
//     */
//    public function testGet_top_inactive_tags()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_merchant_tag_stats
//     * @todo   Implement testGet_merchant_tag_stats().
//     */
//    public function testGet_merchant_tag_stats()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::get_mail_template_from_server
//     * @todo   Implement testGet_mail_template_from_server().
//     */
//    public function testGet_mail_template_from_server()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::send_merchant_email
//     * @todo   Implement testSend_merchant_email().
//     */
//    public function testSend_merchant_email()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MerchantDAO::send_campaign_email
//     * @todo   Implement testSend_campaign_email().
//     */
//    public function testSend_campaign_email()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
}
