<?php
require_once "PHPUnit/Extensions/Database/TestCase.php";
fast_require('PhotosDAO', get_dao_directory() . '/photos_dao.php');
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-16 at 16:47:10.
 */
class PhotosDAOTest extends PHPUnit_Extensions_Database_TestCase
{
    /**
     * @var PhotosDAO
     */
    protected $object;

	/**
     * @return PHPUnit_Extensions_Database_DB_IDatabaseConnection
     */
    public function getConnection()
    {
		$pdo = new PDO($GLOBALS['L_DB_DSN'], $GLOBALS['L_DB_USER'], $GLOBALS['L_DB_PWD']);
		$pdo->exec("set foreign_key_checks = 0;");
		return $this->createDefaultDBConnection($pdo, $GLOBALS['L_DB_NAME']);
    }

	/**
     * @return PHPUnit_Extensions_Database_DataSet_IDataSet
     */
    public function getDataSet()
    {
		global $test_base_dir;
		return $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/frame252.xml');
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		parent::setUp();
		Memcached::get_instance()->flush();
        $this->object = new PhotosDAO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
		$this->getConnection()->getConnection()->exec("set foreign_key_checks = 1;");;
		parent::tearDown();
    }

	/**
     * @covers PhotosDAO::get_photos
     */
    public function testGet_photos()
    {
		$session_user = "cherrymoo";
		$username = "cherrymoo";
		$offset = 0;
		$number_of_entries = 10;
        $result = $this->object->get_photos($session_user, $username, $offset, $number_of_entries);
		$this->assertNotEmpty($result);
		$this->assertEquals(2, count($result['photos']));
		$this->assertEquals(2, $result['total_count']);

		$session_user = "joker2";
		$result = $this->object->get_photos($session_user, $username, $offset, $number_of_entries);
		$this->assertNotEmpty($result);
		$this->assertEquals(1, count($result['photos']));
		$this->assertEquals(1, $result['total_count']);

		$session_user = "cherrymoo";
		$username = "joker2";
		$result = $this->object->get_photos($session_user, $username, $offset, $number_of_entries);
		$this->assertNotEmpty($result);
		$this->assertEquals(0, count($result['photos']));
		$this->assertEquals(0, $result['total_count']);

		try
		{
			$session_user = "cherrymoo";
			$username = "lesterchan";
			$result = $this->object->get_photos($session_user, $username, $offset, $number_of_entries);
			$this->fail("Should not be able to see this photo.");
		}
		catch (Exception $ex)
		{
			$msg = $ex->getMessage();
			if ($msg == "You are not allowed to view lesterchan's photos")
			{
				$this->assertTrue(true);
			}
			else
			{
				$this->fail("Should not be able to see this photo.");
			}
		}
    }

	/**
     * @covers PhotosDAO::photo_exists
     */
	public function testPhoto_exists()
	{
		$scrapbook_id = 1;
		$result = $this->object->photo_exists($scrapbook_id);
		$this->assertTrue($result);

		$scrapbook_id = 499;
		$result = $this->object->photo_exists($scrapbook_id);
		$this->assertFalse($result);

		$scrapbook_id = -20;
		$result = $this->object->photo_exists($scrapbook_id);
		$this->assertFalse($result);

		$scrapbook_id = "more_stupid_id";
		$result = $this->object->photo_exists($scrapbook_id);
		$this->assertFalse($result);
	}

	/**
     * @covers PhotosDAO::like_photo
     */
    public function testLike_photo()
    {
		$this->getConnection()->getConnection()->query("DELETE FROM system WHERE PropertyName = '".SystemProperty::Photo_PhotoLikeEnabled."'");
		XCache::getInstance()->delete(XCache::KEYSPACE_SYSTEM_PROPERTIES);
		SystemProperty::get_instance(true);

		$session_username = "joker2";
		$scrapbook_id = 3; // cherrymoo photo
		$like = 1;
        $result = $this->object->like_photo($session_username, $scrapbook_id, $like);
		$this->assertNotEmpty($result);
		$this->assertEquals(1 , $result['numlikes']);
		$this->assertEquals(0 , $result['numdislikes']);

		$session_username = "lesterchan";
		$result = $this->object->like_photo($session_username, $scrapbook_id, $like);
		$this->assertNotEmpty($result);
		$this->assertEquals(2 , $result['numlikes']);
		$this->assertEquals(0 , $result['numdislikes']);

		$session_username = "lesterchan";
		$result = $this->object->dislike_photo($session_username, $scrapbook_id);
		$this->assertNotEmpty($result);
		$this->assertEquals(1 , $result['numlikes']);
		$this->assertEquals(1 , $result['numdislikes']);

		$session_username = "joker2";
		$scrapbook_id = 433; // Invalid ID
		$result = $this->object->like_photo($session_username, $scrapbook_id, $like);
		$this->assertEquals(null, $result, "Should not like/dislike an invalid photo");

		$scrapbook_id = -20;
		$like = 1;
		$result = $this->object->like_photo($session_username, $scrapbook_id, $like);
		$this->assertEquals(null, $result);

		$scrapbook_id = 1;
		$like = 20;
		$result = $this->object->like_photo($session_username, $scrapbook_id, $like);
		$this->assertEquals(null, $result);

		$like = -20;
		$result = $this->object->like_photo($session_username, $scrapbook_id, $like);
		$this->assertEquals(null, $result);
    }

	public function testDisablePhotoLikes()
	{
		$this->getConnection()->getConnection()->query("INSERT INTO system (`PropertyName`, `PropertyValue`) VALUES ('".SystemProperty::Photo_PhotoLikeEnabled."', '0') ON DUPLICATE KEY UPDATE PropertyValue = '0'");
		XCache::getInstance()->delete(XCache::KEYSPACE_SYSTEM_PROPERTIES);
		SystemProperty::get_instance(true);

		$session_username = "joker2";
		$scrapbook_id = 3; // cherrymoo photo
		$like = 1;
        $result = $this->object->like_photo($session_username, $scrapbook_id, $like);
		$this->assertEquals(null, $result, "Should obey system prop flag to disallow Photo Like");
	}

//    /**
//     * @covers PhotosDAO::get_photo_id_from_file_id
//     * @todo   Implement testGet_photo_id_from_file_id().
//     */
//    public function testGet_photo_id_from_file_id()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers PhotosDAO::is_photo_owned_by_user
//     * @todo   Implement testIs_photo_owned_by_user().
//     */
//    public function testIs_photo_owned_by_user()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers PhotosDAO::get_single_photo
//     * @todo   Implement testGet_single_photo().
//     */
//    public function testGet_single_photo()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers PhotosDAO::get_single_photo_with_offset
//     * @todo   Implement testGet_single_photo_with_offset().
//     */
//    public function testGet_single_photo_with_offset()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers PhotosDAO::get_photo
//     * @todo   Implement testGet_photo().
//     */
//    public function testGet_photo()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers PhotosDAO::get_photos_old
//     * @todo   Implement testGet_photos_old().
//     */
//    public function testGet_photos_old()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers PhotosDAO::dislike_photo
//     * @todo   Implement testDislike_photo().
//     */
//    public function testDislike_photo()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers PhotosDAO::get_photo_likes
//     * @todo   Implement testGet_photo_likes().
//     */
//    public function testGet_photo_likes()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers PhotosDAO::get_photos_likes
//     * @todo   Implement testGet_photos_likes().
//     */
//    public function testGet_photos_likes()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
}
