<?php
require_once "PHPUnit/Extensions/Database/TestCase.php";
fast_require('StoreDAO', get_dao_directory() . '/store_dao.php');
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-16 at 16:47:44.
 */
class StoreDAOTest extends PHPUnit_Extensions_Database_TestCase
{
    /**
     * @var StoreDAO
     */
    protected $object;

	/**
     * @return PHPUnit_Extensions_Database_DB_IDatabaseConnection
     */
    public function getConnection()
    {
		$pdo = new PDO($GLOBALS['L_DB_DSN'], $GLOBALS['L_DB_USER'], $GLOBALS['L_DB_PWD']);
		$pdo->exec("set foreign_key_checks = 0;");
		return $this->createDefaultDBConnection($pdo, $GLOBALS['L_DB_NAME']);
    }

	/**
     * @return PHPUnit_Extensions_Database_DataSet_IDataSet
     */
    public function getDataSet()
    {
		global $test_base_dir;
		return $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/frame252.xml');
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		parent::setUp();
		Memcached::get_instance()->flush();
        $this->object = new StoreDAO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
		$this->getConnection()->getConnection()->exec("set foreign_key_checks = 1;");;
		parent::tearDown();
    }

	/**
     * @covers StoreDAO::rate_item
     */
    public function testRate_item()
    {
		$session_username = "joker2";
		$storeitem_id = 1;
		$rating = 5;
        $result = $this->object->rate_item($session_username, $storeitem_id, $rating);
		$this->assertNotEmpty($result);
		$this->assertEquals(5, $result['average']);
		$this->assertEquals(1, $result['numratings']);

		$session_username = "cherrymoo";
		$rating = 3;
        $result = $this->object->rate_item($session_username, $storeitem_id, $rating);
		$this->assertNotEmpty($result);
		$this->assertEquals(4, $result['average']);
		$this->assertEquals(2, $result['numratings']);
    }

//    /**
//     * @covers StoreDAO::get_featured_items
//     * @todo   Implement testGet_featured_items().
//     */
//    public function testGet_featured_items()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_new_items
//     * @todo   Implement testGet_new_items().
//     */
//    public function testGet_new_items()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_new_item
//     * @todo   Implement testGet_new_item().
//     */
//    public function testGet_new_item()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_free_items
//     * @todo   Implement testGet_free_items().
//     */
//    public function testGet_free_items()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_popular_items
//     * @todo   Implement testGet_popular_items().
//     */
//    public function testGet_popular_items()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_popular_item
//     * @todo   Implement testGet_popular_item().
//     */
//    public function testGet_popular_item()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_recent_gifts_given
//     * @todo   Implement testGet_recent_gifts_given().
//     */
//    public function testGet_recent_gifts_given()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_all_items
//     * @todo   Implement testGet_all_items().
//     */
//    public function testGet_all_items()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_items_in_category
//     * @todo   Implement testGet_items_in_category().
//     */
//    public function testGet_items_in_category()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_categories
//     * @todo   Implement testGet_categories().
//     */
//    public function testGet_categories()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_parent_category
//     * @todo   Implement testGet_parent_category().
//     */
//    public function testGet_parent_category()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::has_subcategory
//     * @todo   Implement testHas_subcategory().
//     */
//    public function testHas_subcategory()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_category
//     * @todo   Implement testGet_category().
//     */
//    public function testGet_category()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_recently_purchased
//     * @todo   Implement testGet_recently_purchased().
//     */
//    public function testGet_recently_purchased()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_item
//     * @todo   Implement testGet_item().
//     */
//    public function testGet_item()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_categories_where_item_belong
//     * @todo   Implement testGet_categories_where_item_belong().
//     */
//    public function testGet_categories_where_item_belong()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_currency_list
//     * @todo   Implement testGet_currency_list().
//     */
//    public function testGet_currency_list()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_category_id_list
//     * @todo   Implement testGet_category_id_list().
//     */
//    public function testGet_category_id_list()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_item_id_list
//     * @todo   Implement testGet_item_id_list().
//     */
//    public function testGet_item_id_list()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_item_ratings
//     * @todo   Implement testGet_item_ratings().
//     */
//    public function testGet_item_ratings()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::get_items_ratings
//     * @todo   Implement testGet_items_ratings().
//     */
//    public function testGet_items_ratings()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers StoreDAO::search_items
//     * @todo   Implement testSearch_items().
//     */
//    public function testSearch_items()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
}
