<?php
require_once "PHPUnit/Extensions/Database/TestCase.php";
fast_require('UserDAO', get_dao_directory() . '/user_dao.php');
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-16 at 16:48:28.
 */
class MockUserDAO extends UserDAO
{
	public function get_static_userdetails()
	{
		return parent::$user_details;
	}
}
class UserDAOTest extends PHPUnit_Extensions_Database_TestCase
{
    /**
     * @var MockUserDAO
     */
    protected $object;

	/**
     * @return PHPUnit_Extensions_Database_DB_IDatabaseConnection
     */
    public function getConnection()
    {
		$pdo = new PDO($GLOBALS['L_DB_DSN'], $GLOBALS['L_DB_USER'], $GLOBALS['L_DB_PWD']);
		$pdo->exec("set foreign_key_checks = 0;");
		return $this->createDefaultDBConnection($pdo, $GLOBALS['L_DB_NAME']);
    }

	/**
     * @return PHPUnit_Extensions_Database_DataSet_IDataSet
     */
    public function getDataSet()
    {
		global $test_base_dir;
		return $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/frame252.xml');
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		parent::setUp();
		Memcached::get_instance()->flush();
        $this->object = new MockUserDAO();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
		$this->getConnection()->getConnection()->exec("set foreign_key_checks = 1;");;
		parent::tearDown();
    }

	/**
     * @covers UserDAO::get_user_level
     */
    public function testGet_user_level()
    {
		$username = 'cherrymoo';
        $result = $this->object->get_user_level($username);
		$this->assertNotEmpty($result);
		$this->assertEquals(15, $result['level']);
    }

	/**
     * @covers UserDAO::get_user_level_and_reputation_level_permission
     */
    public function testGet_user_level_and_reputation_level_permission()
    {
        $username = 'cherrymoo';
		$reputation_level_permission_action = 'PostCommentLikeUserWall';
        $result = $this->object->get_user_level_and_reputation_level_permission($username, $reputation_level_permission_action);
		$this->assertNotEmpty($result);
		$this->assertGreaterThanOrEqual($result['required_level'], $result['user_level']);
    }

//    /**
//     * @covers UserDAO::get_user_id
//     * @todo   Implement testGet_user_id().
//     */
//    public function testGet_user_id()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::mig33_user_exists
//     * @todo   Implement testMig33_user_exists().
//     */
//    public function testMig33_user_exists()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_by_mobile_phone
//     * @todo   Implement testGet_user_by_mobile_phone().
//     */
//    public function testGet_user_by_mobile_phone()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::disable_user_permanently
//     * @todo   Implement testDisable_user_permanently().
//     */
//    public function testDisable_user_permanently()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
	public function validUsers()
	{
		return array(
			  array("cherrymoo", 2160)
			, array("lesterchan", 1)
			, array("infn8loop", 9)
		);
	}

	/**
	* @covers UserDAO::get_user_detail
	* @dataProvider validUsers
	*/
	public function testGet_user_detail($username, $userid)
	{
		$result = $this->object->get_user_detail($username);
		$this->assertInstanceOf('UserDetail', $result, "Check instance of UserDetail");
		$this->assertEquals($result->username, $username, "Check user name");
		$this->assertEquals($result, $this->object->get_user_detail($username), "Checking again the same object");
		$userdetails = $this->object->get_static_userdetails();
		$this->assertEquals($result, $userdetails['username'][$username], "Checking static UserDetails");
	}

//    /**
//     * @covers UserDAO::is_valid_alias
//     * @todo   Implement testIs_valid_alias().
//     */
//    public function testIs_valid_alias()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::is_valid_alias_via_rest
//     * @todo   Implement testIs_valid_alias_via_rest().
//     */
//    public function testIs_valid_alias_via_rest()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_alias
//     * @todo   Implement testGet_user_alias().
//     */
//    public function testGet_user_alias()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::set_user_alias
//     * @todo   Implement testSet_user_alias().
//     */
//    public function testSet_user_alias()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_detail_from_id
//     * @todo   Implement testGet_user_detail_from_id().
//     */
//    public function testGet_user_detail_from_id()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_detail_from_mobilephone
//     * @todo   Implement testGet_user_detail_from_mobilephone().
//     */
//    public function testGet_user_detail_from_mobilephone()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_detail_from_emailaddress
//     * @todo   Implement testGet_user_detail_from_emailaddress().
//     */
//    public function testGet_user_detail_from_emailaddress()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_profile_privacy_status
//     * @todo   Implement testGet_user_profile_privacy_status().
//     */
//    public function testGet_user_profile_privacy_status()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_contact_detail
//     * @todo   Implement testGet_contact_detail().
//     */
//    public function testGet_contact_detail()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_contact_detail_from_id
//     * @todo   Implement testGet_contact_detail_from_id().
//     */
//    public function testGet_contact_detail_from_id()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_profile
//     * @todo   Implement testGet_user_profile().
//     */
//    public function testGet_user_profile()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_merchant_tag_from_username
//     * @todo   Implement testGet_merchant_tag_from_username().
//     */
//    public function testGet_merchant_tag_from_username()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::like_user
//     * @todo   Implement testLike_user().
//     */
//    public function testLike_user()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::dislike_user
//     * @todo   Implement testDislike_user().
//     */
//    public function testDislike_user()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_likes
//     * @todo   Implement testGet_user_likes().
//     */
//    public function testGet_user_likes()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_displaypicture
//     * @todo   Implement testGet_user_displaypicture().
//     */
//    public function testGet_user_displaypicture()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_account_balance
//     * @todo   Implement testGet_user_account_balance().
//     */
//    public function testGet_user_account_balance()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_contact_list
//     * @todo   Implement testGet_contact_list().
//     */
//    public function testGet_contact_list()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::reset_contact_list_cache
//     * @todo   Implement testReset_contact_list_cache().
//     */
//    public function testReset_contact_list_cache()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_contact_list_mig33_users_only
//     * @todo   Implement testGet_contact_list_mig33_users_only().
//     */
//    public function testGet_contact_list_mig33_users_only()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_contact_list_with_phone_number
//     * @todo   Implement testGet_contact_list_with_phone_number().
//     */
//    public function testGet_contact_list_with_phone_number()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_referral_count
//     * @todo   Implement testGet_user_referral_count().
//     */
//    public function testGet_user_referral_count()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_emoticon_packs
//     * @todo   Implement testGet_emoticon_packs().
//     */
//    public function testGet_emoticon_packs()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_all_friends
//     * @todo   Implement testGet_all_friends().
//     */
//    public function testGet_all_friends()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_friends_id_list_from_username
//     * @todo   Implement testGet_friends_id_list_from_username().
//     */
//    public function testGet_friends_id_list_from_username()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_friends
//     * @todo   Implement testGet_friends().
//     */
//    public function testGet_friends()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_friends_list
//     * @todo   Implement testGet_friends_list().
//     */
//    public function testGet_friends_list()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_mutual_friends_list
//     * @todo   Implement testGet_mutual_friends_list().
//     */
//    public function testGet_mutual_friends_list()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::record_profile_view
//     * @todo   Implement testRecord_profile_view().
//     */
//    public function testRecord_profile_view()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_profile_views
//     * @todo   Implement testGet_profile_views().
//     */
//    public function testGet_profile_views()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_profiles_viewed
//     * @todo   Implement testGet_profiles_viewed().
//     */
//    public function testGet_profiles_viewed()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_num_profile_views
//     * @todo   Implement testGet_num_profile_views().
//     */
//    public function testGet_num_profile_views()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_num_profiles_viewed
//     * @todo   Implement testGet_num_profiles_viewed().
//     */
//    public function testGet_num_profiles_viewed()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::remove_profile_view
//     * @todo   Implement testRemove_profile_view().
//     */
//    public function testRemove_profile_view()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::set_captcha_required
//     * @todo   Implement testSet_captcha_required().
//     */
//    public function testSet_captcha_required()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::is_captcha_required
//     * @todo   Implement testIs_captcha_required().
//     */
//    public function testIs_captcha_required()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_failed_captcha_counter
//     * @todo   Implement testGet_failed_captcha_counter().
//     */
//    public function testGet_failed_captcha_counter()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::increment_failed_captcha_counter
//     * @todo   Implement testIncrement_failed_captcha_counter().
//     */
//    public function testIncrement_failed_captcha_counter()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::remove_captcha_required
//     * @todo   Implement testRemove_captcha_required().
//     */
//    public function testRemove_captcha_required()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::set_user_captcha_odds
//     * @todo   Implement testSet_user_captcha_odds().
//     */
//    public function testSet_user_captcha_odds()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::remove_user_captcha_odds
//     * @todo   Implement testRemove_user_captcha_odds().
//     */
//    public function testRemove_user_captcha_odds()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_captcha_odds
//     * @todo   Implement testGet_user_captcha_odds().
//     */
//    public function testGet_user_captcha_odds()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_avatar_vote_count
//     * @todo   Implement testGet_avatar_vote_count().
//     */
//    public function testGet_avatar_vote_count()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::increment_avatar_vote_count
//     * @todo   Implement testIncrement_avatar_vote_count().
//     */
//    public function testIncrement_avatar_vote_count()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_user_current_avatar_candidate_index
//     * @todo   Implement testGet_user_current_avatar_candidate_index().
//     */
//    public function testGet_user_current_avatar_candidate_index()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::set_user_current_avatar_candidate_index
//     * @todo   Implement testSet_user_current_avatar_candidate_index().
//     */
//    public function testSet_user_current_avatar_candidate_index()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_voters_list
//     * @todo   Implement testGet_voters_list().
//     */
//    public function testGet_voters_list()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_unique_games_played
//     * @todo   Implement testGet_unique_games_played().
//     */
//    public function testGet_unique_games_played()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_bot_details
//     * @todo   Implement testGet_bot_details().
//     */
//    public function testGet_bot_details()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::user_attempted_verification
//     * @todo   Implement testUser_attempted_verification().
//     */
//    public function testUser_attempted_verification()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::is_user_authenticated
//     * @todo   Implement testIs_user_authenticated().
//     */
//    public function testIs_user_authenticated()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers UserDAO::get_mutual_games_played
//     * @todo   Implement testGet_mutual_games_played().
//     */
//    public function testGet_mutual_games_played()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
}
