<?php
require_once "PHPUnit/Extensions/Database/TestCase.php";
fast_require('Memcached', get_framework_common_directory() . '/memcached.php');
fast_require('VoucherDAO', get_dao_directory() . '/voucher_dao.php');
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-16 at 16:49:05.
 */
class VoucherDAOTest extends PHPUnit_Extensions_Database_TestCase
{
    /**
     * @var VoucherDAO
     */
    protected $object;

	/**
     * @return PHPUnit_Extensions_Database_DB_IDatabaseConnection
     */
    public function getConnection()
    {
		$pdo = new PDO($GLOBALS['L_DB_DSN'], $GLOBALS['L_DB_USER'], $GLOBALS['L_DB_PWD']);
		$pdo->exec("set foreign_key_checks = 0;");
		return $this->createDefaultDBConnection($pdo, $GLOBALS['L_DB_NAME']);
    }

	/**
     * @return PHPUnit_Extensions_Database_DataSet_IDataSet
     */
    public function getDataSet()
    {
		global $test_base_dir;
		return $this->createMySQLXMLDataSet($test_base_dir.'/fixtures/frame252.xml');
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		parent::setUp();
		Memcached::get_instance()->flush();
        $this->object = new VoucherDAO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
		$this->getConnection()->getConnection()->exec("set foreign_key_checks = 1;");
		parent::tearDown();
    }

    /**
     * @covers VoucherDAO::is_voucher_owner
     */
    public function testIs_voucher_owner()
    {
		$username = "lesterchan";
		$voucher_number = "7751318034";
        $result = $this->object->is_voucher_owner($username, $voucher_number);
		$this->assertTrue($result);

		$username = "cherrymoo";
        $result = $this->object->is_voucher_owner($username, $voucher_number);
		$this->assertFalse($result);

		$username = "terryboo";
        $result = $this->object->is_voucher_owner($username, $voucher_number);
		$this->assertFalse($result);

		$username = "lesterchan";
		$voucher_number = "77513188888";
        $result = $this->object->is_voucher_owner($username, $voucher_number);
		$this->assertFalse($result);

		$username = "";
		$voucher_number = "7751318034";
        $result = $this->object->is_voucher_owner($username, $voucher_number);
		$this->assertFalse($result);

		$username = "lesterchan";
		$voucher_number = "";
        $result = $this->object->is_voucher_owner($username, $voucher_number);
		$this->assertFalse($result);
    }

    /**
     * @covers VoucherDAO::is_voucher_batch_owner
     */
    public function testIs_voucher_batch_owner()
    {
        $username = "lesterchan";
		$voucher_batch_id = 1;
        $result = $this->object->is_voucher_batch_owner($username, $voucher_batch_id);
		$this->assertTrue($result);

		$username = "cherrymoo";
        $result = $this->object->is_voucher_batch_owner($username, $voucher_batch_id);
		$this->assertFalse($result);
    }

//    /**
//     * @covers VoucherDAO::find_voucher
//     * @todo   Implement testFind_voucher().
//     */
//    public function testFind_voucher()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers VoucherDAO::get_voucher_batches
//     * @todo   Implement testGet_voucher_batches().
//     */
//    public function testGet_voucher_batches()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers VoucherDAO::retrieve_vouchers
//     * @todo   Implement testRetrieve_vouchers().
//     */
//    public function testRetrieve_vouchers()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers VoucherDAO::insert_voucher_batch_record
//     * @todo   Implement testInsert_voucher_batch_record().
//     */
//    public function testInsert_voucher_batch_record()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
}
