package com.projectgoth.fusion.authentication;

import com.projectgoth.fusion.common.SystemPropertyEntities;
import com.projectgoth.fusion.common.ValueEnum;
import com.projectgoth.fusion.fdl.enums.ImType;

public enum PasswordType implements ValueEnum<Byte> {
   FUSION((byte)1),
   MERCHANT((byte)2),
   MAIL((byte)3),
   AIM_IM((byte)10),
   MSN_IM((byte)11),
   GTALK_IM((byte)12),
   YAHOO_IM((byte)13),
   FACEBOOK_IM((byte)14),
   MERCHANT_PIN_NOAUTH((byte)15),
   MERCHANT_PIN_AUTH((byte)16),
   SECURITY_QUESTION((byte)17),
   TWITTER((byte)18);

   public static final byte[] OTHER_IM_TYPES = new byte[]{AIM_IM.value(), MSN_IM.value(), GTALK_IM.value(), YAHOO_IM.value(), FACEBOOK_IM.value(), MERCHANT_PIN_NOAUTH.value(), MERCHANT_PIN_AUTH.value()};
   private final byte value;

   private PasswordType(byte value) {
      this.value = value;
   }

   public Byte value() {
      return this.value;
   }

   public static PasswordType fromValue(byte value) {
      PasswordType[] arr$ = values();
      int len$ = arr$.length;

      for(int i$ = 0; i$ < len$; ++i$) {
         PasswordType e = arr$[i$];
         if (e.value() == value) {
            return e;
         }
      }

      return null;
   }

   public static PasswordType[] fromValues(byte[] values) {
      if (values == null) {
         return null;
      } else if (values.length == 0) {
         return new PasswordType[0];
      } else {
         PasswordType[] passwordTypes = new PasswordType[values.length];
         int index = 0;
         byte[] arr$ = values;
         int len$ = values.length;

         for(int i$ = 0; i$ < len$; ++i$) {
            byte value = arr$[i$];
            if (value >= 1) {
               PasswordType[] arr$ = values();
               int len$ = arr$.length;

               for(int i$ = 0; i$ < len$; ++i$) {
                  PasswordType e = arr$[i$];
                  if (e.value() == value) {
                     passwordTypes[index++] = e;
                     break;
                  }
               }
            }
         }

         return passwordTypes;
      }
   }

   public static PasswordType forIMEnum(ImType imType) {
      if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
         if (imType == null) {
            return null;
         } else {
            switch(imType) {
            case AIM:
               return AIM_IM;
            case FUSION:
               return FUSION;
            case GTALK:
               return GTALK_IM;
            case MSN:
               return MSN_IM;
            case YAHOO:
               return YAHOO_IM;
            case FACEBOOK:
               return FACEBOOK_IM;
            default:
               return null;
            }
         }
      } else if (imType == ImType.AIM) {
         return AIM_IM;
      } else if (imType == ImType.FUSION) {
         return FUSION;
      } else if (imType == ImType.GTALK) {
         return GTALK_IM;
      } else if (imType == ImType.MSN) {
         return MSN_IM;
      } else if (imType == ImType.YAHOO) {
         return YAHOO_IM;
      } else {
         return imType == ImType.FACEBOOK ? FACEBOOK_IM : null;
      }
   }
}
