#!/bin/bash
# docker-entrypoint.sh — Container startup script for Migmechat
# Handles service dependency checks, DB initialization, and application start.

set -e

# ─── Color Output ────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()    { echo -e "${BLUE}[$(date '+%H:%M:%S')]${NC} $*"; }
success(){ echo -e "${GREEN}[$(date '+%H:%M:%S')] ✓${NC} $*"; }
warn()   { echo -e "${YELLOW}[$(date '+%H:%M:%S')] ⚠${NC} $*"; }
error()  { echo -e "${RED}[$(date '+%H:%M:%S')] ✗${NC} $*" >&2; }

# ─── Environment Defaults ────────────────────────────────────────────────────
DB_HOST="${DB_HOST:-mysql}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-fusion}"
DB_USER="${DB_USER:-fusion}"
DB_PASSWORD="${DB_PASSWORD:-fusionpassword}"

MEMCACHE_HOST="${MEMCACHE_HOST:-memcache}"
MEMCACHE_PORT="${MEMCACHE_PORT:-11211}"

ICE_REGISTRY_HOST="${ICE_REGISTRY_HOST:-registry}"
ICE_REGISTRY_PORT="${ICE_REGISTRY_PORT:-10000}"

GATEWAY_TYPE="${GATEWAY_TYPE:-TCP}"
GATEWAY_HOST="${GATEWAY_HOST:-0.0.0.0}"
GATEWAY_PORT="${GATEWAY_PORT:-9119}"

LOG_LEVEL="${LOG_LEVEL:-INFO}"

# ─── Wait for MySQL ───────────────────────────────────────────────────────────
wait_for_mysql() {
    log "Waiting for MySQL at ${DB_HOST}:${DB_PORT}..."
    local retries=30
    until mysqladmin ping -h "${DB_HOST}" -P "${DB_PORT}" \
          -u "${DB_USER}" -p"${DB_PASSWORD}" --silent 2>/dev/null; do
        retries=$((retries - 1))
        if [ "${retries}" -eq 0 ]; then
            error "MySQL did not become available in time. Exiting."
            exit 1
        fi
        log "MySQL not ready, retrying in 3s... (${retries} attempts left)"
        sleep 3
    done
    success "MySQL is ready."
}

# ─── Wait for Memcached ───────────────────────────────────────────────────────
wait_for_memcache() {
    log "Waiting for Memcached at ${MEMCACHE_HOST}:${MEMCACHE_PORT}..."
    local retries=20
    until echo "stats" | nc -w1 "${MEMCACHE_HOST}" "${MEMCACHE_PORT}" \
          | grep -q "uptime" 2>/dev/null; do
        retries=$((retries - 1))
        if [ "${retries}" -eq 0 ]; then
            warn "Memcached not reachable; continuing anyway."
            return
        fi
        log "Memcached not ready, retrying in 2s... (${retries} attempts left)"
        sleep 2
    done
    success "Memcached is ready."
}

# ─── Wait for Ice Registry ────────────────────────────────────────────────────
wait_for_registry() {
    log "Waiting for Ice Registry at ${ICE_REGISTRY_HOST}:${ICE_REGISTRY_PORT}..."
    local retries=20
    until nc -z "${ICE_REGISTRY_HOST}" "${ICE_REGISTRY_PORT}" 2>/dev/null; do
        retries=$((retries - 1))
        if [ "${retries}" -eq 0 ]; then
            warn "Ice Registry not reachable; continuing anyway."
            return
        fi
        log "Registry not ready, retrying in 2s... (${retries} attempts left)"
        sleep 2
    done
    success "Ice Registry is ready."
}

# ─── Initialize Database ──────────────────────────────────────────────────────
init_database() {
    log "Checking if database '${DB_NAME}' is initialized..."
    local table_count
    table_count=$(mysql -h "${DB_HOST}" -P "${DB_PORT}" \
        -u "${DB_USER}" -p"${DB_PASSWORD}" \
        -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${DB_NAME}';" \
        --skip-column-names 2>/dev/null || echo "0")

    if [ "${table_count}" -gt 0 ]; then
        success "Database already initialized (${table_count} tables found)."
        return
    fi

    log "Database is empty. Importing SQL schemas..."
    local sql_dir="/app/sql"

    # Import core schemas in dependency order
    local core_files=(
        "userid.sql"
        "ANC.sql"
        "VAS.sql"
        "store.sql"
        "virtualgifts.sql"
        "badges.sql"
        "Bots.sql"
    )

    for sql_file in "${core_files[@]}"; do
        local full_path="${sql_dir}/${sql_file}"
        if [ -f "${full_path}" ]; then
            log "Importing ${sql_file}..."
            mysql -h "${DB_HOST}" -P "${DB_PORT}" \
                -u "${DB_USER}" -p"${DB_PASSWORD}" \
                "${DB_NAME}" < "${full_path}" 2>/dev/null \
                && success "Imported ${sql_file}" \
                || warn "Failed to import ${sql_file} (may already exist)"
        else
            warn "SQL file not found: ${full_path}"
        fi
    done

    success "Database initialization complete."
}

# ─── Generate Configuration Files ────────────────────────────────────────────
generate_config() {
    log "Generating configuration from environment variables..."

    local config_dir="/app/etc"
    mkdir -p "${config_dir}"

    # Generate database.properties
    cat > "${config_dir}/database.properties" <<EOF
# Auto-generated by docker-entrypoint.sh at $(date)
global.maxIdleTime=300
global.preferredTestQuery=select 1

database.driver=com.mysql.jdbc.Driver
database.jdbcUrl=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?rewriteBatchedStatements=true&characterEncoding=UTF-8
database.username=${DB_USER}
database.password=${DB_PASSWORD}
database.acquireIncrement=1
database.minPoolSize=10
database.maxPoolSize=100
database.initialPoolSize=5
database.acquireRetryAttempts=0
database.acquireRetryDelay=1000
database.breakAfterAcquireFailure=false
database.maxIdleTime=300
database.idleConnectionTestPeriod=120
database.testConnectionOnCheckout=true

archive.database.driver=com.mysql.jdbc.Driver
archive.database.jdbcUrl=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?rewriteBatchedStatements=true
archive.database.username=${DB_USER}
archive.database.password=${DB_PASSWORD}
archive.database.acquireIncrement=1
archive.database.minPoolSize=1
archive.database.maxPoolSize=10
archive.database.initialPoolSize=1
archive.database.acquireRetryAttempts=0
archive.database.acquireRetryDelay=1000
archive.database.breakAfterAcquireFailure=false
archive.database.maxIdleTime=300

memcache.serverList=${MEMCACHE_HOST}:${MEMCACHE_PORT}
memcache.timeout=1000
EOF

    # Generate gateway config
    cat > "${config_dir}/Gateway${GATEWAY_TYPE}.cfg" <<EOF
# Auto-generated by docker-entrypoint.sh at $(date)
GatewayType=${GATEWAY_TYPE}
GatewayHost=${GATEWAY_HOST}
GatewayPort=${GATEWAY_PORT}
Ice.Default.Locator=FusionIceGrid/Locator:tcp -h ${ICE_REGISTRY_HOST} -p ${ICE_REGISTRY_PORT}
Ice.ThreadPool.Server.Size=4
Ice.ThreadPool.Server.SizeMax=20
EOF

    success "Configuration files generated."
}

# ─── Start Application ────────────────────────────────────────────────────────
start_gateway() {
    log "Starting Migmechat Gateway (type: ${GATEWAY_TYPE})..."
    local jar
    jar=$(find /app/target -maxdepth 1 -name 'fusion-*.jar' -not -name '*sources*' | head -1)
    if [ -z "${jar}" ]; then
        jar=$(find /app/target -maxdepth 1 -name '*.jar' -not -name '*sources*' | head -1)
    fi

    if [ -z "${jar}" ]; then
        error "No JAR file found in /app/target. Did the build succeed?"
        exit 1
    fi

    exec java -server \
        -Xmx1536m \
        -Dlog.dir=/app/logs/ \
        -Dconfig.dir=/app/etc/ \
        -Dlog4j.configuration=file:/app/etc/log4j.properties \
        -jar "${jar}" \
        "/app/etc/Gateway${GATEWAY_TYPE}.cfg"
}

start_registry() {
    log "Starting Ice Registry..."
    exec icegridregistry --Ice.Config=/app/etc/Registry.cfg
}

# ─── Main ─────────────────────────────────────────────────────────────────────
main() {
    local cmd="${1:-gateway}"

    case "${cmd}" in
        gateway)
            wait_for_mysql
            wait_for_memcache
            wait_for_registry
            init_database
            generate_config
            start_gateway
            ;;
        registry)
            start_registry
            ;;
        *)
            # Allow custom commands (e.g. bash, sh)
            exec "$@"
            ;;
    esac
}

main "$@"
