/*
 * Decompiled with CFR 0.152.
 */
package com.projectgoth.fusion.authentication;

import com.projectgoth.fusion.common.SystemPropertyEntities;
import com.projectgoth.fusion.common.ValueEnum;
import com.projectgoth.fusion.fdl.enums.ImType;

/*
 * This class specifies class file version 49.0 but uses Java 6 signatures.  Assumed Java 6.
 */
public enum PasswordType implements ValueEnum<Byte>
{
    FUSION(1),
    MERCHANT(2),
    MAIL(3),
    AIM_IM(10),
    MSN_IM(11),
    GTALK_IM(12),
    YAHOO_IM(13),
    FACEBOOK_IM(14),
    MERCHANT_PIN_NOAUTH(15),
    MERCHANT_PIN_AUTH(16),
    SECURITY_QUESTION(17),
    TWITTER(18);

    public static final byte[] OTHER_IM_TYPES;
    private final byte value;

    private PasswordType(byte value) {
        this.value = value;
    }

    @Override
    public Byte value() {
        return this.value;
    }

    public static PasswordType fromValue(byte value) {
        for (PasswordType e : PasswordType.values()) {
            if (e.value() != value) continue;
            return e;
        }
        return null;
    }

    public static PasswordType[] fromValues(byte[] values) {
        if (values == null) {
            return null;
        }
        if (values.length == 0) {
            return new PasswordType[0];
        }
        PasswordType[] passwordTypes = new PasswordType[values.length];
        int index = 0;
        block0: for (byte value : values) {
            if (value < 1) continue;
            for (PasswordType e : PasswordType.values()) {
                if (e.value() != value) continue;
                passwordTypes[index++] = e;
                continue block0;
            }
        }
        return passwordTypes;
    }

    public static PasswordType forIMEnum(ImType imType) {
        if (SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue().booleanValue()) {
            if (imType == null) {
                return null;
            }
            switch (imType) {
                case AIM: {
                    return AIM_IM;
                }
                case FUSION: {
                    return FUSION;
                }
                case GTALK: {
                    return GTALK_IM;
                }
                case MSN: {
                    return MSN_IM;
                }
                case YAHOO: {
                    return YAHOO_IM;
                }
                case FACEBOOK: {
                    return FACEBOOK_IM;
                }
            }
            return null;
        }
        if (imType == ImType.AIM) {
            return AIM_IM;
        }
        if (imType == ImType.FUSION) {
            return FUSION;
        }
        if (imType == ImType.GTALK) {
            return GTALK_IM;
        }
        if (imType == ImType.MSN) {
            return MSN_IM;
        }
        if (imType == ImType.YAHOO) {
            return YAHOO_IM;
        }
        if (imType == ImType.FACEBOOK) {
            return FACEBOOK_IM;
        }
        return null;
    }

    static {
        OTHER_IM_TYPES = new byte[]{AIM_IM.value(), MSN_IM.value(), GTALK_IM.value(), YAHOO_IM.value(), FACEBOOK_IM.value(), MERCHANT_PIN_NOAUTH.value(), MERCHANT_PIN_AUTH.value()};
    }
}

