package com.projectgoth.fusion.chatsync;

import com.projectgoth.fusion.common.ConfigUtils;
import com.projectgoth.fusion.common.LogFilter;
import com.projectgoth.fusion.common.SystemProperty;
import com.projectgoth.fusion.common.SystemPropertyEntities;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktChat;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktChatListVersion;
import com.projectgoth.fusion.gateway.packet.chatsync.FusionPktChatListVersionOld;
import com.projectgoth.fusion.slice.ConnectionPrx;
import com.projectgoth.fusion.slice.FusionException;
import com.projectgoth.fusion.slice.SessionPrx;
import java.util.Iterator;
import org.apache.log4j.Logger;

public class UserMissingChatsPusher extends UserMissingChats {
   private static final LogFilter log;
   private final ConnectionPrx connection;
   private final short transactionId;
   private final String parentUsername;
   private long queueingStartTime;

   public UserMissingChatsPusher(int userID, ConnectionPrx connection, int chatListVersion, Integer limit, Byte chatType, short transactionId, String parentUsername) {
      super(userID, chatListVersion, limit, chatType, connection);
      this.connection = connection;
      this.transactionId = transactionId;
      this.parentUsername = parentUsername;
      this.queueingStartTime = System.currentTimeMillis();
   }

   public void retrieve(ChatSyncStore[] stores) throws FusionException {
      if (SystemProperty.getBool((SystemPropertyEntities.SystemPropertyEntryInterface)SystemPropertyEntities.ChatSyncSettings.WALLCLOCK_TIME_STATS_ENABLED)) {
         ChatSyncStats.getInstance().addGetChatsAsyncQueueingWallclockTime(System.currentTimeMillis() - this.queueingStartTime);
      }

      long startWallclock = System.currentTimeMillis();

      try {
         super.retrieve(stores);
         if (this.missingChatDefs.size() != 0) {
            this.pushMissingChats();
         }
      } finally {
         if (SystemProperty.getBool((SystemPropertyEntities.SystemPropertyEntryInterface)SystemPropertyEntities.ChatSyncSettings.WALLCLOCK_TIME_STATS_ENABLED)) {
            ChatSyncStats.getInstance().addGetChatsAsyncWallclockTime(System.currentTimeMillis() - startWallclock);
         }

      }

   }

   private void pushMissingChats() throws FusionException {
      SessionPrx session = this.connection.getSessionObject();
      if (log.isDebugEnabled()) {
         log.debug("pushMissingChats to session=" + session.getSessionID() + " with desired chatType=" + this.chatType);
      }

      if (log.isDebugEnabled()) {
         log.debug("pushMissingChats: no of chats to push=" + this.missingChatDefs.size());
      }

      if (this.missingChatDefs.size() > 0) {
         long chatListTimestamp = System.currentTimeMillis();
         Iterator i$ = this.missingChatDefs.iterator();

         while(i$.hasNext()) {
            ChatDefinition chatDef = (ChatDefinition)i$.next();

            try {
               if (log.isDebugEnabled()) {
                  log.debug("pushMissingChats: pushing chat id=" + chatDef.getChatID());
               }

               FusionPktChat chat = chatDef.toFusionPktChat(this.transactionId, this.currentChatList.getVersion(), chatListTimestamp, this.parentUsername);
               if (log.isDebugEnabled()) {
                  log.debug("pushMissingChats: converted ChatDefinition to pkt=" + chat);
               }

               this.connection.putSerializedPacket(chat.toSerializedBytes());
            } catch (Exception var7) {
               log.error("Failed to send chat " + chatDef + " to userID=" + this.userID);
            }
         }
      }

      if ((Boolean)SystemPropertyEntities.Temp.Cache.fi83Week2UseAutogeneratedPacketsEnabled.getValue()) {
         FusionPktChatListVersion finished = new FusionPktChatListVersion(this.transactionId);
         finished.setVersion(this.currentChatList.getVersion());
         this.connection.putSerializedPacket(finished.toSerializedBytes());
      } else {
         FusionPktChatListVersionOld finished = new FusionPktChatListVersionOld(this.transactionId);
         finished.setVersion(this.currentChatList.getVersion());
         this.connection.putSerializedPacket(finished.toSerializedBytes());
      }

      session.setChatListVersion(this.currentChatList.getVersion());
      this.setCurrentChatListOnUser(session);
   }

   private void setCurrentChatListOnUser(SessionPrx session) {
      try {
         session.setCurrentChatListGroupChatSubset(this.currentChatList.toIceObject());
      } catch (Exception var3) {
         log.error("Call to setCurrentChatListGroupChatSubset failed for user=" + this.parentUsername + " e=" + var3, var3);
      }

   }

   public boolean canRetryReads() throws FusionException {
      return SystemProperty.getBool((SystemPropertyEntities.SystemPropertyEntryInterface)SystemPropertyEntities.ChatSyncSettings.RETRY_GET_CHATS_ENABLED);
   }

   static {
      log = new LogFilter(Logger.getLogger(ConfigUtils.getLoggerName(UserMissingChatsPusher.class)), SystemPropertyEntities.ChatSyncSettings.LOG_EXCLUSION_FILTER);
   }
}
