CREATE TABLE `userregistration` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Username` varchar(128) NOT NULL DEFAULT '',
  `updatedTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `Password` varchar(128) NOT NULL DEFAULT '',
  `VerificationToken` varchar(64) DEFAULT NULL,
  `CountryID` int(11) DEFAULT NULL,
  `Language` varchar(3) NOT NULL DEFAULT 'ENG',
  `EmailAddress` varchar(128) DEFAULT NULL,
  `RegistrationIPAddress` varchar(128) DEFAULT NULL,
  `RegistrationDevice` varchar(128) DEFAULT NULL,
  `UserAgent` varchar(128) DEFAULT NULL,
  `UTCOffset` double(2,1) DEFAULT NULL,
  `Type` int(11) NOT NULL DEFAULT '0',
  `ReferredBy` varchar(128) DEFAULT NULL,
  `ReferralLevel` int(11) DEFAULT NULL,
  `Currency` varchar(6) NOT NULL,
  `RegistrationType` varchar(10) NOT NULL,
  `MobileDevice` varchar(128) DEFAULT NULL,
  `IMEI` varchar(128) DEFAULT NULL,
  `Verified` int(11) NOT NULL DEFAULT '0',
  `VerificationTime` TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY `id` (`ID`),
  KEY `FK_userReg_countryid` (`CountryID`),
  KEY `FK_userReg_referredby` (`ReferredBy`),
  KEY `FK_userReg_emailaddress` (`emailAddress`),
  KEY `FK_userReg_currency` (`Currency`),
  CONSTRAINT `FK_userReg_countryid` FOREIGN KEY (`CountryID`) REFERENCES `country` (`ID`),
  CONSTRAINT `FK_userReg_referredby` FOREIGN KEY (`ReferredBy`) REFERENCES `user` (`Username`),
  CONSTRAINT `FK_userReg_currency` FOREIGN KEY (`Currency`) REFERENCES `currency` (`Code`),
  INDEX (`Username`),
  INDEX (`updatedTime`),
  INDEX (`VerificationToken`),
  INDEX (`EmailAddress`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
