insert into emoticonpack values( 18, 2, 'Chinese New Year', null, 0.15, 1 );

insert into emoticon values( 532, 18, 'angpow', 12, 12, '/usr/fusion/emoticons/cny/Angpow_12.gif', '/usr/fusion/emoticons/cny/Angpow_12.png' );
insert into emoticon values( 533, 18, 'angpow', 14, 14, '/usr/fusion/emoticons/cny/Angpow_14.gif', '/usr/fusion/emoticons/cny/Angpow_14.png' );
insert into emoticon values( 534, 18, 'angpow', 16, 16, '/usr/fusion/emoticons/cny/Angpow_16.gif', '/usr/fusion/emoticons/cny/Angpow_16.png' );
insert into emoticon values( 535, 18, 'cai', 12, 12, '/usr/fusion/emoticons/cny/Cai_12.gif', '/usr/fusion/emoticons/cny/Cai_12.png' );
insert into emoticon values( 536, 18, 'cai', 14, 14, '/usr/fusion/emoticons/cny/Cai_14.gif', '/usr/fusion/emoticons/cny/Cai_14.png' );
insert into emoticon values( 537, 18, 'cai', 16, 16, '/usr/fusion/emoticons/cny/Cai_16.gif', '/usr/fusion/emoticons/cny/Cai_16.png' );
insert into emoticon values( 538, 18, 'chinesefemale', 12, 12, '/usr/fusion/emoticons/cny/Chinesefemale_12.gif', '/usr/fusion/emoticons/cny/Chinesefemale_12.png' );
insert into emoticon values( 539, 18, 'chinesefemale', 14, 14, '/usr/fusion/emoticons/cny/Chinesefemale_14.gif', '/usr/fusion/emoticons/cny/Chinesefemale_14.png' );
insert into emoticon values( 540, 18, 'chinesefemale', 16, 16, '/usr/fusion/emoticons/cny/Chinesefemale_16.gif', '/usr/fusion/emoticons/cny/Chinesefemale_16.png' );
insert into emoticon values( 541, 18, 'chineseknot', 12, 12, '/usr/fusion/emoticons/cny/Chineseknot_12.gif', '/usr/fusion/emoticons/cny/Chineseknot_12.png' );
insert into emoticon values( 542, 18, 'chineseknot', 14, 14, '/usr/fusion/emoticons/cny/Chineseknot_14.gif', '/usr/fusion/emoticons/cny/Chineseknot_14.png' );
insert into emoticon values( 543, 18, 'chineseknot', 16, 16, '/usr/fusion/emoticons/cny/Chineseknot_16.gif', '/usr/fusion/emoticons/cny/Chineseknot_16.png' );
insert into emoticon values( 544, 18, 'chinesemale', 12, 12, '/usr/fusion/emoticons/cny/Chinesemale_12.gif', '/usr/fusion/emoticons/cny/Chinesemale_12.png' );
insert into emoticon values( 545, 18, 'chinesemale', 14, 14, '/usr/fusion/emoticons/cny/Chinesemale_14.gif', '/usr/fusion/emoticons/cny/Chinesemale_14.png' );
insert into emoticon values( 546, 18, 'chinesemale', 16, 16, '/usr/fusion/emoticons/cny/Chinesemale_16.gif', '/usr/fusion/emoticons/cny/Chinesemale_16.png' );
insert into emoticon values( 547, 18, 'fa', 12, 12, '/usr/fusion/emoticons/cny/Fa_12.gif', '/usr/fusion/emoticons/cny/Fa_12.png' );
insert into emoticon values( 548, 18, 'fa', 14, 14, '/usr/fusion/emoticons/cny/Fa_14.gif', '/usr/fusion/emoticons/cny/Fa_14.png' );
insert into emoticon values( 549, 18, 'fa', 16, 16, '/usr/fusion/emoticons/cny/Fa_16.gif', '/usr/fusion/emoticons/cny/Fa_16.png' );
insert into emoticon values( 550, 18, 'firecracker', 12, 12, '/usr/fusion/emoticons/cny/Firecracker_12.gif', '/usr/fusion/emoticons/cny/Firecracker_12.png' );
insert into emoticon values( 551, 18, 'firecracker', 14, 14, '/usr/fusion/emoticons/cny/Firecracker_14.gif', '/usr/fusion/emoticons/cny/Firecracker_14.png' );
insert into emoticon values( 552, 18, 'firecracker', 16, 16, '/usr/fusion/emoticons/cny/Firecracker_16.gif', '/usr/fusion/emoticons/cny/Firecracker_16.png' );
insert into emoticon values( 553, 18, 'gong', 12, 12, '/usr/fusion/emoticons/cny/Gong_12.gif', '/usr/fusion/emoticons/cny/Gong_12.png' );
insert into emoticon values( 554, 18, 'gong', 14, 14, '/usr/fusion/emoticons/cny/Gong_14.gif', '/usr/fusion/emoticons/cny/Gong_14.png' );
insert into emoticon values( 555, 18, 'gong', 16, 16, '/usr/fusion/emoticons/cny/Gong_16.gif', '/usr/fusion/emoticons/cny/Gong_16.png' );
insert into emoticon values( 556, 18, 'koi', 12, 12, '/usr/fusion/emoticons/cny/Koi_12.gif', '/usr/fusion/emoticons/cny/Koi_12.png' );
insert into emoticon values( 557, 18, 'koi', 14, 14, '/usr/fusion/emoticons/cny/Koi_14.gif', '/usr/fusion/emoticons/cny/Koi_14.png' );
insert into emoticon values( 558, 18, 'koi', 16, 16, '/usr/fusion/emoticons/cny/Koi_16.gif', '/usr/fusion/emoticons/cny/Koi_16.png' );
insert into emoticon values( 559, 18, 'lantern', 12, 12, '/usr/fusion/emoticons/cny/Lantern_12.gif', '/usr/fusion/emoticons/cny/Lantern_12.png' );
insert into emoticon values( 560, 18, 'lantern', 14, 14, '/usr/fusion/emoticons/cny/Lantern_14.gif', '/usr/fusion/emoticons/cny/Lantern_14.png' );
insert into emoticon values( 561, 18, 'lantern', 16, 16, '/usr/fusion/emoticons/cny/Lantern_16.gif', '/usr/fusion/emoticons/cny/Lantern_16.png' );
insert into emoticon values( 562, 18, 'ox', 12, 12, '/usr/fusion/emoticons/cny/Ox_12.gif', '/usr/fusion/emoticons/cny/Ox_12.png' );
insert into emoticon values( 563, 18, 'ox', 14, 14, '/usr/fusion/emoticons/cny/Ox_14.gif', '/usr/fusion/emoticons/cny/Ox_14.png' );
insert into emoticon values( 564, 18, 'ox', 16, 16, '/usr/fusion/emoticons/cny/Ox_16.gif', '/usr/fusion/emoticons/cny/Ox_16.png' );
insert into emoticon values( 565, 18, 'xi', 12, 12, '/usr/fusion/emoticons/cny/Xi_12.gif', '/usr/fusion/emoticons/cny/Xi_12.png' );
insert into emoticon values( 566, 18, 'xi', 14, 14, '/usr/fusion/emoticons/cny/Xi_14.gif', '/usr/fusion/emoticons/cny/Xi_14.png' );
insert into emoticon values( 567, 18, 'xi', 16, 16, '/usr/fusion/emoticons/cny/Xi_16.gif', '/usr/fusion/emoticons/cny/Xi_16.png' );

insert into emoticonhotkey values( 739, 532, 1, '(angpow)' );
insert into emoticonhotkey values( 740, 533, 1, '(angpow)' );
insert into emoticonhotkey values( 741, 534, 1, '(angpow)' );
insert into emoticonhotkey values( 742, 535, 1, '(cai)' );
insert into emoticonhotkey values( 743, 536, 1, '(cai)' );
insert into emoticonhotkey values( 744, 537, 1, '(cai)' );
insert into emoticonhotkey values( 745, 538, 1, '(chinesefemale)' );
insert into emoticonhotkey values( 746, 539, 1, '(chinesefemale)' );
insert into emoticonhotkey values( 747, 540, 1, '(chinesefemale)' );
insert into emoticonhotkey values( 748, 541, 1, '(chineseknot)' );
insert into emoticonhotkey values( 749, 542, 1, '(chineseknot)' );
insert into emoticonhotkey values( 750, 543, 1, '(chineseknot)' );
insert into emoticonhotkey values( 751, 544, 1, '(chinesemale)' );
insert into emoticonhotkey values( 752, 545, 1, '(chinesemale)' );
insert into emoticonhotkey values( 753, 546, 1, '(chinesemale)' );
insert into emoticonhotkey values( 754, 547, 1, '(fa)' );
insert into emoticonhotkey values( 755, 548, 1, '(fa)' );
insert into emoticonhotkey values( 756, 549, 1, '(fa)' );
insert into emoticonhotkey values( 757, 550, 1, '(firecracker)' );
insert into emoticonhotkey values( 758, 551, 1, '(firecracker)' );
insert into emoticonhotkey values( 759, 552, 1, '(firecracker)' );
insert into emoticonhotkey values( 760, 553, 1, '(gong)' );
insert into emoticonhotkey values( 761, 554, 1, '(gong)' );
insert into emoticonhotkey values( 762, 555, 1, '(gong)' );
insert into emoticonhotkey values( 763, 556, 1, '(koi)' );
insert into emoticonhotkey values( 764, 557, 1, '(koi)' );
insert into emoticonhotkey values( 765, 558, 1, '(koi)' );
insert into emoticonhotkey values( 766, 559, 1, '(lantern)' );
insert into emoticonhotkey values( 767, 560, 1, '(lantern)' );
insert into emoticonhotkey values( 768, 561, 1, '(lantern)' );
insert into emoticonhotkey values( 769, 562, 1, '(ox)' );
insert into emoticonhotkey values( 770, 563, 1, '(ox)' );
insert into emoticonhotkey values( 771, 564, 1, '(ox)' );
insert into emoticonhotkey values( 772, 565, 1, '(xi)' );
insert into emoticonhotkey values( 773, 566, 1, '(xi)' );
insert into emoticonhotkey values( 774, 567, 1, '(xi)' );

