insert into virtualgift (name, hotkey, price, currency, numsold, location12x12gif, location12x12png, location14x14gif, location14x14png, location16x16gif, location16x16png, location64x64png, status) values ('4 runs', 'vg_four', 0.05, 'USD', 0, '/usr/fusion/emoticons/virtualgifts/four_12x12.gif',  '/usr/fusion/emoticons/virtualgifts/four_12x12.png', '/usr/fusion/emoticons/virtualgifts/four_14x14.gif','/usr/fusion/emoticons/virtualgifts/four_14x14.png','/usr/fusion/emoticons/virtualgifts/four_16x16.gif','/usr/fusion/emoticons/virtualgifts/four_16x16.png', '/usr/fusion/emoticons/virtualgifts/four_64x64.png', 1);

insert into virtualgift (name, hotkey, price, currency, numsold, location12x12gif, location12x12png, location14x14gif, location14x14png, location16x16gif, location16x16png, location64x64png, status) values ('6 runs', 'vg_six', 0.10, 'USD', 0, '/usr/fusion/emoticons/virtualgifts/six_12x12.gif',  '/usr/fusion/emoticons/virtualgifts/six_12x12.png', '/usr/fusion/emoticons/virtualgifts/six_14x14.gif','/usr/fusion/emoticons/virtualgifts/six_14x14.png','/usr/fusion/emoticons/virtualgifts/six_16x16.gif','/usr/fusion/emoticons/virtualgifts/six_16x16.png', '/usr/fusion/emoticons/virtualgifts/six_64x64.png', 1);

insert into virtualgift (name, hotkey, price, currency, numsold, location12x12gif, location12x12png, location14x14gif, location14x14png, location16x16gif, location16x16png, location64x64png, status) values ('Ball', 'vg_ball', 0.05, 'USD', 0, '/usr/fusion/emoticons/virtualgifts/ball_12x12.gif',  '/usr/fusion/emoticons/virtualgifts/ball_12x12.png', '/usr/fusion/emoticons/virtualgifts/ball_14x14.gif','/usr/fusion/emoticons/virtualgifts/ball_14x14.png','/usr/fusion/emoticons/virtualgifts/ball_16x16.gif','/usr/fusion/emoticons/virtualgifts/ball_16x16.png', '/usr/fusion/emoticons/virtualgifts/ball_64x64.png', 1);

insert into virtualgift (name, hotkey, price, currency, numsold, location12x12gif, location12x12png, location14x14gif, location14x14png, location16x16gif, location16x16png, location64x64png, status) values ('Bat', 'vg_bat', 0.20, 'USD', 0, '/usr/fusion/emoticons/virtualgifts/bat_12x12.gif',  '/usr/fusion/emoticons/virtualgifts/bat_12x12.png', '/usr/fusion/emoticons/virtualgifts/bat_14x14.gif','/usr/fusion/emoticons/virtualgifts/bat_14x14.png','/usr/fusion/emoticons/virtualgifts/bat_16x16.gif','/usr/fusion/emoticons/virtualgifts/bat_16x16.png', '/usr/fusion/emoticons/virtualgifts/bat_64x64.png', 1);

insert into virtualgift (name, hotkey, price, currency, numsold, location12x12gif, location12x12png, location14x14gif, location14x14png, location16x16gif, location16x16png, location64x64png, status) values ('Batsman', 'vg_batsman', 0.15, 'USD', 0, '/usr/fusion/emoticons/virtualgifts/batsman_12x12.gif',  '/usr/fusion/emoticons/virtualgifts/batsman_12x12.png', '/usr/fusion/emoticons/virtualgifts/batsman_14x14.gif','/usr/fusion/emoticons/virtualgifts/batsman_14x14.png','/usr/fusion/emoticons/virtualgifts/batsman_16x16.gif','/usr/fusion/emoticons/virtualgifts/batsman_16x16.png', '/usr/fusion/emoticons/virtualgifts/batsman_64x64.png', 1);

insert into virtualgift (name, hotkey, price, currency, numsold, location12x12gif, location12x12png, location14x14gif, location14x14png, location16x16gif, location16x16png, location64x64png, status) values ('Bowler', 'vg_bowler', 0.15, 'USD', 0, '/usr/fusion/emoticons/virtualgifts/bowler_12x12.gif',  '/usr/fusion/emoticons/virtualgifts/bowler_12x12.png', '/usr/fusion/emoticons/virtualgifts/bowler_14x14.gif','/usr/fusion/emoticons/virtualgifts/bowler_14x14.png','/usr/fusion/emoticons/virtualgifts/bowler_16x16.gif','/usr/fusion/emoticons/virtualgifts/bowler_16x16.png', '/usr/fusion/emoticons/virtualgifts/bowler_64x64.png', 1);

insert into virtualgift (name, hotkey, price, currency, numsold, location12x12gif, location12x12png, location14x14gif, location14x14png, location16x16gif, location16x16png, location64x64png, status) values ('Helmet', 'vg_helmet', 0.20, 'USD', 0, '/usr/fusion/emoticons/virtualgifts/helmet_12x12.gif',  '/usr/fusion/emoticons/virtualgifts/helmet_12x12.png', '/usr/fusion/emoticons/virtualgifts/helmet_14x14.gif','/usr/fusion/emoticons/virtualgifts/helmet_14x14.png','/usr/fusion/emoticons/virtualgifts/helmet_16x16.gif','/usr/fusion/emoticons/virtualgifts/helmet_16x16.png', '/usr/fusion/emoticons/virtualgifts/helmet_64x64.png', 1);

insert into virtualgift (name, hotkey, price, currency, numsold, location12x12gif, location12x12png, location14x14gif, location14x14png, location16x16gif, location16x16png, location64x64png, status) values ('Stump', 'vg_stump', 0.15, 'USD', 0, '/usr/fusion/emoticons/virtualgifts/stump_12x12.gif',  '/usr/fusion/emoticons/virtualgifts/stump_12x12.png', '/usr/fusion/emoticons/virtualgifts/stump_14x14.gif','/usr/fusion/emoticons/virtualgifts/stump_14x14.png','/usr/fusion/emoticons/virtualgifts/stump_16x16.gif','/usr/fusion/emoticons/virtualgifts/stump_16x16.png', '/usr/fusion/emoticons/virtualgifts/stump_64x64.png', 1);

insert into virtualgift (name, hotkey, price, currency, numsold, location12x12gif, location12x12png, location14x14gif, location14x14png, location16x16gif, location16x16png, location64x64png, status) values ('Trophy', 'vg_trophy', 1.00, 'USD', 0, '/usr/fusion/emoticons/virtualgifts/trophy_12x12.gif',  '/usr/fusion/emoticons/virtualgifts/trophy_12x12.png', '/usr/fusion/emoticons/virtualgifts/trophy_14x14.gif','/usr/fusion/emoticons/virtualgifts/trophy_14x14.png','/usr/fusion/emoticons/virtualgifts/trophy_16x16.gif','/usr/fusion/emoticons/virtualgifts/trophy_16x16.png', '/usr/fusion/emoticons/virtualgifts/trophy_64x64.png', 1);

insert into virtualgift (name, hotkey, price, currency, numsold, location12x12gif, location12x12png, location14x14gif, location14x14png, location16x16gif, location16x16png, location64x64png, status) values ('Umpire', 'vg_umpire', 0.10, 'USD', 0, '/usr/fusion/emoticons/virtualgifts/umpire_12x12.gif',  '/usr/fusion/emoticons/virtualgifts/umpire_12x12.png', '/usr/fusion/emoticons/virtualgifts/umpire_14x14.gif','/usr/fusion/emoticons/virtualgifts/umpire_14x14.png','/usr/fusion/emoticons/virtualgifts/umpire_16x16.gif','/usr/fusion/emoticons/virtualgifts/umpire_16x16.png', '/usr/fusion/emoticons/virtualgifts/umpire_64x64.png', 1);