insert into emoticonpack values( 21, 2, '   Cricket', null, 0.18, 1 );

insert into emoticon values( 628, 21, '4s', 12, 12, '/usr/fusion/emoticons/cricket/4s_12.gif', '/usr/fusion/emoticons/cricket/4s_12.png' );
insert into emoticon values( 629, 21, '4s', 14, 14, '/usr/fusion/emoticons/cricket/4s_14.gif', '/usr/fusion/emoticons/cricket/4s_14.png' );
insert into emoticon values( 630, 21, '4s', 16, 16, '/usr/fusion/emoticons/cricket/4s_16.gif', '/usr/fusion/emoticons/cricket/4s_16.png' );
insert into emoticon values( 631, 21, '6s', 12, 12, '/usr/fusion/emoticons/cricket/6s_12.gif', '/usr/fusion/emoticons/cricket/6s_12.png' );
insert into emoticon values( 632, 21, '6s', 14, 14, '/usr/fusion/emoticons/cricket/6s_14.gif', '/usr/fusion/emoticons/cricket/6s_14.png' );
insert into emoticon values( 633, 21, '6s', 16, 16, '/usr/fusion/emoticons/cricket/6s_16.gif', '/usr/fusion/emoticons/cricket/6s_16.png' );
insert into emoticon values( 634, 21, 'bat-or-little-batter', 12, 12, '/usr/fusion/emoticons/cricket/Bat-or-little-batter_12.gif', '/usr/fusion/emoticons/cricket/Bat-or-little-batter_12.png' );
insert into emoticon values( 635, 21, 'bat-or-little-batter', 14, 14, '/usr/fusion/emoticons/cricket/Bat-or-little-batter_14.gif', '/usr/fusion/emoticons/cricket/Bat-or-little-batter_14.png' );
insert into emoticon values( 636, 21, 'bat-or-little-batter', 16, 16, '/usr/fusion/emoticons/cricket/Bat-or-little-batter_16.gif', '/usr/fusion/emoticons/cricket/Bat-or-little-batter_16.png' );
insert into emoticon values( 637, 21, 'bowled-wicket', 12, 12, '/usr/fusion/emoticons/cricket/Bowled-Wicket_12.gif', '/usr/fusion/emoticons/cricket/Bowled-Wicket_12.png' );
insert into emoticon values( 638, 21, 'bowled-wicket', 14, 14, '/usr/fusion/emoticons/cricket/Bowled-Wicket_14.gif', '/usr/fusion/emoticons/cricket/Bowled-Wicket_14.png' );
insert into emoticon values( 639, 21, 'bowled-wicket', 16, 16, '/usr/fusion/emoticons/cricket/Bowled-Wicket_16.gif', '/usr/fusion/emoticons/cricket/Bowled-Wicket_16.png' );
insert into emoticon values( 640, 21, 'cricket-uniform', 12, 12, '/usr/fusion/emoticons/cricket/Cricket-Uniform_12.gif', '/usr/fusion/emoticons/cricket/Cricket-Uniform_12.png' );
insert into emoticon values( 641, 21, 'cricket-uniform', 14, 14, '/usr/fusion/emoticons/cricket/Cricket-Uniform_14.gif', '/usr/fusion/emoticons/cricket/Cricket-Uniform_14.png' );
insert into emoticon values( 642, 21, 'cricket-uniform', 16, 16, '/usr/fusion/emoticons/cricket/Cricket-Uniform_16.gif', '/usr/fusion/emoticons/cricket/Cricket-Uniform_16.png' );
insert into emoticon values( 643, 21, 'cricket-ball', 12, 12, '/usr/fusion/emoticons/cricket/Cricket-ball_12.gif', '/usr/fusion/emoticons/cricket/Cricket-ball_12.png' );
insert into emoticon values( 644, 21, 'cricket-ball', 14, 14, '/usr/fusion/emoticons/cricket/Cricket-ball_14.gif', '/usr/fusion/emoticons/cricket/Cricket-ball_14.png' );
insert into emoticon values( 645, 21, 'cricket-ball', 16, 16, '/usr/fusion/emoticons/cricket/Cricket-ball_16.gif', '/usr/fusion/emoticons/cricket/Cricket-ball_16.png' );
insert into emoticon values( 646, 21, 'cricket-helmet', 12, 12, '/usr/fusion/emoticons/cricket/Cricket-helmet_12.gif', '/usr/fusion/emoticons/cricket/Cricket-helmet_12.png' );
insert into emoticon values( 647, 21, 'cricket-helmet', 14, 14, '/usr/fusion/emoticons/cricket/Cricket-helmet_14.gif', '/usr/fusion/emoticons/cricket/Cricket-helmet_14.png' );
insert into emoticon values( 648, 21, 'cricket-helmet', 16, 16, '/usr/fusion/emoticons/cricket/Cricket-helmet_16.gif', '/usr/fusion/emoticons/cricket/Cricket-helmet_16.png' );
insert into emoticon values( 649, 21, 'setup-wicket', 12, 12, '/usr/fusion/emoticons/cricket/Setup-Wicket_12.gif', '/usr/fusion/emoticons/cricket/Setup-Wicket_12.png' );
insert into emoticon values( 650, 21, 'setup-wicket', 14, 14, '/usr/fusion/emoticons/cricket/Setup-Wicket_14.gif', '/usr/fusion/emoticons/cricket/Setup-Wicket_14.png' );
insert into emoticon values( 651, 21, 'setup-wicket', 16, 16, '/usr/fusion/emoticons/cricket/Setup-Wicket_16.gif', '/usr/fusion/emoticons/cricket/Setup-Wicket_16.png' );

insert into emoticonhotkey values( 835, 628, 1, '(4s)' );
insert into emoticonhotkey values( 836, 629, 1, '(4s)' );
insert into emoticonhotkey values( 837, 630, 1, '(4s)' );
insert into emoticonhotkey values( 838, 631, 1, '(6s)' );
insert into emoticonhotkey values( 839, 632, 1, '(6s)' );
insert into emoticonhotkey values( 840, 633, 1, '(6s)' );
insert into emoticonhotkey values( 841, 634, 1, '(bat-or-little-batter)' );
insert into emoticonhotkey values( 842, 635, 1, '(bat-or-little-batter)' );
insert into emoticonhotkey values( 843, 636, 1, '(bat-or-little-batter)' );
insert into emoticonhotkey values( 844, 637, 1, '(bowled-wicket)' );
insert into emoticonhotkey values( 845, 638, 1, '(bowled-wicket)' );
insert into emoticonhotkey values( 846, 639, 1, '(bowled-wicket)' );
insert into emoticonhotkey values( 847, 640, 1, '(cricket-uniform)' );
insert into emoticonhotkey values( 848, 641, 1, '(cricket-uniform)' );
insert into emoticonhotkey values( 849, 642, 1, '(cricket-uniform)' );
insert into emoticonhotkey values( 850, 643, 1, '(cricket-ball)' );
insert into emoticonhotkey values( 851, 644, 1, '(cricket-ball)' );
insert into emoticonhotkey values( 852, 645, 1, '(cricket-ball)' );
insert into emoticonhotkey values( 853, 646, 1, '(cricket-helmet)' );
insert into emoticonhotkey values( 854, 647, 1, '(cricket-helmet)' );
insert into emoticonhotkey values( 855, 648, 1, '(cricket-helmet)' );
insert into emoticonhotkey values( 856, 649, 1, '(setup-wicket)' );
insert into emoticonhotkey values( 857, 650, 1, '(setup-wicket)' );
insert into emoticonhotkey values( 858, 651, 1, '(setup-wicket)' );
