insert into emoticonpack values( 20, 2, 'Earth Day', null, 0.50, 1 );

insert into emoticon values( 598, 20, 'blueskies', 12, 12, '/usr/fusion/emoticons/earthday/Blueskies_12.gif', '/usr/fusion/emoticons/earthday/Blueskies_12.png' );
insert into emoticon values( 599, 20, 'blueskies', 14, 14, '/usr/fusion/emoticons/earthday/Blueskies_14.gif', '/usr/fusion/emoticons/earthday/Blueskies_14.png' );
insert into emoticon values( 600, 20, 'blueskies', 16, 16, '/usr/fusion/emoticons/earthday/Blueskies_16.gif', '/usr/fusion/emoticons/earthday/Blueskies_16.png' );
insert into emoticon values( 601, 20, 'earthday2009', 12, 12, '/usr/fusion/emoticons/earthday/EarthDay2009_12.gif', '/usr/fusion/emoticons/earthday/EarthDay2009_12.png' );
insert into emoticon values( 602, 20, 'earthday2009', 14, 14, '/usr/fusion/emoticons/earthday/EarthDay2009_14.gif', '/usr/fusion/emoticons/earthday/EarthDay2009_14.png' );
insert into emoticon values( 603, 20, 'earthday2009', 16, 16, '/usr/fusion/emoticons/earthday/EarthDay2009_16.gif', '/usr/fusion/emoticons/earthday/EarthDay2009_16.png' );
insert into emoticon values( 604, 20, 'earth', 12, 12, '/usr/fusion/emoticons/earthday/Earth_12.gif', '/usr/fusion/emoticons/earthday/Earth_12.png' );
insert into emoticon values( 605, 20, 'earth', 14, 14, '/usr/fusion/emoticons/earthday/Earth_14.gif', '/usr/fusion/emoticons/earthday/Earth_14.png' );
insert into emoticon values( 606, 20, 'earth', 16, 16, '/usr/fusion/emoticons/earthday/Earth_16.gif', '/usr/fusion/emoticons/earthday/Earth_16.png' );
insert into emoticon values( 607, 20, 'greentree', 12, 12, '/usr/fusion/emoticons/earthday/GreenTree_12.gif', '/usr/fusion/emoticons/earthday/GreenTree_12.png' );
insert into emoticon values( 608, 20, 'greentree', 14, 14, '/usr/fusion/emoticons/earthday/GreenTree_14.gif', '/usr/fusion/emoticons/earthday/GreenTree_14.png' );
insert into emoticon values( 609, 20, 'greentree', 16, 16, '/usr/fusion/emoticons/earthday/GreenTree_16.gif', '/usr/fusion/emoticons/earthday/GreenTree_16.png' );
insert into emoticon values( 610, 20, 'greenthumb', 12, 12, '/usr/fusion/emoticons/earthday/Greenthumb_12.gif', '/usr/fusion/emoticons/earthday/Greenthumb_12.png' );
insert into emoticon values( 611, 20, 'greenthumb', 14, 14, '/usr/fusion/emoticons/earthday/Greenthumb_14.gif', '/usr/fusion/emoticons/earthday/Greenthumb_14.png' );
insert into emoticon values( 612, 20, 'greenthumb', 16, 16, '/usr/fusion/emoticons/earthday/Greenthumb_16.gif', '/usr/fusion/emoticons/earthday/Greenthumb_16.png' );
insert into emoticon values( 613, 20, 'happysun', 12, 12, '/usr/fusion/emoticons/earthday/HappySun_12.gif', '/usr/fusion/emoticons/earthday/HappySun_12.png' );
insert into emoticon values( 614, 20, 'happysun', 14, 14, '/usr/fusion/emoticons/earthday/HappySun_14.gif', '/usr/fusion/emoticons/earthday/HappySun_14.png' );
insert into emoticon values( 615, 20, 'happysun', 16, 16, '/usr/fusion/emoticons/earthday/HappySun_16.gif', '/usr/fusion/emoticons/earthday/HappySun_16.png' );
insert into emoticon values( 616, 20, 'lightsoff', 12, 12, '/usr/fusion/emoticons/earthday/Lightsoff_12.gif', '/usr/fusion/emoticons/earthday/Lightsoff_12.png' );
insert into emoticon values( 617, 20, 'lightsoff', 14, 14, '/usr/fusion/emoticons/earthday/Lightsoff_14.gif', '/usr/fusion/emoticons/earthday/Lightsoff_14.png' );
insert into emoticon values( 618, 20, 'lightsoff', 16, 16, '/usr/fusion/emoticons/earthday/Lightsoff_16.gif', '/usr/fusion/emoticons/earthday/Lightsoff_16.png' );
insert into emoticon values( 619, 20, 'pollution', 12, 12, '/usr/fusion/emoticons/earthday/Pollution_12.gif', '/usr/fusion/emoticons/earthday/Pollution_12.png' );
insert into emoticon values( 620, 20, 'pollution', 14, 14, '/usr/fusion/emoticons/earthday/Pollution_14.gif', '/usr/fusion/emoticons/earthday/Pollution_14.png' );
insert into emoticon values( 621, 20, 'pollution', 16, 16, '/usr/fusion/emoticons/earthday/Pollution_16.gif', '/usr/fusion/emoticons/earthday/Pollution_16.png' );
insert into emoticon values( 622, 20, 'recycle', 12, 12, '/usr/fusion/emoticons/earthday/Recycle_12.gif', '/usr/fusion/emoticons/earthday/Recycle_12.png' );
insert into emoticon values( 623, 20, 'recycle', 14, 14, '/usr/fusion/emoticons/earthday/Recycle_14.gif', '/usr/fusion/emoticons/earthday/Recycle_14.png' );
insert into emoticon values( 624, 20, 'recycle', 16, 16, '/usr/fusion/emoticons/earthday/Recycle_16.gif', '/usr/fusion/emoticons/earthday/Recycle_16.png' );
insert into emoticon values( 625, 20, 'sunflower', 12, 12, '/usr/fusion/emoticons/earthday/Sunflower_12.gif', '/usr/fusion/emoticons/earthday/Sunflower_12.png' );
insert into emoticon values( 626, 20, 'sunflower', 14, 14, '/usr/fusion/emoticons/earthday/Sunflower_14.gif', '/usr/fusion/emoticons/earthday/Sunflower_14.png' );
insert into emoticon values( 627, 20, 'sunflower', 16, 16, '/usr/fusion/emoticons/earthday/Sunflower_16.gif', '/usr/fusion/emoticons/earthday/Sunflower_16.png' );

insert into emoticonhotkey values( 805, 598, 1, '(blueskies)' );
insert into emoticonhotkey values( 806, 599, 1, '(blueskies)' );
insert into emoticonhotkey values( 807, 600, 1, '(blueskies)' );
insert into emoticonhotkey values( 808, 601, 1, '(earthday2009)' );
insert into emoticonhotkey values( 809, 602, 1, '(earthday2009)' );
insert into emoticonhotkey values( 810, 603, 1, '(earthday2009)' );
insert into emoticonhotkey values( 811, 604, 1, '(earth)' );
insert into emoticonhotkey values( 812, 605, 1, '(earth)' );
insert into emoticonhotkey values( 813, 606, 1, '(earth)' );
insert into emoticonhotkey values( 814, 607, 1, '(greentree)' );
insert into emoticonhotkey values( 815, 608, 1, '(greentree)' );
insert into emoticonhotkey values( 816, 609, 1, '(greentree)' );
insert into emoticonhotkey values( 817, 610, 1, '(greenthumb)' );
insert into emoticonhotkey values( 818, 611, 1, '(greenthumb)' );
insert into emoticonhotkey values( 819, 612, 1, '(greenthumb)' );
insert into emoticonhotkey values( 820, 613, 1, '(happysun)' );
insert into emoticonhotkey values( 821, 614, 1, '(happysun)' );
insert into emoticonhotkey values( 822, 615, 1, '(happysun)' );
insert into emoticonhotkey values( 823, 616, 1, '(lightsoff)' );
insert into emoticonhotkey values( 824, 617, 1, '(lightsoff)' );
insert into emoticonhotkey values( 825, 618, 1, '(lightsoff)' );
insert into emoticonhotkey values( 826, 619, 1, '(pollution)' );
insert into emoticonhotkey values( 827, 620, 1, '(pollution)' );
insert into emoticonhotkey values( 828, 621, 1, '(pollution)' );
insert into emoticonhotkey values( 829, 622, 1, '(recycle)' );
insert into emoticonhotkey values( 830, 623, 1, '(recycle)' );
insert into emoticonhotkey values( 831, 624, 1, '(recycle)' );
insert into emoticonhotkey values( 832, 625, 1, '(sunflower)' );
insert into emoticonhotkey values( 833, 626, 1, '(sunflower)' );
insert into emoticonhotkey values( 834, 627, 1, '(sunflower)' );

