insert into contentcategory values (49, 'Bambi', 2);

insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (49, 2, 2, 'Bambi Neon Spring', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/bambi/bambi-neon-spring_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/bambi/bambi-neon-spring_40x40.jpg', 53750, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (49, 2, 2, 'Bambi Frolics In The Summer Flowers', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/bambi/bambi-frolics-in-the-summer-flowers_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/bambi/bambi-frolics-in-the-summer-flowers_40x40.jpg', 53771, 1);



insert into contentcategory values (48, 'Cartoon', 2);

insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (48, 2, 2, 'Anak Jawa Bendera', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoon/anak-jawa-bendera_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoon/anak-jawa-bendera_40x40.jpg', 53807, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (48, 2, 2, 'Thumper Plays the Butterfly', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoon/thumper-plays-the-butterfly_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoon/thumper-plays-the-butterfly_40x40.jpg', 53766, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (48, 2, 2, 'Wolf Dagger', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoon/wolf-dagger_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoon/wolf-dagger_40x40.jpg', 53795, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (48, 2, 2, 'Pressed Pete', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoon/pressed-pete_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoon/pressed-pete_40x40.jpg', 53800, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (48, 2, 2, 'Samba Jose', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoon/samba-jose_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoon/samba-jose_40x40.jpg', 53801, 1);



insert into contentcategory values (54, 'Cartoon, Indonesia', 2);

insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Blankon', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/blankon_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/blankon_40x40.jpg', 53804, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Merdeka', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/merdeka_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/merdeka_40x40.jpg', 53805, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Anak Pantai', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/anak-pantai_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/anak-pantai_40x40.jpg', 53808, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Merdeka', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/ela00004_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/ela00004_40x40.jpg', 53809, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Golfield and Scooter', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/golfield-and-scooter_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/golfield-and-scooter_40x40.jpg', 53810, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Liburan', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/liburan_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/liburan_40x40.jpg', 53811, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Love Sambal', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/love-sambal_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/love-sambal_40x40.jpg', 53812, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Merdeka Merah Putih', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/merdeka-merah-putih_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/merdeka-merah-putih_40x40.jpg', 53813, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Sweet Blondie', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/sweet-blondie_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/sweet-blondie_40x40.jpg', 53814, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Valentine''s Cupid', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/valentines-cupid_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/valentines-cupid_40x40.jpg', 53802, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Cupids In Love', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/cupids-in-love_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/cupids-in-love_40x40.jpg', 53803, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (54, 2, 2, 'Valentine''s Day', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/cartoonindo/valentines-day_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/cartoonindo/valentines-day_40x40.jpg', 53806, 1);



insert into contentcategory values (50, 'Disney On Ice', 2);


insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (50, 2, 2, 'Simba & Pumbaa are Skating Buddies', 107, 1.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyonice/simba-and-pumbaa-are-skating-buddies_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyonice/simba-and-pumbaa-are-skating-buddies_40x40.jpg', 53732, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (50, 2, 2, 'Lilo & Stitch Show Their Dancing', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyonice/lilo-and-stitch-show-their-dancing_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyonice/lilo-and-stitch-show-their-dancing_40x40.jpg', 53733, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (50, 2, 2, 'The Little Mermaid', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyonice/the-little-mermaid_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyonice/the-little-mermaid_40x40.jpg', 53734, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (50, 2, 2, 'Tinker Bell: Skating Diva', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyonice/tinker-bell-skating-diva_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyonice/tinker-bell-skating-diva_40x40.jpg', 53735, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (50, 2, 2, 'Dalmatian Skating Derby', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyonice/dalmatian-skating-derby_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyonice/dalmatian-skating-derby_40x40.jpg', 53737, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (50, 2, 2, 'Flying High With Mickey & Minnie', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyonice/flying-high-with-mickey-and-minnie_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyonice/flying-high-with-mickey-and-minnie_40x40.jpg', 53738, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (50, 2, 2, 'Eric & Ariel Make a Cute Skating Duet', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyonice/eric-and-ariel-make-a-cute-skating-duet_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyonice/eric-and-ariel-make-a-cute-skating-duet_40x40.jpg', 53736, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (50, 2, 2, 'Mickey & Minnie Skating a Duet', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyonice/mickey-and-minnie-skating-a-duet_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyonice/mickey-and-minnie-skating-a-duet_40x40.jpg', 53739, 1);



insert into contentcategory values (51, 'Disney Princess', 2);

insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (51, 2, 2, 'Aurora Is Wistful', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyprincess/aurora-is-wistful_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyprincess/aurora-is-wistful_40x40.jpg', 53740, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (51, 2, 2, 'Aurora Is Daydreaming About her Prince', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyprincess/aurora-is-daydreaming-about-her-prince_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyprincess/aurora-is-daydreaming-about-her-prince_40x40.jpg', 53741, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (51, 2, 2, 'Three Princesses All In A Row', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyprincess/three-princesses-all-in-a-row_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyprincess/three-princesses-all-in-a-row_40x40.jpg', 53742, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (51, 2, 2, 'Snow White: Who Me?', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyprincess/snow-white-who-me_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyprincess/snow-white-who-me_40x40.jpg', 53743, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (51, 2, 2, 'Jasmine Is Her Own Woman', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyprincess/jasmine-is-her-own-woman_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyprincess/jasmine-is-her-own-woman_40x40.jpg', 53744, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (51, 2, 2, 'Aurora Is Being Mischievous', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyprincess/aurora-is-being-mischievous_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyprincess/aurora-is-being-mischievous_40x40.jpg', 53745, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (51, 2, 2, 'Not Just Your Average Princesses', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyprincess/not-just-your-average-princesses_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyprincess/not-just-your-average-princesses_40x40.jpg', 53746, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (51, 2, 2, 'Ariel Has Eric On Her Mind', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyprincess/ariel-has-eric-on-her-mind_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyprincess/ariel-has-eric-on-her-mind_40x40.jpg', 53747, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (51, 2, 2, 'The Girls Are Ready to Be Wooed', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyprincess/the-girls-are-ready-to-be-wooed_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyprincess/the-girls-are-ready-to-be-wooed_40x40.jpg', 53748, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (51, 2, 2, 'Belle is Thinking About the Beast', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneyprincess/belle-is-thinking-about-the-beast_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneyprincess/belle-is-thinking-about-the-beast_40x40.jpg', 53749, 1);



insert into contentcategory values (52, 'Disney Sports', 2);

insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (52, 2, 2, 'Donald: Skateboard King Of the Beach', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneysports/donald-skateboard-king-of-the-beach_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneysports/donald-skateboard-king-of-the-beach_40x40.jpg', 53767, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (52, 2, 2, 'Tigger Rips The Wave', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneysports/tigger-rips-the-wave_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneysports/tigger-rips-the-wave_40x40.jpg', 53768, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (52, 2, 2, 'Mickey: Surf King of the Beach', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneysports/mickey-surf-king-of-the-beach_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneysports/mickey-surf-king-of-the-beach_40x40.jpg', 53769, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (52, 2, 2, 'Mickey Balances and Goals!', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneysports/mickey-balances-and-goals!_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneysports/mickey-balances-and-goals!_40x40.jpg', 53787, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (52, 2, 2, 'Mickey Swings', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneysports/mickey-swings_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneysports/mickey-swings_40x40.jpg', 53788, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (52, 2, 2, 'Mickey Road Bikes', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneysports/mickey-road-bikes_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneysports/mickey-road-bikes_40x40.jpg', 53789, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (52, 2, 2, 'Mickey Water Skis', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneysports/mickey-water-skis_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneysports/mickey-water-skis_40x40.jpg', 53790, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (52, 2, 2, 'MickeyFriends', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneysports/mickeyfriends_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneysports/mickeyfriends_40x40.jpg', 53791, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (52, 2, 2, 'FragmentsMickey', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/disneysports/fragmentsmickey_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/disneysports/fragmentsmickey_40x40.jpg', 53792, 1);



insert into contentcategory values (55, 'Mickey & Friends', 2);

insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Daisy Social Butterfly', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/daisy-social-butterfly_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/daisy-social-butterfly_40x40.jpg', 53751, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Donald Abstract', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/donald-abstract_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/donald-abstract_40x40.jpg', 53752, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Mickey Salutes Spring', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-salutes-spring_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-salutes-spring_40x40.jpg', 53754, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Mickey''s Blue Period', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickeys-blue-period_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickeys-blue-period_40x40.jpg', 53755, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Mickey Loves Summer Time', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-loves-summer-time_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-loves-summer-time_40x40.jpg', 53770, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Minnie''s Tropical Vacation', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/minnies-tropical-vacation_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/minnies-tropical-vacation_40x40.jpg', 53773, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Mickey Shows His Skater Moves', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-shows-his-skater-moves_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-shows-his-skater-moves_40x40.jpg', 53774, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Mickey''s Got An Attitude', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickeys-got-an-attitude_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickeys-got-an-attitude_40x40.jpg', 53775, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Big Bad Wolf Is Busting Through', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/big-bad-wolf-is-busting-through_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/big-bad-wolf-is-busting-through_40x40.jpg', 53776, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Mickey Crashes the Gate', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-crashes-the-gate_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-crashes-the-gate_40x40.jpg', 53777, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Donald Jumps a Stunt Cone', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/donald-jumps-a-stunt-cone_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/donald-jumps-a-stunt-cone_40x40.jpg', 53778, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Donald Is Up To The Challenge', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/donald-is-up-to-the-challenge_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/donald-is-up-to-the-challenge_40x40.jpg', 53779, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Homie The Duck', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/homie-the-duck_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/homie-the-duck_40x40.jpg', 53780, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Mickey: Attitude? Who Me?', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-attitude-who-me_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-attitude-who-me_40x40.jpg', 53781, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Boogie Down With Donald & Mickey', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/boogie-down-with-donald-and-mickey_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/boogie-down-with-donald-and-mickey_40x40.jpg', 53782, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Lucky Mickey', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/lucky-mickey_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/lucky-mickey_40x40.jpg', 53793, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Cool Pete', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/cool-pete_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/cool-pete_40x40.jpg', 53794, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Mickey Saves', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-saves_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/mickey-saves_40x40.jpg', 53796, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Tantrum Donald', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/tantrum-donald_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/tantrum-donald_40x40.jpg', 53797, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (55, 2, 2, 'Rokin Mickey', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/mickeyandfriends/rokin-mickey_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/mickeyandfriends/rokin-mickey_40x40.jpg', 53799, 1);



insert into contentcategory values (56, 'Phantom Duck, Action', 2);

insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (56, 2, 2, 'PK Is Ready for Battle', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/phantomduck/pk-is-ready-for-battle_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/phantomduck/pk-is-ready-for-battle_40x40.jpg', 53783, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (56, 2, 2, 'PK Takes The Battle To Them!', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/phantomduck/pk-takes-the-battle-to-them!_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/phantomduck/pk-takes-the-battle-to-them!_40x40.jpg', 53784, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (56, 2, 2, 'PK Saves The Earth Again', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/phantomduck/pk-saves-the-earth-again_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/phantomduck/pk-saves-the-earth-again_40x40.jpg', 53785, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (56, 2, 2, 'Evronian General With An Attitude', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/phantomduck/evronian-general-with-an-attitude_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/phantomduck/evronian-general-with-an-attitude_40x40.jpg', 53786, 1);



insert into contentcategory values (57, 'Winnie The Pooh', 2);

insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Pooh Fall Down', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-fall-down_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-fall-down_40x40.jpg', 53756, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Pooh & Eeyore Hugs', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-eeyore-hugs_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-eeyore-hugs_40x40.jpg', 53757, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Pooh & Piglet Cutouts', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-piglet-cutouts_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-piglet-cutouts_40x40.jpg', 53758, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Pooh & Roo Playing House', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-roo-playing-house_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-roo-playing-house_40x40.jpg', 53759, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Pooh & Friends Spring Portrait', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-friends-spring-portrait_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-friends-spring-portrait_40x40.jpg', 53760, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Pooh & Piglet Spring in Their Step', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-piglet-spring-in-their-step_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-piglet-spring-in-their-step_40x40.jpg', 53761, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Pooh So Happy', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-so-happy_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-so-happy_40x40.jpg', 53762, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Pooh & Piglet Jumping for Spring', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-piglet-jumping-for-spring_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-piglet-jumping-for-spring_40x40.jpg', 53763, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Pooh & Piglet Jumping for Spring', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-piglet-jumping-for-spring_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-piglet-jumping-for-spring_40x40.jpg', 53764, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Pooh & Tigger Paddycake', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-tigger-paddycake_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-tigger-paddycake_40x40.jpg', 53765, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Pooh & Eeyore: What To Do?', 107, 1.750, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-eeyore-what-to-do_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/pooh-and-eeyore-what-to-do_40x40.jpg', 53772, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, '1966 Eeyore', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/1966-eeyore_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/1966-eeyore_40x40.jpg', 53798, 1);
insert into content (contentcategoryid, contentproviderid, type, name, countryid,price, currency, wholesalecost, wholesalecostcurrency, preview, previewwidth, previewheight, thumbnail, providerid, status) values (57, 2, 2, 'Eeyore''s Heart Seat', 107, 3.000, 'IDR', 0, 'IDR', 'http://www.mig33.com/img/mobile_content/winniethepooh/eeyores-heart-seat_128x128.jpg', 128, 128, 'http://www.mig33.com/img/mobile_content/winniethepooh/eeyores-heart-seat_40x40.jpg', 53753, 1);

