insert into emoticonpack values( 17, 2, 'New Year Pack', null, 0.15, 1 );

insert into emoticon values( 502, 17, '2009', 12, 12, '/usr/fusion/emoticons/newyear/2009_12.gif', '/usr/fusion/emoticons/newyear/2009_12.png' );
insert into emoticon values( 503, 17, '2009', 14, 14, '/usr/fusion/emoticons/newyear/2009_14.gif', '/usr/fusion/emoticons/newyear/2009_14.png' );
insert into emoticon values( 504, 17, '2009', 16, 16, '/usr/fusion/emoticons/newyear/2009_16.gif', '/usr/fusion/emoticons/newyear/2009_16.png' );
insert into emoticon values( 505, 17, 'balloons', 12, 12, '/usr/fusion/emoticons/newyear/Balloons_12.gif', '/usr/fusion/emoticons/newyear/Balloons_12.png' );
insert into emoticon values( 506, 17, 'balloons', 14, 14, '/usr/fusion/emoticons/newyear/Balloons_14.gif', '/usr/fusion/emoticons/newyear/Balloons_14.png' );
insert into emoticon values( 507, 17, 'balloons', 16, 16, '/usr/fusion/emoticons/newyear/Balloons_16.gif', '/usr/fusion/emoticons/newyear/Balloons_16.png' );
insert into emoticon values( 508, 17, 'blower', 12, 12, '/usr/fusion/emoticons/newyear/Blower_12.gif', '/usr/fusion/emoticons/newyear/Blower_12.png' );
insert into emoticon values( 509, 17, 'blower', 14, 14, '/usr/fusion/emoticons/newyear/Blower_14.gif', '/usr/fusion/emoticons/newyear/Blower_14.png' );
insert into emoticon values( 510, 17, 'blower', 16, 16, '/usr/fusion/emoticons/newyear/Blower_16.gif', '/usr/fusion/emoticons/newyear/Blower_16.png' );
insert into emoticon values( 511, 17, 'champagne', 12, 12, '/usr/fusion/emoticons/newyear/Champagne_12.gif', '/usr/fusion/emoticons/newyear/Champagne_12.png' );
insert into emoticon values( 512, 17, 'champagne', 14, 14, '/usr/fusion/emoticons/newyear/Champagne_14.gif', '/usr/fusion/emoticons/newyear/Champagne_14.png' );
insert into emoticon values( 513, 17, 'champagne', 16, 16, '/usr/fusion/emoticons/newyear/Champagne_16.gif', '/usr/fusion/emoticons/newyear/Champagne_16.png' );
insert into emoticon values( 514, 17, 'crackers', 12, 12, '/usr/fusion/emoticons/newyear/Crackers_12.gif', '/usr/fusion/emoticons/newyear/Crackers_12.png' );
insert into emoticon values( 515, 17, 'crackers', 14, 14, '/usr/fusion/emoticons/newyear/Crackers_14.gif', '/usr/fusion/emoticons/newyear/Crackers_14.png' );
insert into emoticon values( 516, 17, 'crackers', 16, 16, '/usr/fusion/emoticons/newyear/Crackers_16.gif', '/usr/fusion/emoticons/newyear/Crackers_16.png' );
insert into emoticon values( 517, 17, 'discoball', 12, 12, '/usr/fusion/emoticons/newyear/Discoball_12.gif', '/usr/fusion/emoticons/newyear/Discoball_12.png' );
insert into emoticon values( 518, 17, 'discoball', 14, 14, '/usr/fusion/emoticons/newyear/Discoball_14.gif', '/usr/fusion/emoticons/newyear/Discoball_14.png' );
insert into emoticon values( 519, 17, 'discoball', 16, 16, '/usr/fusion/emoticons/newyear/Discoball_16.gif', '/usr/fusion/emoticons/newyear/Discoball_16.png' );
insert into emoticon values( 520, 17, '09fireworks', 12, 12, '/usr/fusion/emoticons/newyear/Fireworks_12.gif', '/usr/fusion/emoticons/newyear/Fireworks_12.png' );
insert into emoticon values( 521, 17, '09fireworks', 14, 14, '/usr/fusion/emoticons/newyear/Fireworks_14.gif', '/usr/fusion/emoticons/newyear/Fireworks_14.png' );
insert into emoticon values( 522, 17, '09fireworks', 16, 16, '/usr/fusion/emoticons/newyear/Fireworks_16.gif', '/usr/fusion/emoticons/newyear/Fireworks_16.png' );
insert into emoticon values( 523, 17, 'glasses', 12, 12, '/usr/fusion/emoticons/newyear/Glasses_12.gif', '/usr/fusion/emoticons/newyear/Glasses_12.png' );
insert into emoticon values( 524, 17, 'glasses', 14, 14, '/usr/fusion/emoticons/newyear/Glasses_14.gif', '/usr/fusion/emoticons/newyear/Glasses_14.png' );
insert into emoticon values( 525, 17, 'glasses', 16, 16, '/usr/fusion/emoticons/newyear/Glasses_16.gif', '/usr/fusion/emoticons/newyear/Glasses_16.png' );
insert into emoticon values( 526, 17, 'midnight', 12, 12, '/usr/fusion/emoticons/newyear/Midnight_12.gif', '/usr/fusion/emoticons/newyear/Midnight_12.png' );
insert into emoticon values( 527, 17, 'midnight', 14, 14, '/usr/fusion/emoticons/newyear/Midnight_14.gif', '/usr/fusion/emoticons/newyear/Midnight_14.png' );
insert into emoticon values( 528, 17, 'midnight', 16, 16, '/usr/fusion/emoticons/newyear/Midnight_16.gif', '/usr/fusion/emoticons/newyear/Midnight_16.png' );
insert into emoticon values( 529, 17, 'newyear', 12, 12, '/usr/fusion/emoticons/newyear/NewYear_12.gif', '/usr/fusion/emoticons/newyear/NewYear_12.png' );
insert into emoticon values( 530, 17, 'newyear', 14, 14, '/usr/fusion/emoticons/newyear/NewYear_14.gif', '/usr/fusion/emoticons/newyear/NewYear_14.png' );
insert into emoticon values( 531, 17, 'newyear', 16, 16, '/usr/fusion/emoticons/newyear/NewYear_16.gif', '/usr/fusion/emoticons/newyear/NewYear_16.png' );

insert into emoticonhotkey values( 709, 502, 1, '(2009)' );
insert into emoticonhotkey values( 710, 503, 1, '(2009)' );
insert into emoticonhotkey values( 711, 504, 1, '(2009)' );
insert into emoticonhotkey values( 712, 505, 1, '(balloons)' );
insert into emoticonhotkey values( 713, 506, 1, '(balloons)' );
insert into emoticonhotkey values( 714, 507, 1, '(balloons)' );
insert into emoticonhotkey values( 715, 508, 1, '(blower)' );
insert into emoticonhotkey values( 716, 509, 1, '(blower)' );
insert into emoticonhotkey values( 717, 510, 1, '(blower)' );
insert into emoticonhotkey values( 718, 511, 1, '(champagne)' );
insert into emoticonhotkey values( 719, 512, 1, '(champagne)' );
insert into emoticonhotkey values( 720, 513, 1, '(champagne)' );
insert into emoticonhotkey values( 721, 514, 1, '(crackers)' );
insert into emoticonhotkey values( 722, 515, 1, '(crackers)' );
insert into emoticonhotkey values( 723, 516, 1, '(crackers)' );
insert into emoticonhotkey values( 724, 517, 1, '(discoball)' );
insert into emoticonhotkey values( 725, 518, 1, '(discoball)' );
insert into emoticonhotkey values( 726, 519, 1, '(discoball)' );
insert into emoticonhotkey values( 727, 520, 1, '(09fireworks)' );
insert into emoticonhotkey values( 728, 521, 1, '(09fireworks)' );
insert into emoticonhotkey values( 729, 522, 1, '(09fireworks)' );
insert into emoticonhotkey values( 730, 523, 1, '(glasses)' );
insert into emoticonhotkey values( 731, 524, 1, '(glasses)' );
insert into emoticonhotkey values( 732, 525, 1, '(glasses)' );
insert into emoticonhotkey values( 733, 526, 1, '(midnight)' );
insert into emoticonhotkey values( 734, 527, 1, '(midnight)' );
insert into emoticonhotkey values( 735, 528, 1, '(midnight)' );
insert into emoticonhotkey values( 736, 529, 1, '(newyear)' );
insert into emoticonhotkey values( 737, 530, 1, '(newyear)' );
insert into emoticonhotkey values( 738, 531, 1, '(newyear)' );
