CREATE TABLE `virtualgift` (
  `ID` int(11) NOT NULL auto_increment,
  `Name` varchar(128) default NULL,
  `HotKey` varchar(128) default NULL,
  `Price` double NOT NULL,
  `Currency` varchar(6) NOT NULL,
  `NumAvailable` int(11) NULL,
  `NumSold` int(11) NOT NULL default 0,
  `Location12x12GIF` varchar(128) default NULL,
  `Location12x12PNG` varchar(128) default NULL,
  `Location14x14GIF` varchar(128) default NULL,
  `Location14x14PNG` varchar(128) default NULL,
  `Location16x16GIF` varchar(128) default NULL,
  `Location16x16PNG` varchar(128) default NULL,
  `Status` int(11) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `virtualgiftreceived` (
  `ID` int(11) NOT NULL auto_increment,
  `Username` varchar(128) NOT NULL,
  `DateCreated` datetime NOT NULL,
  `VirtualGiftID` int(11) NOT NULL,
  `Sender` varchar(128) NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `FK_VirtualGiftID` (`VirtualGiftID`),
  KEY `FK_Username` (`Username`),
  KEY `FK_Sender` (`Sender`),
  CONSTRAINT `VirtualGiftID` FOREIGN KEY (`VirtualGiftID`) REFERENCES `virtualgift` (`ID`),
  CONSTRAINT `Username` FOREIGN KEY (`Username`) REFERENCES `user` (`Username`),
  CONSTRAINT `Sender` FOREIGN KEY (`Sender`) REFERENCES `user` (`Username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO virtualgift VALUES
(1, 'Fortune Cookie', 'vg_fortunecookie', 0.03, 'USD', NULL, 0,
'/usr/fusion/emoticons/virtualgifts/fortunecookie_12x12.gif',
'/usr/fusion/emoticons/virtualgifts/fortunecookie_12x12.png',
'/usr/fusion/emoticons/virtualgifts/fortunecookie_14x14.gif',
'/usr/fusion/emoticons/virtualgifts/fortunecookie_14x14.png',
'/usr/fusion/emoticons/virtualgifts/fortunecookie_16x16.gif',
'/usr/fusion/emoticons/virtualgifts/fortunecookie_16x16.png', 1),
(2, 'Kiss', 'vg_kiss', 0.05, 'USD', NULL, 0,
'/usr/fusion/emoticons/virtualgifts/kiss_12x12.gif',
'/usr/fusion/emoticons/virtualgifts/kiss_12x12.png',
'/usr/fusion/emoticons/virtualgifts/kiss_14x14.gif',
'/usr/fusion/emoticons/virtualgifts/kiss_14x14.png',
'/usr/fusion/emoticons/virtualgifts/kiss_16x16.gif',
'/usr/fusion/emoticons/virtualgifts/kiss_16x16.png', 1),
(3, 'Hug', 'vg_hug', 0.05, 'USD', NULL, 0,
'/usr/fusion/emoticons/virtualgifts/hug_12x12.gif',
'/usr/fusion/emoticons/virtualgifts/hug_12x12.png',
'/usr/fusion/emoticons/virtualgifts/hug_14x14.gif',
'/usr/fusion/emoticons/virtualgifts/hug_14x14.png',
'/usr/fusion/emoticons/virtualgifts/hug_16x16.gif',
'/usr/fusion/emoticons/virtualgifts/hug_16x16.png', 1),
(4, 'Flower', 'vg_flower', 0.10, 'USD', NULL, 0,
'/usr/fusion/emoticons/virtualgifts/flower_12x12.gif',
'/usr/fusion/emoticons/virtualgifts/flower_12x12.png',
'/usr/fusion/emoticons/virtualgifts/flower_14x14.gif',
'/usr/fusion/emoticons/virtualgifts/flower_14x14.png',
'/usr/fusion/emoticons/virtualgifts/flower_16x16.gif',
'/usr/fusion/emoticons/virtualgifts/flower_16x16.png', 1),
(5, 'Cake', 'vg_cake', 0.10, 'USD', NULL, 0,
'/usr/fusion/emoticons/virtualgifts/cake_12x12.gif',
'/usr/fusion/emoticons/virtualgifts/cake_12x12.png',
'/usr/fusion/emoticons/virtualgifts/cake_14x14.gif',
'/usr/fusion/emoticons/virtualgifts/cake_14x14.png',
'/usr/fusion/emoticons/virtualgifts/cake_16x16.gif',
'/usr/fusion/emoticons/virtualgifts/cake_16x16.png', 1),
(6, 'Cocktail', 'vg_cocktail', 0.15, 'USD', NULL, 0,
'/usr/fusion/emoticons/virtualgifts/cocktail_12x12.gif',
'/usr/fusion/emoticons/virtualgifts/cocktail_12x12.png',
'/usr/fusion/emoticons/virtualgifts/cocktail_14x14.gif',
'/usr/fusion/emoticons/virtualgifts/cocktail_14x14.png',
'/usr/fusion/emoticons/virtualgifts/cocktail_16x16.gif',
'/usr/fusion/emoticons/virtualgifts/cocktail_16x16.png', 1),
(7, 'Heart', 'vg_heart', 0.25, 'USD', NULL, 0,
'/usr/fusion/emoticons/virtualgifts/heart_12x12.gif',
'/usr/fusion/emoticons/virtualgifts/heart_12x12.png',
'/usr/fusion/emoticons/virtualgifts/heart_14x14.gif',
'/usr/fusion/emoticons/virtualgifts/heart_14x14.png',
'/usr/fusion/emoticons/virtualgifts/heart_16x16.gif',
'/usr/fusion/emoticons/virtualgifts/heart_16x16.png', 1),
(8, 'Ice Cream', 'vg_icecream', 0.30, 'USD', NULL, 0,
'/usr/fusion/emoticons/virtualgifts/icecream_12x12.gif',
'/usr/fusion/emoticons/virtualgifts/icecream_12x12.png',
'/usr/fusion/emoticons/virtualgifts/icecream_14x14.gif',
'/usr/fusion/emoticons/virtualgifts/icecream_14x14.png',
'/usr/fusion/emoticons/virtualgifts/icecream_16x16.gif',
'/usr/fusion/emoticons/virtualgifts/icecream_16x16.png', 1),
(9, 'Champagne Toast', 'vg_champagne', 0.50, 'USD', NULL, 0,
'/usr/fusion/emoticons/virtualgifts/champagne_12x12.gif',
'/usr/fusion/emoticons/virtualgifts/champagne_12x12.png',
'/usr/fusion/emoticons/virtualgifts/champagne_14x14.gif',
'/usr/fusion/emoticons/virtualgifts/champagne_14x14.png',
'/usr/fusion/emoticons/virtualgifts/champagne_16x16.gif',
'/usr/fusion/emoticons/virtualgifts/champagne_16x16.png', 1),
(10, 'Teddy Bear', 'vg_teddybear', 1.00, 'USD', NULL, 0,
'/usr/fusion/emoticons/virtualgifts/teddybear_12x12.gif',
'/usr/fusion/emoticons/virtualgifts/teddybear_12x12.png',
'/usr/fusion/emoticons/virtualgifts/teddybear_14x14.gif',
'/usr/fusion/emoticons/virtualgifts/teddybear_14x14.png',
'/usr/fusion/emoticons/virtualgifts/teddybear_16x16.gif',
'/usr/fusion/emoticons/virtualgifts/teddybear_16x16.png', 1),
(11, 'Diamond', 'vg_diamond', 2.00, 'USD', NULL, 0,
'/usr/fusion/emoticons/virtualgifts/diamond_12x12.gif',
'/usr/fusion/emoticons/virtualgifts/diamond_12x12.png',
'/usr/fusion/emoticons/virtualgifts/diamond_14x14.gif',
'/usr/fusion/emoticons/virtualgifts/diamond_14x14.png',
'/usr/fusion/emoticons/virtualgifts/diamond_16x16.gif',
'/usr/fusion/emoticons/virtualgifts/diamond_16x16.png', 1);
