<?php
fast_require('Memcached', get_framework_common_directory() . '/memcached.php');

//Memcache Settings - specified in base.php
$memcache_servers = array(
	'common'  => array("localhost"=>11221),
	'captcha' => array("localhost"=>11221)
);

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-14 at 13:32:34.
 */
class MemcachedTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Memcached
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = Memcached::get_instance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
		$this->object->flush();
    }

    /**
     * @covers Memcached::get_instance
     */
    public function testGet_instance()
    {
		$result = Memcached::get_instance('invalidinstance');
		$this->assertNull($result);
		$this->assertInstanceOf('Memcached', $this->object);

		$result = Memcached::get_instance();
		$this->assertEquals($this->object, $result);
    }

    /**
     * @covers Memcached::get_memcache_full_key
     */
    public function testGet_memcache_full_key()
    {
		$result = Memcached::get_memcache_full_key('dummy', 'boo');
		$this->assertEquals('dummy/boo', $result);
    }

	/**
     * @covers Memcached::item_exists
     */
    public function testItem_exists()
    {
		$key = "dummy/foo";
        $result = $this->object->item_exists($key);
		$this->assertFalse($result);
		
		$this->object->set($key, 'blah');
		$result = $this->object->item_exists($key);
		$this->assertTrue($result);
    }

    /**
     * @covers Memcached::add_or_update
     */
    public function testAdd_or_update()
    {
		$key = "dummy/moo";
		$data = "Tim is gay";
		$data2 = "Tim is really gay";
		$this->object->add_or_update($key, $data);
		$result = $this->object->get($key);
		$this->assertEquals($data, $result);
		
		$this->object->add_or_update($key, $data2);
		$result = $this->object->get($key);
		$this->assertEquals($data2, $result);
    }

    /**
     * @covers Memcached::increment_key_counter
     */
    public function testIncrement_key_counter()
    {
		$key = "dummy/floo";
		$value = 20;
        $this->object->add_or_update($key, $value);
		$this->object->increment_key_counter($key);
		$result = $this->object->get($key);
		$this->assertEquals(21, $result);
    }

    /**
     * @covers Memcached::decrement_key_counter
     */
    public function testDecrement_key_counter()
    {
        $key = "dummy/floo";
		$value = 20;
        $this->object->add_or_update($key, $value);
		$this->object->decrement_key_counter($key);
		$result = $this->object->get($key);
		$this->assertEquals(19, $result);
    }

    /**
     * @covers Memcached::remove_item
     */
    public function testRemove_item()
    {
		$key = "dummy/invalid_foo";
        $result = $this->object->remove_item($key);
		$this->assertFalse($result);

		$key2 = "dummy/floo";
		$value = "Terrible dumbasses";
		$this->object->add_or_update($key2, $value);
		$result = $this->object->remove_item($key2);
		$this->assertTrue($result);
    }

    /**
     * @covers Memcached::get_distributed_lock
     */
    public function testGet_distributed_lock()
    {
		$key = 'boo';
		$this->object->get_distributed_lock($key, 1);
		$result = $this->object->item_exists(Memcached::$KEYSPACE_DISTRIBUTED_LOCK.$key);
		$this->assertTrue($result);

		$this->object->get_distributed_lock($key, 1);
		$result = $this->object->item_exists(Memcached::$KEYSPACE_DISTRIBUTED_LOCK.$key);
		$this->assertTrue($result);
    }

    /**
     * @covers Memcached::release_distributed_lock
     */
    public function testRelease_distributed_lock()
    {
		$key = 'bam';
		$this->object->get_distributed_lock($key);
		$result = $this->object->item_exists(Memcached::$KEYSPACE_DISTRIBUTED_LOCK.$key);
		$this->assertTrue($result);

		$this->object->release_distributed_lock($key);
		$result = $this->object->item_exists(Memcached::$KEYSPACE_DISTRIBUTED_LOCK.$key);
		$this->assertFalse($result);
    }
}
