<?php
$pageTitle = "";
$pageType = "terms";
$globalNavSelected = "";
$headTitle = "Terms and Conditions";
$metaDescription = "mig33 Terms and Conditions";
$metaKeywords = "terms and conditions";
include("includes_corporate/html_head.php");
?>
<body>

<div id="terms" class="pageContainer">

<?php include("includes_corporate/page_header.php"); ?>

<div id="pageContent" class="container_16">
    <div id="content">
        <div class="grid_16">
            <h2>Terms and Conditions</h2>

            <h4>1. USE REQUIREMENTS AND RESTRICTIONS</h4>
            <p>PLEASE READ THESE USE REQUIREMENTS AND RESTRICTIONS CAREFULLY.  BY ACCESSING OR USING THE MIG33 WEB SITE, SOFTWARE OR SERVICES, YOU AGREE TO BE BOUND BY THE USE REQUIREMENTS AND RESTRICTIONS DESCRIBED HEREIN AND ALL TERMS INCORPORATED BY REFERENCE.  IF YOU DO NOT AGREE WITH ALL OF THE USE REQUIREMENTS AND RESTRICTIONS DESCRIBED HEREIN, DO NOT USE THE MIG33 WEB SITE, SOFTWARE OR SERVICES.</p>
            <p>These Use Requirements and Restrictions (this "<strong>Agreement</strong>") apply to: (a) your access to, and use of, the Web site of Project Goth, Inc. ("<strong>Company</strong>", "<strong>we</strong>", or "<strong>our</strong>"), located at <a href="http://www.mig33.com">www.mig33.com</a> (the "<strong>Site</strong>"); (b) the services provided by Company; and (c) the software provided by the Company.  This Agreement does not alter in any way the terms or conditions of any other agreement you may have with Company.  If you are using the Site, the mig33 services or the mig33 software on behalf of any entity, you represent and warrant that you are authorized to accept the terms and conditions set forth in this Agreement on such entity's behalf, and that such entity agrees to indemnify you and Company for violations of this Agreement.</p>
			<p>Company reserves the right to change or modify any of the terms and conditions contained in this Agreement, at any time and in its sole discretion.  Any changes or modification will be effective immediately upon posting of the revisions on the Site, and you waive any right you may have to receive specific notice of such changes or modifications.  Your continued use of this Site, the mig33 software or the mig33 services following the posting of changes or modifications will confirm your acceptance of such changes or modifications.  Therefore, you should frequently review this Agreement and applicable policies from time-to-time to understand the terms and conditions that apply to your use of the Site.  If you do not agree to the amended terms, you must stop using the Site, the mig33 software and the mig33 services.</p>
			<p><strong>1.1. Services Provided.</strong>  Subject to the terms and conditions of this Agreement, we may provide you with the Site, as well as with certain connectivity software and services as may be made available by us from time to time.</p>
			<p><strong>1.2. Requirements.</strong>  You acknowledge that: (a) in order to use the mig33 software and services you must have a mobile phone that is compatible with our services (refer to www.mig33.com for details); (b) you are responsible for ensuring that suitable wireless coverage for data transmission services is available in the area(s) in which you intend to use the services; and (c) the availability and performance of the mig33 software and services is dependent on the memory, storage and other limitations of your mobile phone as well as the quality and speed of your connection with your wireless carrier.</p>
			<p><strong>1.3. Prohibited Actions.</strong>  You shall comply with all applicable laws and regulations and refrain from violating any third-party rights in connection with this Agreement.  Without limiting the generality of the foregoing, you must not: (a) use the Site, mig33 software or mig33 services to, or in any way that would, violate any applicable law or regulation, any contract (including, but not limited to, wireless service contracts), or any other third-party rights; (b) violate, interfere with, damage or compromise the Site , mig33 software or mig33 service, or any other person's copy of the mig33 software or their mobile phone; (c) remove any proprietary notices from the mig33 software or any copies thereof; (d) cause, permit or authorize the modification, creation of derivative works, translation or copying of the mig33 software; (e) sell, sublicense, assign, rent, lease, act as a service bureau or grant rights in the Site, mig33 software or mig33 services to any other person except with our prior written consent and/or pursuant to the provisions of Section 5 regarding our Merchant Program; (f) decompile, disassemble, reverse engineer or hack the Site or the mig33 software, or circumvent any encryption, technical protection or security methods implemented by us with respect to the Site or mig33 software and/or data transmitted, processed or stored by us or by other users, except to the extent expressly permitted by mandatory provisions of applicable law that cannot be contractually derogated from, but then only with 30 days' prior written notice to us; (g) engage in any form of credit farming (i.e., the process of aggregating credits by signing on multiple user accounts that are really all for you or just one user); or (h) attempt to do anything or induce or enable others to do or attempt to do anything prohibited by this Section 1.3.</p>
			<p><strong>1.4. Prohibited Content.</strong>  Without limiting the generality of Section 1.3 hereof, you must not use, or knowingly or negligently allow any other person to use, the Site, the mig33 software or the mig33 services to develop, generate, transmit or store information that: (a) infringes any person's intellectual property or other proprietary rights; (b) is defamatory, harmful, abusive, obscene or hateful; (c) in any way obstructs or otherwise interferes with the normal performance of another person's use of the Web site, software or service; (d) is an unsolicited commercial communication not permitted by law; (e) constitutes harassment, nuisance or a violation of privacy or threatens anyone; (f) impersonates any other person, or steals or assumes any person's identity (whether a real identity or online nickname or alias); (g) is prohibited under applicable law; or (h) may jeopardize the operation of a cellular or related network or knowingly or negligently allow any other person to do so.  We assume no liability for the content of any message or any other communication or response submitted by you or any other person through our services or otherwise and you shall indemnify and hold harmless us and our affiliates, related bodies corporate, officers, directors, employees, agents and service providers (collectively, our "<strong>Related Parties</strong>") from any loss or damage we or our Related Parties may suffer as a result of such message, communication or response.  We reserve the right, but are under no obligation, to monitor content transmitted through our Web site, software, or service, and reserve the right to prevent transmission of content that we deem illegal, infringing or otherwise inappropriate.</p>
			<h4>2. ACCOUNTS</h4>
			<p><strong>2.1. Account Tied to Mobile Number.</strong>  The account you are opening by accepting this Agreement is tied to the mobile phone number you enter during the sign-up process.  If your mobile phone number changes, you must establish a new account in order to enable you to use the mig33 services from that new number.  Your account is not transferable between mobile phone numbers.</p>
			<p><strong>2.2. Credits.</strong>  You can load credits onto your account through any of the accepted payment methods described on <a href="http://www.mig33.com">www.mig33.com</a>.  Credits are used to pay for the charges described in Section 3.  <strong>Credits are non-refundable and cannot be converted into or redeemed for cash.</strong></p>
			<p><strong>2.3. Credit Expiration.</strong>  Any credit balance in your account that has aged 90 days or more from the date of acquisition will expire.</p>
			<p><strong>2.4. Users with Several Accounts.</strong>  If you breach any of the terms or conditions set forth in this Agreement and you have more than one account with us, we may, at our sole discretion, suspend or terminate all of your accounts.  If you are in arrears in payment of any of your accounts, we may recover any amounts outstanding on any of your accounts from any of your other accounts that have credit balances.</p>
			<p><strong>2.5. Updating Information. </strong> You must notify us of any change in your address or other details you supply us.  I f we ask you for information about you or your account for the purpose of operating the mig33 service, you must provide it to us.</p>

            <h4>3. CHARGES AND PAYMENT</h4>
			<p><strong>3.1. mig33 Charges.</strong>  Our price list (which may be updated from time to time) is available on <a href="http://www.mig33.com">www.mig33.com</a> and contains all charges for the mig33 services.  You are responsible for all charges on your mig33 account, regardless of whether or not they were incurred by you personally, unless you can demonstrate that the charges were incurred by an unauthorized person after you have requested that we suspend your account due to loss or theft of your mobile phone and/or account information and we have confirmed, in writing, that we have processed your request.</p>
			<p><strong>3.2. Negative Balances.</strong>  In order to use our services, your account must have a sufficient credit balance.  If you have a negative balance on your account due to credit card chargebacks or for any other reason, we may, at our sole discretion, either send you a bill for your use of our services or deduct the amount owed from your credit balance when you next recharge your account or from the credit balance on any other account held by you.  In the interim, we may suspend your account.  Interest on any late payments will accrue at the rate of one and one-half percent (1.5%) per month, or the highest rate permitted by law, whichever is lower, from the date such amount is due until finally paid.  Further, if we send you a bill and you do not pay the bill by the due date, we may immediately terminate your use of any of our services or software pursuant to Section 10.  You agree to reimburse us for any costs we incur in recovering any overdue amounts from you. </p>
			<p><strong>3.3. Wireless Carrier Charges.</strong>  In addition to any mig33 charges, you are responsible for any payments to your wireless carrier to enable you to use our services and/or any charges by your wireless carrier resulting from the use of our services.</p>
			<p><strong>3.4. Taxes.</strong> You are responsible for, and agree to pay or reimburse us for, any and all taxes incurred in connection with your use of our services.  Further, you will indemnify and hold us and our Related Parties harmless from any sales, use, excise or similar taxes and all government permit or license fees, and any costs associated with the collection or withholding thereof, including penalties and interest.</p>

			<h4>4. INTELLECTUAL PROPERTY RIGHTS</h4>
			<p><strong>4.1. Limited License to mig33 Software.</strong> Subject to your compliance with the terms and conditions set forth in this Agreement, we grant you a personal, limited, non-exclusive, non-sublicenseable, non-assignable, royalty-free license to download, install and use the mig33 software on one mobile phone for your sole use and for the sole purpose of using the mig33 services and not for any other purpose.</p>
			<p><strong>4.2. Retention of Rights.</strong> We retain all intellectual property rights (including, but not limited to, any and all patents, copyrights, moral rights, trademarks, trade secrets and any other form of intellectual property rights recognized in any jurisdiction, including applications and registrations for any of the foregoing) embodied in or relating to the Site, the mig33 software and the services, the design or operation thereof, any modification or enhancements thereto and any other technical information relating to the provision thereof (collectively, "<strong>Intellectual Property Rights</strong>").  You must not do anything that would jeopardize, damage, limit or interfere with our Intellectual Property Rights or our interest in them. No license is granted under this Agreement except the limited licenses pursuant to Sections 4.1 and 5.2 hereof.</p>

			<h4>5. MERCHANT PROGRAM</h4>
			<p><strong>5.1. Merchant Program Features.</strong>  You have the option, at no additional charge, to register for our Merchant Program.  If you are registered for our Merchant Program, you will receive a discount on mig33 credits per our current price list and may freely transfer credit balances on your accounts to other users and/or convert your credit balances, in whole or in part, into vouchers and pre-paid cards.</p>
			<p><strong>5.2. Limited Trademark License.</strong>  If you are registered for our Merchant Program, we grant you a personal, limited, non-exclusive, non-sublicenseable, non-assignable, royalty-free license to use the mig33 name and associated images (collectively, the "<strong>Licensed Mark</strong>") solely for the purpose of selling and offering for sale credit balances, vouchers, and/or prepaid cards for third parties in your own name and for your own account, and for no other purpose.  In using the Licensed Mark, you agree that you will not purport or imply that you are our employee, partner, joint venturer, authorized representative or otherwise in a position to make legally binding statements or declarations on our behalf.</p>
			<p><strong>5.3. Regulatory Compliance.</strong>  Without limiting the generality of Section 1.3(a) hereof, you agree to monitor and comply with all applicable regulatory requirements imposed by your jurisdiction or any other jurisdiction with respect to your participation in the Merchant Program, including, but not limited to, any requirement to obtain a license as a reseller of telecommunications services.</p>


			<h4>6. DISCLAIMER OF WARRANTY</h4>
			<p><strong>THE SITE, THE MIG33 SOFTWARE, THE MIG33 SERVICES AND THE THIRD PARTY CONTENT ARE PROVIDED "AS IS", AND WE DO NOT REPRESENT OR WARRANT THAT THE SITE, THE MIG33 SOFTWARE OR THE MIG33 SERVICES WILL ALWAYS BE AVAILABLE, ACCESSIBLE, UNINTERRUPTED, TIMELY, SECURE, ACCURATE, COMPLETE, ERROR-FREE OR WILL OPERATE WITHOUT DATA LOSS, NOR DO WE WARRANT ANY PARTICULAR QUALITY OF THE WEB SITE, SOFTWARE OR SERVICES.  WE DISCLAIM ANY AND ALL OTHER WARRANTIES AND REPRESENTATIONS (EXPRESS OR IMPLIED, ORAL OR WRITTEN) WITH RESPECT TO THE SITE, THE MIG33 SOFTWARE, THE MIG33 SERVICES OR THE THIRD PARTY CONTENT WHETHER ALLEGED TO ARISE BY OPERATION OF LAW, BY REASON OF CUSTOM OR USAGE IN THE TRADE, BY COURSE OF DEALING OR OTHERWISE, INCLUDING ANY AND ALL (A) WARRANTIES OF MERCHANTABILITY, (B) WARRANTIES OF FITNESS OR SUITABILITY FOR ANY PURPOSE (WHETHER OR NOT WE KNOW, WE HAVE REASON TO KNOW, WE HAVE BEEN ADVISED OR WE ARE OTHERWISE AWARE OF ANY SUCH PURPOSE), (C) WARRANTIES OF NONINFRINGEMENT OR CONDITION OF TITLE, AND (D) WARRANTIES THAT THE SITE, THE MIG33 SOFTWARE OR THE MIG33 SERVICES WILL OPERATE WITHOUT INTERRUPTION OR ERROR.  YOU ACKNOWLEDGE AND AGREE THAT YOU HAVE RELIED ON NO WARRANTIES.</strong></p>


			<h4>7. LIMITATION OF LIABILITY</h4>
			<p><strong>7.1. LIMITED LIABILITY.</strong></p>
			<p><strong>NEITHER WE NOR OUR RELATED PARTIES ARE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOSS OF PROFITS, LOSS OF USE, LOSS OF REVENUE, LOSS OF GOODWILL, ANY INTERRUPTION OF BUSINESS, LOSS OF OR DAMAGE TO BUSINESS OR REPUTATION, LOSS OF OPPORTUNITY, LOSS OF ADVANTAGE, LOSS OF USE OF ANY SOFTWARE OR DATA, LOSS OF USE OF ANY MOBILE PHONE OR OTHER EQUIPMENT, LOSS OF USE OF THE SYSTEM ON WHICH THE SITE, MIG33 SOFTWARE OR MIG33 SERVICES ARE USED, OR FOR ANY INDIRECT, SPECIAL, INCIDENTAL, EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, THE SITE, THE MIG33 SOFTWARE, THE MIG33 SERVICES OR THIRD PARTY CONTENT, REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, EVEN IF WE HAVE BEEN ADVISED OR ARE OTHERWISE AWARE OF THE POSSIBILITY OF SUCH DAMAGES. </strong></p>
			<p><strong>IN NO EVENT SHALL OUR AND OUR RELATED PARTY'S TOTAL CUMULATIVE LIABILITY FOR ANY LOSS OF PROFITS, LOSS OF USE, LOSS OF REVENUE, LOSS OF GOODWILL, ANY INTERRUPTION OF BUSINESS, LOSS OF OR DAMAGE TO BUSINESS OR REPUTATION, LOSS OF OPPORTUNITY, LOSS OF ADVANTAGE, LOSS OF USE OF ANY SOFTWARE OR DATA, LOSS OF USE OF ANY MOBILE PHONE OR OTHER EQUIPMENT, LOSS OF USE OF THE SYSTEM ON WHICH THE SITE, MIG33 SOFTWARE OR MIG33 SERVICES ARE USED, OR FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, THE SITE, THE MIG33 SOFTWARE, THE MIG33 SERVICES OR THIRD PARTY CONTENT, REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, EVEN IF WE OR OUR RELATED PARTIES HAVE BEEN ADVISED OR ARE OTHERWISE AWARE OF THE POSSIBILITY OF SUCH DAMAGES, EXCEED THE AMOUNT PAID BY YOU FOR YOUR USE OF THE MIG33 SERVICES AND THE MIG33 SOFTWARE IN THE SIX (6) MONTHS PRIOR TO THE ACCRUAL OF THE FIRST CLAIM.  MULTIPLE CLAIMS WILL NOT EXPAND THIS LIMITATION.  THIS SECTION WILL BE GIVEN FULL EFFECT EVEN IF ANY REMEDY SPECIFIED IN THIS AGREEMENT IS DEEMED TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.</strong></p>
			<p><strong>7.2. Events Beyond Our Control.</strong> We and our Related Parties are not liable for any delay or default in performance under this Agreement caused by an event beyond our reasonable control, including but not limited to, war, accident, act of God, industrial action, embargo or a delay, failure or default by you, your wireless carrier, or any other supplier of goods or services to us or to you.</p>
			<p><strong>7.3. External Links.</strong> Without limiting the generality of the foregoing, we may provide third party content on the Site and may provide links to Web pages and content of third parties (collectively, our "<strong>Third Party Content</strong>") as a service to those interested in this information.  We do not monitor or have any control over any Third Party Content or third party Web sites.  We do not endorse or adopt any Third Party Content and can make no guarantee as to its accuracy or completeness.  We do not represent or warrant the accuracy of any information contained therein, and we undertake no responsibility to update or review any Third Party Content.  You use such Third Party Content contained therein at your own risk.</p>


			<h4>8. REPRESENTATION AND WARRANTY; INDEMNITY</h4>
			<p>You represent and warrant that you will: (a) comply with all of your wireless carrier's terms and conditions; and (b) not breach any of the terms set forth in this Agreement.</p>
			<p>You agree to indemnify and hold us and our Related Parties harmless from and against any and all actual or threatened suits, actions, proceedings (at law or in equity), claims (groundless or otherwise), damages, payments, deficiencies, fines, judgments, settlements, liabilities, losses, costs and expenses (including, but not limited to, reasonable attorneys’ fees, costs, penalties, interest and disbursements) resulting from any claim (including third party claims), suit, action or proceeding  against us or our Related Parties, whether successful or not, resulting from, arising in connection with or relating to: (a) your breach of any term of this Agreement or any policy or guidelines referred to in it; (b) your use or misuse of the Site, the mig33 software or the mig33 services; or (c) any breach of any of your representations and warranties.</p>

			<h4>9. SUSPENSION OF SERVICE</h4>
			<p><strong>9.1. Suspension for Any Reason.</strong>  We may suspend your use of our services, in whole or in part, at our sole discretion without notice at any time and for any reason, including, but not limited to, the following: (a) we decide that our services need maintenance or upgrading; (b) you have not incurred a charge for using the services for 3 months; (c) you or anyone else using your mobile phone, are in breach of any of this Agreement; or (d) any third party takes action or threatens to take action against us for providing any services.</p>
			<p><strong>9.2. Continuing Liability.</strong>  You remain liable for all charges due under this Agreement throughout the period of any suspension (including, but not limited to, any periodic access fees) unless we, in our sole discretion, determine otherwise.</p>


			<h4>10. TERMINATION</h4>
			<p><strong>10.1. Termination by You.</strong> You may terminate this Agreement, for cause or no cause, by notifying us in accordance with Section 11.3.  Any credit in your account at the time will be lost.</p>
			<p><strong>10.2. Termination by Us.</strong>  We may terminate this Agreement, for cause or no cause, with 14 days' notice to you.  Moreover, we may terminate this Agreement immediately without notice if: (a) you, or any user of your mobile phone, breaches any of the terms of this Agreement (including, but not limited to, any restriction set forth in Section 1.3); (b) you, or any user of your mobile phone, damages a phone network or puts a phone network at risk or abuses or threatens our staff; (c) you do not pay mig33 charges as required under Section 3; (d) you have not incurred a charge for using our services for 3 months; (e) your credit is zero or negative for 3 months; (f) you become bankrupt or insolvent or make an arrangement with your creditors; (g) your mobile phone network is no longer compatible with our services; (h) your mobile phone number is withdrawn; or (i) we are ordered by any court or government agency to cancel our services or your use thereof.</p>
			<p><strong>10.3. Loss of Credits upon Termination.</strong> You will lose any credits left on your account at the time of termination of the Agreement.  These credits cannot be converted into or redeemed for cash, or applied against any other accounts you have with us.</p>
			<p><strong>10.4. Other Consequences of Termination.</strong> Upon termination of this Agreement for any reason: (a) you will no longer be able to use the services and you will forfeit any credits remaining on your account; (b) all licenses and rights to use the mig33 software and the mig33 services will immediately cease and you must remove the mig33 software from your mobile phone and delete all copies of the mig33 software in your possession; and (c) we can disable or delete any mig33 software you have installed without notice to you.</p>
			<p><strong>10.5. Survival.</strong> The provisions of Sections 1.3, 3, 4, 6, 7, 8, and any other provisions that by their nature should survive, shall survive any termination of this Agreement.</p>

			<h4>11. GENERAL</h4>
			<p><strong>11.1. Relationship of the Parties.</strong>  You acknowledge and agree that nothing in this Agreement, including, but not limited to, registration for our Merchant Program, constitutes an employment agreement or creates or acknowledges an employment relationship between you and us or makes us partners, joint venturers or otherwise participants in a joint undertaking.  Our relationship shall at all times be one of independent contractors.</p>
			<p><strong>11.2. Amendments.</strong>  We reserve the right to change or amend the terms of this Agreement at any time.  If we do this and the change is to your detriment, we will place a notice on <a href="http://www.mig33.com">www.mig33.com</a> or notify you by any other means we deem appropriate in our sole discretion.  It is your responsibility to check <a href="http://www.mig33.com">www.mig33.com</a> on a regular basis, including, without limitation, prior to using the Site, the mig33 software or the mig33 services.  Your continued use of the Site, the mig33 software or the mig33 services constitutes your acceptance of the revised terms.</p>
			<p><strong>11.3. Notices.</strong>  Notices by you to us hereunder shall be invalid unless made in writing (fax or signed document) to the fax number or mailing address listed on <a href="http://www.mig33.com">www.mig33.com</a>.  Notices by us to you may be made in any manner we deem appropriate in our sole discretion.</p>
			<p><strong>11.4. Assignment and Delegation.</strong>  You must not transfer your account or assign any of your rights or delegate any of your duties under this Agreement without our prior written approval.  We may freely transfer, assign or delegate this Agreement or its rights and duties under this Agreement.  Subject to the foregoing, this Agreement will be binding upon and will inure to the benefit of the parties and their respective representatives, heirs, administrators, successors and permitted assigns.  </p>
			<p><strong>11.5. Privacy.</strong>  The <a href="http://www.mig33.com/privacy.php">mig33 Privacy Policy</a> on <a href="http://www.mig33.com">www.mig33.com</a>, which is hereby incorporated into this Agreement, explains how we will handle your personal information.</p>
			<p><strong>11.6. Confidentiality.</strong>  You must keep any information you obtain relating to our software confidential and will not use such information for any purpose that is not specifically provided for in this Agreement or authorized by us in writing.</p>
			<p><strong>11.7. Severability.</strong>  If and to the extent any provision of this Agreement is held illegal, invalid, or unenforceable in whole or in part under applicable law, such provision or such portion thereof shall be ineffective as to the jurisdiction in which it is illegal, invalid or unenforceable to the extent of its illegality, invalidity or unenforceability, and shall be deemed modified to the extent necessary to conform to applicable law so as to give it the maximum effect intended. The illegality, invalidity or unenforceability of such provision in that jurisdiction shall not in any way affect the legality, validity or enforceability of such provision in any other jurisdiction or of any other provision in any jurisdiction</p>
			<p><strong>11.8. No Waiver.</strong>  Our failure or delay to exercise or enforce any right or claim does not constitute a waiver of such right or claim and shall in no way affect our right to later enforce or exercise it.</p>
			<p><strong>11.9. Headings.</strong>  The headings used in this Agreement are intended for convenience of reference only and in no way define, limit or describe the scope or substance of any of its provisions. </p>
			<p><strong>11.10. Governing Law and Jurisdiction.</strong>  This Agreement shall be governed by and construed in accordance with the laws of the State of California, United States of America. You consent to the jurisdiction of the State and federal courts serving San Mateo County, California, for any and all disputes arising under or in connection with this Agreement.</p>
			<p><strong>11.11. Prevailing Language.</strong>  The English language version of this Agreement shall be controlling in all respects and shall prevail in case of any inconsistencies with translated versions, if any.</p>

        </div>
    </div> <!-- end content -->
    <div class="clearfix"></div>

</div> <!-- end pageContent -->

<?php include("includes_corporate/page_footer.php"); ?>

</div> <!-- end pageContainer -->

<?php include("includes_corporate/footer_js.php"); ?>

</body>
</html>
